### ISSUE TITLE
Simple Example Non-responsive on OpenFL Neko

### ISSUE THREAD

**Issue by tienery** [haxeui/haxeui-core#10]
I decided to give HaxeUI a whirl out of curiosity today, but I have come across a rather unusually unresponsive window.

The code I am using is a relatively simple example, similar to that in the README:

```haxe
package;

import haxe.ui.components.Button;
import haxe.ui.containers.VBox;
import haxe.ui.core.Screen;
import openfl.display.Sprite;
import openfl.Lib;
import haxe.ui.Toolkit;

class Main extends Sprite 
{

	public function new() 
	{
		super();
		
		Toolkit.init();
        
        var main = new VBox();
        
        var btn1 = new Button();
        btn1.text = "Some Text";
        main.addComponent(btn1);
        
        Screen.instance.addComponent(main);
	}

}
```

I've narrowed down the issue to the `addComponent` on the `main` VBox object which causes the client to freeze. By commenting out that line, everything works as normal. A VBox is supposedly added to the screen, but I'm not seeing one ;) I'm assuming that is deliberate.

Let me know if you need any additional information.

**Comment by ianharrigan** [comment]
Ive never actually used it by extended `Sprite` and building it all up in the constructor, so that might be the issue (which would need to be fixed if it is the case). Can you try using one of the templates and see if you get the same issue: https://github.com/haxeui/haxeui-templates

Essentially, drop the `Sprite`, use a static entry point and build the UI there (just to see if thats the issue), eg:

```haxe
class Main {
    public static function main() {
        Toolkit.init();

        var main = new VBox();

        var btn1 = new Button();
        btn1.text = "Some Text";
        main.addComponent(btn1);

        Screen.instance.addComponent(main);
    }
}
```

**Comment by tienery** [comment]
I have tried that, and the same issue occurs. I have not yet installed the haxeui-templates. and if I may be honest, I don't know how (I'm looking into it). But once I have and tested the same example using the OpenFL template provided, we can trace down the issue.

**Comment by ianharrigan** [comment]
> All Flash Develop templates for all backends are kept in a single haxeui-templates.fdz (flash develop zip) file. This file can be downloaded here.

If you click that link you should get a `.fdz` file, double click on that and you will be asked if you want FD to install them, then when you create a new project you should have something like this:

![image](https://cloud.githubusercontent.com/assets/3024242/17836936/c7ffa940-67a4-11e6-871f-be6f311f3337.png)

**Comment by tienery** [comment]
Okay, I'm not sure exactly what I did... but it works...

I was testing things way too quickly I lost the exact time I fixed the problem. Now both examples are working properly. I did just reinstall OpenFL version 4 and used that over the dev build that I was using, so perhaps that may have been the cause of the problem.

**Comment by ianharrigan** [comment]
Possibly, well, at least its working. Thats the important part. ;)
