### ISSUE TITLE
real-time xml-parser

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#100]
Hi. Is there way to parse xml-ui at runtime?
Thanks.

**Comment by ianharrigan** [comment]
Hi,

Sure. Checkout `Toolkit.componentFromString`

Cheers,
Ian

**Comment by r3d9u11** [comment]
Thanks for answer. Is it possible to load a complex ui like a:
```
<component-container1>
   <component-container2>
      <button1/>
      <button2/>
      <button3/>
   </component-containt2>
</component-container1>
```
or only standard component Toolkit.componentFromString("<button ... />", ...) ?
I can't find description of this function and parameters. Do you have some example, how to work with it?

**Comment by ianharrigan** [comment]
what is `<component-container />`

**Comment by r3d9u11** [comment]
it is a example name.
instread "component-container" must be one of:

Containers:

    Accordions
    Boxes
    Calendar Views
    Continuous Boxes
    Frames
    Grids
    List Views
    Menu Bars
    Panel Lists
    Rich Text Views
    Scroll Views
    Stacks
    Table Views
    Tab Views
```

something like a:
...
...
<Scroll...>
   <HGrid...>
      <button1 .../>
      <button2 .../>
      <button3 .../>
   </HGrid...>
</Scroll...>
...
```

**Comment by ianharrigan** [comment]
The `Toolkit.componentFromString` works similar to the macro version... first the XML is parsed into a tree of `ComponentInfo`  and then the component is built from that. The difference is the macro version builds the code an places it in your .hx file and the runtime version just builds the actual component at runtime. So any valid xml should work:

`Toolkit.componentFromString("<vbox><button />...</vbox>")`

or 

`Toolkit.componentFromString(myXMLString)`

and `myXMLString` could be loaded from a resource, file system, http, however you want.

**Comment by r3d9u11** [comment]
Thanks for help!

**Comment by ianharrigan** [comment]
No probs!
