### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#104]
## Expected Behavior
compilation was failed with error: `~/.haxelib_repo/haxeui-core/git/haxe/ui/Toolkit.hx:267: characters 2837-2850 : Class<Math> has no field MathImpl`

## Your Environment
* Version used: haxeui-core current version from git, haxe 3.4.0
* Operating System and version (desktop or mobile): Linux Mint 18.1 x64
* Link to your project: [Button.zip](https://github.com/haxeui/haxeui-core/files/749933/Button.zip)

**Comment by ianharrigan** [comment]
Should be fixed for now, leave this open though as we need to find out why this happens in haxe 3.4

**Comment by r3d9u11** [comment]
Ok. 
Thanks, works fine now.
