### ISSUE TITLE
Dropdowns on OpenFL (Neko) do not appear as expected

### ISSUE THREAD

**Issue by tienery** [haxeui/haxeui-core#11]
As I mentioned on Twitter quite recently, I thought that dropdowns had been properly implemented and that it just worked. Although you (Ian) mentioned that OpenFL should work, I'm getting some unusual results.

Here is the XML code I'm using:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox id="tools">
    <hbox>
        <dropdown id="type" style="height: 30px; width: 120px; vertical-align: bottom;">
            
        </dropdown>
    </hbox>
</vbox>
```

Now, I'm not sure if that's the correct XML for dropdown because I'm just testing things out. However, I'm having very weird issues revolving around dropdowns.

Firstly, these are the results for the above XML:

![img](http://image.prntscr.com/image/a5947015b9504da8a81fa1ddf093a471.png)

Now, I want to make sure if that above XML is correct before I start posting additional issues because it may just be the fact that the XML is wrong.

**Comment by tienery** [comment]
Okay, I've just modified the XML to be:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox id="tools">
    <hbox>
        <dropdown id="type" text="A dropdown" style="height: 30px; width: 120px; vertical-align: bottom;">
            
        </dropdown>
    </hbox>
</vbox>
```

And the results are:

![img](http://image.prntscr.com/image/d3b1821edd3a42cb9235fa0767632d0e.png)

Of course, the scroll bar still appears when it shouldn't because no items in the dropdown exist.

**Comment by ianharrigan** [comment]
ok, so yeah, there is an issue there about them not having data, leave this issue open and ill fix it when i get some time, in the mean time try:

```xml
<dropdown text="Dropdown">
    <data>
        <item text="Item 1" />
        <item text="Item 2" />
        <item text="Item 3" />
        <item text="Item 4" />
    </data>
</dropdown>
```

**Comment by ianharrigan** [comment]
Can you retest this with latest and close if its fixed?

Cheers.

**Comment by tienery** [comment]
Retested and I can confirm it works now :+1:
