### ISSUE TITLE
bind listview to array

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#112]
Hi. How I can to bind listview to array of strings?
I tried to use example from old haxeui:
```
<?xml version="1.0" encoding="utf-8" ?>
<listview width="300" height="100%">
    <array>
        Item 1,
        Item 2,
        Item 3
    </array>
</listview>
```
but I got notice:
`.haxelib_repo/haxeui-core/git/haxe/ui/macros/ComponentMacros.hx:131: WARNING: no class found for component: array`
and blank list:
![123](https://cloud.githubusercontent.com/assets/15020827/23202072/653a23be-f8ed-11e6-9a1f-105cd9de4fe1.png)

also I tried to change xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<listview width="300" height="100%">
    <data>
       <item text="Item 1" value="1" />
       <item text="Item 2" value="2" />
       <item text="Item 3" value="3" />
    </data>
</listview>
```
but I got same result as in [issue 107](https://github.com/haxeui/haxeui-core/issues/107)

haxeui-core from git
haxeui-openfl from git
target: neko
haxe 3.4.0
Linux Mint 18.1 x64

Thanks.

**Comment by ianharrigan** [comment]
The xml in your second example is the correct xml, and works fine this end. Im wondering if this error is something to do with haxe 3.4? Do other targets work? cpp? What about different backends? say, haxeui-html5?

**Comment by r3d9u11** [comment]
Yes, both components (DropDownList and ListView) are works fine for -cpp target. But for -neko they are have I similar exception:
```
$ openfl test linux -64 -neko
Called from ? line 1
Called from ApplicationMain.hx line 80
Called from ApplicationMain.hx line 100
Called from lime/app/Preloader.hx line 201
Called from lime/app/Preloader.hx line 314
Called from openfl/display/Preloader.hx line 51
Called from a C function
Called from openfl/events/EventDispatcher.hx line 97
Called from openfl/display/DisplayObject.hx line 363
Called from a C function
Called from openfl/events/EventDispatcher.hx line 218
Called from openfl/display/Preloader.hx line 290
Called from openfl/display/Preloader.hx line 229
Called from a C function
Called from openfl/events/EventDispatcher.hx line 97
Called from openfl/display/DisplayObject.hx line 363
Called from a C function
Called from openfl/events/EventDispatcher.hx line 218
Called from openfl/display/Preloader.hx line 109
Called from a C function
Called from lime/app/Preloader.hx line 220
Called from lime/_macros/EventMacro.hx line 101
Called from ApplicationMain.hx line 203
Called from openfl/display/Stage.hx line 1238
Called from ApplicationMain.hx line 199
Called from haxe/ui/macros/ComponentMacros.hx line 191
Called from haxe/ui/containers/ListView.hx line 148
Uncaught exception - Invalid call
```
I think that something wrong with `haxe.ui.data.*` for neko target, because components with empty data will displayed without exception:

this samples will works fine for neko target:
ListView:
```
<?xml version="1.0" encoding="utf-8" ?>
<listview width="300" height="100%">
	<data>
	</data>
</listview>
```
and DropDown:
```
<?xml version="1.0" encoding="utf-8"?>
<dropdown text="Select Item" width="250">
	<data>
	</data>
</dropdown>
```

**Comment by r3d9u11** [comment]
openfl 6.1.2, haxeui-core and haxeui-openfl from git (master)
```
$ openfl test linux -neko
Uncaught exception - load.c(181) : Module not found : -livereload
```
so, maybe this will be resolved with neko in future...
