### ISSUE TITLE
can't see progress-bar

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#113]
Hi. The progress bar cannot be displayed.
![progr](https://cloud.githubusercontent.com/assets/15020827/23203337/22401144-f8f3-11e6-8c10-6245bae60cf2.png)

UI.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<progress min="0" max="100" pos="75"/>
```
[progr.zip](https://github.com/haxeui/haxeui-core/files/792672/progr.zip)

Linux Mint 18.1 x64
haxe 3.4.0
haxeui-core from git
haxeui-openfl from git
openfl 4.8.0
lime 3.7.3
target: neko

Thanks.

## UPD:
VProgress and HProgress are works fine. Is "Progress" just an abstract component and haven't default direction?

**Comment by ianharrigan** [comment]
Hi,

its `hprogress` or `vprogress`, same goes for sliders and scrollbars. :)

Im might think about aliasing the horizontal versions but not sure.

**Comment by r3d9u11** [comment]
Thank for hint,  I'll have to remember that for other components!

**Comment by ianharrigan** [comment]
Yeah, there is possibly scope to have things like this in the `module.xml` of haxeui-core:

```xml
<class name="haxe.ui.components.HProgress" alias="progress" />
```

Then you could use it as progress, another possible option is to allow something like this in the ui markup:

```xml
<progress direction="vertical" />
```

But i need to think about it a little more
