### ISSUE TITLE
Collection of samples for a novice users

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#115]
Hi. As the study I created  and published a [little collection of samples ](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.7_HaxeUI) for a novice users. Hope this can be useful for someone.

The collection will be expanded.

**Comment by aW4KeNiNG** [comment]
Nice repo :) Good job.

**Comment by ianharrigan** [comment]
Very nice repo, very full!

**Comment by MSGhero** [comment]
I'm on my phone so maybe I can't tell, but it'd be cool if you could also put an image of what the layout looks like. That way the other backends can compare their results to openfl's.

**Comment by r3d9u11** [comment]
@MSGhero No problem. I'll attach images little later

**Comment by r3d9u11** [comment]
@MSGhero I added screenshots for all samples of HaxeUI

**Comment by MSGhero** [comment]
Nice thanks! I'm working on the flixel backend this weekend, and this is easier than going back and forth between backends :)

**Comment by ianharrigan** [comment]
Im going to close this issue, but still, just want to say, amazing job in general (not just haxeui, but the whole repo is great!).
