### ISSUE TITLE
data item can't display text

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#116]
## Expected Behavior
data item cannot display text and shows value instead it

## Current Behavior
must be displayed "Item 1", "Item 2", "Item 3"

## Test app / minimal test case
ListView [sample](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.7_HaxeUI/9.7.1_haxeui-openfl/9.7.1.1_Components/ListView)
DropDown [sample](https://github.com/r3d9u11/haxe-basics/tree/master/9_AdditionalLibraries/9.7_HaxeUI/9.7.1_haxeui-openfl/9.7.1.1_Components/DropDown)

## Your Environment
Haxe 3.4.0
hxcpp 3.4.49
Target: only CPP (neko still not working with data item)
haxeui-core from git
haxeui-openfl from git
OS Linux Mint 18.1 x64

Thanks.

**Comment by ianharrigan** [comment]
Hi, ive lost the samples, can you point me in the right direction?

Cheers,
Ian
