### ISSUE TITLE
ScrollView addComponent, VBox or HBox, doesnt work 

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#12]
I have some components defined in XML.  During a button click I remove previous component and add new component.  Both are VBox components.   When new component is added nothing appears, and there are no errors. The only code that appears to get run is "v = _contents.addComponent(child);".  Everything else does not apply.  

In order to get it to work I change ScrollView.hx at line 100 from

if (Std.is(child, HScroll) || Std.is(child, VScroll)) {
to 
if (Std.is(child, HScroll) || Std.is(child, VScroll) || Std.is(child, VBox) || Std.is(child, HBox) ) {

This, however, seems to break the Dropdown component that you added recently.  I am not sure my fix is the best approach

**Comment by ianharrigan** [comment]
Ok, great, ill look into it. Thanks.

Do you happen to have a small reproducible test app? Will certainly speed things up.

Cheers,
Ian

**Comment by hoseyjoe** [comment]
I just made one based on the html template
[Small.zip](https://github.com/haxeui/haxeui-core/files/432980/Small.zip)

**Comment by ianharrigan** [comment]
Hey Joe, so this should be fixed now. Can you retest and close if fixed whenever you get a moment?

Cheers,
Ian

**Comment by hoseyjoe** [comment]
This appears fixed but #23  may be a result?

**Comment by hoseyjoe** [comment]
fixed
