### ISSUE TITLE
[enhancement] eliminate unnecessary explicit equality checks boolVar == true/boolVar == false all over the codebase

### ISSUE THREAD

**Issue by jeebus3000** [haxeui/haxeui-core#121]
Hello! 
Great project, I wish it success and long life.
_I know, my opinion would be more valuable if I were a contributor._ Obvious antipatterns are triggering my OCD :D

**Comment by kobi2187** [comment]
Hi, I can do that, if @ianharrigan doesn't mind. 
it's a code style preference, that's all. However, when things are cleaner, it may help refactoring and may lead to better code.
In any case, simple regexes can probably do that, or most of it.

**Comment by ianharrigan** [comment]
Thanks Kobi, but dont worry, it is on my list to clean this all up. I have checkstyle installed so the idea is to get down to 0 issues. And i want to have a bit of a refactor while im there.

Thank again.

Ian
