### ISSUE TITLE
DropDown / ListView too slow for more than ~30 items.

### ISSUE THREAD

**Issue by chatziko** [haxeui/haxeui-core#129]
Tested with openfl-html5.

If I create a DropDown with 25-30 items, it already feels quite sluggish when its ListView opens. With 60 items it becomes completely unusable. This is by no means an "extreme" number, I see it as a big limitation.

I guess the solution would be to only render the visible items. I found [this discussion](https://github.com/ianharrigan/haxeui/issues/54#issuecomment-35104037) about "virtual scrolling" for haxeui v1, I don't know whether this has been implemented for v2.

**Comment by ianharrigan** [comment]
Yeah, they arent high numbers. Ill have a play, it should be fine to be honest. What backend are you using? There is a branch that still needs to be merged (being slow on my part) that should increase things pretty hugely - But still might be optimizations that could be made anyway. 

I would like to implement virtual scrolling for v2, for sure, but its not going to happen just yet.

Ill look into it. 

Ian

**Comment by chatziko** [comment]
openfl with html5

**Comment by ianharrigan** [comment]
do you have a sample for me to play with, just so i dont spend ages on the wrong thing. 

Also, im screwed up listviews (visually) with the last commit - so ignore that! :)

**Comment by ianharrigan** [comment]
Can this be retested and see if its still an issue? Thanks.

**Comment by chatziko** [comment]
Sorry, I switched to a different implementation so I'm no longer in position to test this. Feel free to close it if there's nobody else affected.

**Comment by ianharrigan** [comment]
OK, thanks.
