### ISSUE TITLE
Wrapping text in label, button, text doesnt resize/re-position component

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#13]
Wrapping text because of width limit doesn't re position or resize the component inside VBox.  I am testing in HTML but the same is true in nme
## Expected Behavior

I would expect other components in VBox below to position down in order to make room
## Current Behavior

They dont
## Test app / minimal test case

```
<?xml version="1.0" encoding="utf-8"?>
<vbox id="main">
        <button id="testButton1" styleNames="big-button" text="Click Me!  Alot of times.  I dont do anything really" width="50" />
        <label text="comp1 comp1 comp1 comp1 comp1 comp1 comp1 comp1 comp1 comp1" width="50" style="horizontal-align: center; font-size:35px; color: #888888;" />
        <label text="comp2" style="horizontal-align: center; font-size:35px; color: #888888;" />
        <text text="text box text box text box text box text box text box text box text box " width="50" />
    <text text="Nothing to add"/>
</vbox>
```

**Comment by ianharrigan** [comment]
Perfect, ill check it out. I believe text wrapping only works correctly in openfl at the moment, and even then i belive its a #if def, so not ideal. 

Thanks for the test case! :)

Ian

**Comment by hoseyjoe** [comment]
I changed the bug.  I was wrong text wrapping in  some text works in NME

**Comment by hoseyjoe** [comment]
Im saying this is fixed
