### ISSUE TITLE
Dropdown listview not showing any values

### ISSUE THREAD

**Issue by f-rank** [haxeui/haxeui-core#130]
Values from an ArrayDataSource() should display like always when setting
somethingsomething.dataSource= someArrayDataSource;
and I can actually see the values if I trace (somethingsomething.get(number));
but it just doesn't show now on the dropdown anymore.
Was working up to two days ago.

EDIT 1: if I checkout something older it starts throwing:
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/components/TextField.hx:104: characters 16-36 : haxe.ui.core.TextInput has no field color
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/components/TextField.hx:107: characters 16-39 : haxe.ui.core.TextInput has no field fontName
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/components/TextField.hx:110: characters 16-39 : haxe.ui.core.TextInput has no field fontSize
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/components/TextField.hx:113: characters 16-40 : haxe.ui.core.TextInput has no field textAlign
Build halted with errors.

EDIT 2:if I recover https://github.com/haxeui/haxeui-core/blob/1bb4ee339ba2a3cfc0ec6a983b74e3d7850b9e1e/haxe/ui/containers/ListView.hx
it does again display the data source items. So something changed in ListView after hash 1bb4ee3

**Comment by ianharrigan** [comment]
Do you have a sample that used to work and doesnt now?

Cheers,
Ian

**Comment by f-rank** [comment]
Yes. If this doesn't translate well just let me know.

Declaring:
                        var selector_de_jogador_VIS_2:DropDown = new DropDown();
                        var jogadoresVis = new ArrayDataSource();
			jogadoresVis.add({value:vis1num+" "+vis1, jogador:vis1, path:"", numero:vis1num});

and after code entry point:
                        selector_de_jogador_VIS_2.width = 260;
			selector_de_jogador_VIS_2.height = 40;
			selector_de_jogador_VIS_2.listHeight = 200;
			selector_de_jogador_VIS_2.left = 2000.0;
			selector_de_jogador_VIS_2.top = 640.0;
			selector_de_jogador_VIS_2.text = "JOGADOR VISITANTE";
			selector_de_jogador_VIS_2.dataSource = jogadoresVis;
			selector_de_jogador_VIS_2.fontSize = 20;
			selector_de_jogador_VIS_2.onChange = function (e)
			{
				selector_de_jogador_VIS_2.includeInLayout = true;
				selector_de_jogador_VIS_2.text = selector_de_jogador_VIS_2.selectedItem.value;
				JOG_VISITANTE = selector_de_jogador_VIS_2.selectedItem.value;
				trace(selector_de_jogador_VIS_2.selectedItem.value);
			}

This displays the populated dropdown with the Listview.hx at hash 1bb4ee3 but not with the latest update. Think this is the minimum code example.

Thanks.

**Comment by ianharrigan** [comment]
Ok, i can reproduce it with:

```haxe
            var dropdown:DropDown = new DropDown();
            dropdown.text = "Foo";
            main.addComponent(dropdown);
            
            var ds = new ArrayDataSource();
            ds.add( { value: "Bar" } );
            dropdown.dataSource = ds;
```

**Comment by ianharrigan** [comment]
Ok, that should be fixed now. Can you retest and close if its working?

Thanks,
Ian

**Comment by f-rank** [comment]
Retested and working flawless.

Thanks!
