### ISSUE TITLE
ListView should allow for multiple selections. 

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-core#132]
Currently the ListView component only allows for single selections. This should be expanded to allow for multiple selections. 

## Expected Behavior
Holding down SHIFT or CTRL should allow multiple selections to be made, if the listview is set to allow for multiple selections (possibly `allowMultipleSelection` or something less verbose if possible - `selectionMode='multiple'` might make more sense). 

## Current Behavior
Currently there is no multiple selection at all.

**Comment by aW4KeNiNG** [comment]
This issue is related to #84 

Currently I have an implementation with several behaviours. I need to clean some code, etc...

When I have time, I will upload a PR.

**Comment by ianharrigan** [comment]
Cleaning up issues, pretty sure this is done! :)

Hope you are well man!

Ian
