### ISSUE TITLE
Add support to change the title if available

### ISSUE THREAD

**Issue by elnabo** [haxeui/haxeui-core#134]
PR Status
- [x] https://github.com/haxeui/haxeui-hxwidgets/pull/13 (supported)
- [x] https://github.com/haxeui/haxeui-openfl/pull/15 (supported)
- [x] https://github.com/haxeui/haxeui-xwt/pull/7 (supported)
- [x] https://github.com/haxeui/haxeui-flixel/pull/7 (supported)
- [x] https://github.com/haxeui/haxeui-html5/pull/21 (supported)
- [x] https://github.com/haxeui/haxeui-pixijs/pull/7 (supported)
- [x] https://github.com/haxeui/haxeui-flambe/pull/4 (js or warning)
- [x] https://github.com/haxeui/haxeui-kha/pull/15 (js or warning)
- [x] https://github.com/haxeui/haxeui-nme/pull/16 (js or warning)
- [x] https://github.com/haxeui/haxeui-luxe/pull/3 (js or warning)

**Comment by MSGhero** [comment]
Can you add the flixel lib and just copy OpenFL's PR over, importing `flash.Lib` so it compiles?

**Comment by elnabo** [comment]
Ok it's on the todo list.

**Comment by elnabo** [comment]
Are you ok,  on how I do it for target that do not support it such as html5 ?

**Comment by MSGhero** [comment]
I think it has to be defined in every backend. If that target doesn't support changing the title, it should just be blank. So yeah your HTML5 example is fine if it's not possible to change there.

**Comment by elnabo** [comment]
Ok, i've finished adding compatibility to all backends.

**Comment by ianharrigan** [comment]
So one thing, in the haxeui-html5 could possibly set the page title? That might be neat.

Another thing, i wonder if this should be an initialisation option rather than a properly on screen?

**Comment by ibilon** [comment]
> Another thing, i wonder if this should be an initialisation option rather than a properly on screen?

It's useful to be able to change it, for instance web browser show the current tab title as window title, most editing app show the open file's name.

**Comment by elnabo** [comment]
> So one thing, in the haxeui-html5 could possibly set the page title? That might be neat.

It could be possible to set the page title via js. However, I think you can put multiple application on the same page, so the page title doesn't really correspond to the application title. So, I'm unsure what best in this case.

**Comment by ianharrigan** [comment]
@ibilon - fair point, might want it to be dynamic. 

@elnabo - in that case, having multiple apps on the same page, would you not just opt to not use title?

**Comment by elnabo** [comment]
So, changing haxeui-html5 & haxeui-pixijs to use the page title as the application title.

**Comment by ianharrigan** [comment]
I might make sense... i mean, if its possible, makes sense to implemented in as many backends as possible.

**Comment by elnabo** [comment]
I've updated html5 & pixijs to use base js to change the title.

**Comment by elnabo** [comment]
And the other to display a warning to display a warning when title cannot be changed.

**Comment by ianharrigan** [comment]
Ok, all looks great... so one i accept all the PRs, this can be closed, right?

**Comment by elnabo** [comment]
Yeah, it is what I had in mind.

**Comment by ianharrigan** [comment]
Single remark here, but not sure if its relevant: https://github.com/haxeui/haxeui-nme/pull/16

**Comment by ianharrigan** [comment]
Great... thanks @elnabo - all merged.... thanks again!
