### ISSUE TITLE
ListView unclickable with haxeui-hxwidget

### ISSUE THREAD

**Issue by elnabo** [haxeui/haxeui-core#137]
## Expected Behavior
Clicking an item of a `ListView` should trigger `onItemClick`.

## Current Behavior
Nothing happen. `onItemClick` is bound to `Mouse.CLICK` which correspond to clicking on `Button` or similar. However the `ItemRenderer` are  `Label` which doesn't generate such events.

## Possible Solution
- Change the `ItemRenderer` to `Button` but this will not look good.
- Change `onItemClick` to trigger on `Mouse.LEFT_DOWN` but this will change the behavior of all other backends. Or possibly add the Mouse.LEFT_DOWN trigger only for hxwidget (maybe also xwt) in ListView

## Steps to Reproduce (for bugs)
1. Have a ListView with items
2. Compile with haxeui-hxwidget
3. Try to click on an item

**Comment by ianharrigan** [comment]
The thin im not sure about here is that, ideally, the list should be 100% native. The issue there then is that itemrenders wont work. It would be nice to be able to "detect" if you are using something more advanced that a BasicItemRenderer and then switch to a composite ListView, and if not, use standard wx version

**Comment by ianharrigan** [comment]
for example:

![image](https://user-images.githubusercontent.com/3024242/26906917-fc6cf752-4bef-11e7-8975-2bd1a16c746a.png)

**Comment by ianharrigan** [comment]
Probably a better image: 
![image](https://user-images.githubusercontent.com/3024242/26907725-d6f6bee4-4bf5-11e7-8fa5-f3dcd71ebf1b.png)

But it i think, in keeping with the "spirit" of haxeui it would better to use pure native components where possible. I think, that there should also be a way to work out if the itemrenderer is something more complex too, but ill look at that tomorrow.

**Comment by ianharrigan** [comment]
Is this still an issue with the latest master branch?
