### ISSUE TITLE
Color previously defined in flixel

### ISSUE THREAD

**Issue by MSGhero** [haxeui/haxeui-core#140]
The `color` property that was recently added to Component is conflicting with a Flixel-defined `color`.

Flixel: `color(default, set):FlxColor`, where `FlxColor` is an abstract `from Int from UInt to Int to UInt`.
Core: `color:Null<Color>`, where `Color` is an abstract `from Int`.

cc: @nospoone

**Comment by ianharrigan** [comment]
Ah... Might have to #if def it... :(

**Comment by MSGhero** [comment]
Is renaming to `componentColor` too much? If so, I'll make the #if PR later.

**Comment by ianharrigan** [comment]
im not sure... might either remove it or #if def it... let me thing about it... its not critical really... its essentially the text colour so doesnt even really apply to all components. backgroundColor and borderColor i think are more important.

**Comment by ianharrigan** [comment]
The main problem with #if def is that then if you use `color` in xml its likely to cause an error as `FlxColor` probably wont map

**Comment by MSGhero** [comment]
You said it's the text color, so would it work to rename it? `textColor` to go with `borderColor` and `backgroundColor`?

**Comment by ianharrigan** [comment]
Yeah, i was thinking something similar, `textColour`, `foreColor`... i think text colour makes the most sense. I might move it out of `Component` too

**Comment by MSGhero** [comment]
Any updates on this?

**Comment by ianharrigan** [comment]
Not yet, but i think `textColor` is the way to go.
