### ISSUE TITLE
compile time error in Component.hx redefinition of width,height defined in DisplayObject

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#157]
error msg
C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe/ui/core/Component.hx:1464: characters 21-47 : Redefinition of variable width in subclass is not allowed. Previously declared at flash.display.DisplayObject

setup:
windows7 sp1
haxedevelop
openfl
haxeui v2
flash and html5 targets

i'm new to git) and haxeui, i managed to use haxeui 1, but want to use openfl dobj container and haxeui elements together. any help pls?))

**Comment by MSGhero** [comment]
Do you have `haxeui-openfl` installed? If not, install that library from haxelib. That one is designed to work with `haxeui-core` and `openfl`.

**Comment by Helgiii** [comment]
from windows command line i called these:
haxelib git haxeui-core https://github.com/haxeui/haxeui-core
haxelib git haxeui-openfl https://github.com/haxeui/haxeui-openfl
they were donwloaded fine, and i can see those folders in haxetoolkit/haxe/lib

then in project.xml i have
	
	<source path="src" />
	<haxelib name="openfl" />
	<haxelib name="actuate" />
	<haxelib name="hscript"/>
    <haxelib name="haxeui-core" />
    <haxelib name="haxeui-openfl" />

**Comment by Helgiii** [comment]
yep its all right now, sorry for bothering ;)
I ran "haxelib update" in win command line and it updated openfl
