### ISSUE TITLE
findComponent function should have recursive default to true

### ISSUE THREAD

**Issue by tienery** [haxeui/haxeui-core#16]
I personally think that the `findComponent` function in `Component`, [here](https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/core/Component.hx#L554), should have its `recursive` parameter set to `true` by default, because I think that is generally implied when you are looking for an object within the Component you're currently searching.

Otherwise you end up in a situation where you end up with `null` being returned. A lot of people may miss that if they don't know the codebase of HaxeUI that well, and make the presumption that the `findComponent` does what you would otherwise expect.

Or, you could remove the `recursive` function entirely and just make it default behaviour.

**Comment by ianharrigan** [comment]
Im not sure i agree. There are many ways to use this function, one is by using id, either recursively or not. But you can also just go `findComponent(Label)` which will find the first `Label` class but only one level deep. Having it implicitly recursive could cause unwanted effects, ie, "find any child, or children of children that are Labels"

**Comment by tienery** [comment]
Then perhaps if the `critera` is not null, since the default `searchType` is "id", then it would make since to be recursive to find something by id. And if `type` is not null, then recursive can be false unless specified.

When you look at things like the JavaScript DOM, I'm used to using things like `getElementById`, so for me making the recursive true for ID matching would make sense.

**Comment by ianharrigan** [comment]
I think im starting to agree. I think if you specifiy an id, then recursive could be true (unless you specify) anything else would need to be explicit (defaulting to false). I guess that would mean that the `recursive` param would need to change from `recursive:Bool = false` to `recursive:Null<Bool> = null`

**Comment by ianharrigan** [comment]
Can you restest / review that and close if it works as expected? 

Cheers,
Ian

**Comment by tienery** [comment]
I just got a new computer, so I will test as soon as I get the chance and let you know. Otherwise, if it does work, I'll just close this issue.
