### ISSUE TITLE
Need help with themes

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#160]
Hi, I have a little troubles with styling. My own css don't applies :(

defstyle.css:
```
.btn1 {
	width: 100;
	height: 50;
	fontSize: 12;
	color: 0x101101;
}

.lbl1 {
	fontSize: 24;
	color: 0x888888;
}
```
UI.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<vbox>
	<button id="btn1" text="click me!" />
	<text id="lbl1" text="---" />
</vbox>
```
module.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<module>
	<resources>
		<resource path="Assets/Res/css" prefix="res/css" />
	</resources>
	<themes>
		<default>
			<style resource="res/css/defstyle.css" />
		</default>
	</themes>
</module>
```
[css sample OpenFL.zip](https://github.com/haxeui/haxeui-core/files/1313589/sample.zip)

What I'm doing wrong?
Thanks.

**Comment by ibilon** [comment]
You refer to your components by their id, you need to use `#` in the css not `.`,
so `#btn1 {` and `#lbl1 {`.

**Comment by ianharrigan** [comment]
Alternatively you could use:

`<button styleName="btn1" />`

(note you can use `styleName` or `styleNames`)

**Comment by r3d9u11** [comment]
@ibilon my bad, thanks!

But I have second one question: how I can use custom fonts?

module.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<module>
	<resources>
		<resource path="Assets/Res/css" prefix="res/css" />
		<resource path="Assets/Res/font" prefix="res/font" />
	</resources>
	<themes>
		<default>
			<style resource="res/css/defstyle.css" />
		</default>
	</themes>
</module>
```
defstyle.css:
```
@font-face {
	font-family: myFont;
	src: url(res/font/Arial.ttf);
}

#btn1 {
	width: 100;
	height: 50;
	color:  #DC143C;
	font-size: 24px;
	font-family: myFont;
}

#lbl1 {
	color:  #DC143C;
	font-size: 24px;
	font-family: myFont;
}
```

will throw exception:
```
Called from haxe/ui/styles/Engine.hx line 98
Called from haxe/ui/styles/Parser.hx line 1199
Called from haxe/ui/styles/Parser.hx line 1127
Called from haxe/ui/styles/Parser.hx line 1568
Uncaught exception - Invalid char @
```

**Comment by ianharrigan** [comment]
Its not w3c css... try:

```css
#something {
    font-name: "...";
}
```

As for the name, for the openfl backend it will be as you would use it in openfl (i believe)... So i think "Arial"... You may also need to update your application.xml...

I havent looked at fonts in a while, so might need to refresh my memory

**Comment by r3d9u11** [comment]
@ianharrigan I've added line `<assets path="Assets/Res/font" rename="res/font" />` to my project.xml and change my css to:
```
#btn1 {
	width: 100;
	height: 50;
	color:  #DC143C;
	font-size: 24px;
	font-name: "res/font/Arial.ttf";
}

#lbl1 {
	color:  #DC143C;
	font-size: 24px;
	font-name: "res/font/Pacifico.ttf";
}
```
and it works!

Do I need to make changes in project.xml when working with other types of resources (pictures, multimedia) or enough module.xml (as noted [here](https://github.com/haxeui/haxeui-guides/blob/master/modules.md#resources))?

**Comment by ianharrigan** [comment]
module _should_ be enough, infact, looking at the font loading from haxeui-openfl (https://github.com/haxeui/haxeui-openfl/blob/master/haxe/ui/backend/AssetsBase.hx) its not complete. Really that should be much like the images, then you could use either (as you can with images)

**Comment by r3d9u11** [comment]
@ianharrigan many thanks for help!

**Comment by r3d9u11** [comment]
@ianharrigan one more question with themes :)

I can't find, how to append non-default theme? and does it possible to change themes at runtime?
for example I have:

module.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<module>
	<resources>
		<resource path="Assets/Res/css" prefix="res/css" />
	</resources>
	<themes>
		<dark>
			<style resource="res/css/dark/button.css" />
			<style resource="res/css/dark/label.css" />
			<style resource="res/css/dark/vbox.css" />
		</dark>
		<default>
			<style resource="res/css/default/style.css" />
		</default>
	</themes>
</module>
```
and UI.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<vbox theme="dark" styleName="vbox">
	<text id="titleLabel" text="My title" theme="dark" />
	<text text="My label text 1" theme="dark" />
	<text text="My label text 2" theme="dark" styleName="sized" />
	<text text="My label text 3" theme="dark" styleName="colorized" />
	<text text="My label text 4" theme="dark" styleNames="sized colorized" />
	<button id="submitButton" text="Change theme!" theme="dark" />
</vbox>
```
but I had exception as result:
```
...
haxelib_repo/haxeui-core/git/haxe/ui/macros/ComponentMacros.hx:190: characters 28-56 : haxe.ui.components.Label has no field theme
Source/Main.hx:10: characters 21-72 : Called from macro here
...
```

**Comment by ianharrigan** [comment]
Its currently not possible to change themes at runtime... well, at least i havent tried... ;)

It may work, but somethings might not (not 100% sure). 

There is no component attribute "theme", though it might be an interesting idea. Currently there is only ever one "theme" active. So if you change theme, then thats it, all the css is applied. 

To use a different theme, use: `Toolkit.theme = "dark"`

**Comment by r3d9u11** [comment]
@ianharrigan property "theme" I've found in [sample](https://github.com/ianharrigan/haxeui-showcase/blob/master/src/haxe/ui/showcase/util/Prefs.hx#L13) for haxeui v1 :)
Thanks for hint, I'll make some experiments with it.

**Comment by r3d9u11** [comment]
@ianharrigan I tried 
```

import haxe.ui.Toolkit;
import haxe.ui.core.Screen;
import haxe.ui.core.Component;
import haxe.ui.macros.ComponentMacros;

class Main {
	public static function main() {
		Toolkit.theme = "dark";
		Toolkit.init();
		
		var ui:Component = ComponentMacros.buildComponent("Assets/Xml/UI.xml");
		Screen.instance.addComponent(ui);
	}
}
```
and as result I see a blank screen.
But if rename folder css/dark to css/default and change `Toolkit.theme = "dark";` to `Toolkit.theme = "default";` it will works fine.

I'm doing something wrong or it's defect of the library?

**Comment by ianharrigan** [comment]
What does your dark theme hold?

it might also make sense to make your dark theme extend from default. There are other (non visual bits) in default based around auto sizing, etc. In `module.xml´:

```
<themes>
    <dark parent="default" />
</themes>
```

**Comment by r3d9u11** [comment]
@ianharrigan example works fine, Thanks!
```
<themes>
	<dark parent="default">
		<style resource="res/css/default/style.css" />
	</dark>
	<default>
		<style resource="res/css/default/style.css" />
	</default>
</themes>
```

**Comment by r3d9u11** [comment]
@ianharrigan in this [example](https://github.com/r3d9u11/haxe-basics/tree/master/4_ExtLib/4.4_GuiFrameworks/4.4.2_HaxeUI/4.4.2.4_Styling/4.4.2.4.4_UsageThemes) it is just a test with black background and white text :) But I'll do some themes for my future projects and I think that dark theme will look something like a:
![123](https://user-images.githubusercontent.com/15020827/30631279-58437fa8-9dec-11e7-9705-3647ccf91482.png)

So, before I have some questions:

1) Native theme: does [this sample](http://haxeui.org/blog/2016/01/31/1454274720000.html) is actual for haxeui v2? And how it works? Are parameters, textures and colors hard coded in the system or dynamically loading from the OS?

2) What is [properties](https://github.com/haxeui/haxeui-guides/blob/master/modules.md#properties)? What the role of this component? In sample of animation it looks like some "redirection" of one field to second field of class.
