### ISSUE TITLE
childComponents is null?

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#163]
## Expected Behavior
The value of the property "childComponents" is null

## Current Behavior
something like a [[Object Label], [object Label], [object Label]]

## Test app / minimal test case
UI.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<vbox id="vbox1">
	<text id="label1" text="Defautl text 1..." />
	<text id="label2" text="Defautl text 2..." />
	<text id="label3" text="Defautl text 3..." />
	<hbox id="hbox1">
		<text id="sublabel3" text="Subtext 1..." />
		<text id="sublabel3" text="Subtext 2..." />
		<text id="sublabel3" text="Subtext 3..." />
	</hbox>
</vbox>
```
Main.hx
```
...
Toolkit.init();
		
		var ui:Component = ComponentMacros.buildComponent("Assets/Xml/UI.xml");
		Screen.instance.addComponent(ui);
		
		var hbox1 = ui.findComponent("hbox1");
		trace(hbox1); // will return [object HBox]
		
		trace('childs of hbox1:');
		
		var hboxChilds = hbox1.childComponents;
		trace(hboxChilds); // will return null
...
```

## Your Environment

* Version used: haxe 3.4.2, haxeui-core from git
* Environment name and version (e.g. Chrome 39, node.js 5.4): OpenFL 6.1.2, Neko 2.1.0
* Operating System and version (desktop or mobile): Linux Mint 18.2 x64

Thanks

**Comment by ianharrigan** [comment]
what id you type it?

```
var hbox1:HBox = ui.findComponent("hbox1");
```

or 

```
var hbox1 = ui.findComponent("hbox1", HBox);
```

Im not sure how to resolve this. :(

**Comment by r3d9u11** [comment]
@ianharrigan yes, both of methods are works fine. Thanks!

But I really don't understand, how it works, because:
```
var box = ui.findComponent("hbox1");
trace(box); // will return [object HBox]
trace(Std.is(box, haxe.ui.containers.HBox)); // will return true
trace(box.childComponents); // will return null
```

**Comment by ianharrigan** [comment]
Agreed, it is strange behaviour and really should be fixed somehow - reopening.
