### ISSUE TITLE
Cant click buttons in item renderer

### ISSUE THREAD

**Issue by Dunkhan** [haxeui/haxeui-core#166]
Ian said that buttons or other components on an itemrenderer will not trigger any events. I tested this and it is possible to add events to the itemRenderer button inside the declaration of the itemRenderer class. 
For example this code works: https://pastebin.com/RmFX7TSc
But that still means there is no clear way to add a useful event because no handles to any external objects are present. Currently I can only find a way to set the text of a component when adding it and 

## Expected Behavior
I would expect to be able to add functional components like buttons to an itemrenderer and be able to set their functionality so that they have a meaningful effect within the program

Ideally it would be good to be able to create composite objects in the datasource that contain multiple values including functions, and have some kind of binding function that could be overridden in the itemrenderer class to interpret these values and insert them into the rendered items. It would also be useful to be able to pass components to the datasource directly and have the itemRenderer render them.

## Current Behavior
Currently it only seems possible to pass strings to an itemrenderer as data, and any other objects will just be converted to a string if passed

## Possible Solution
see expected behaviour

## Steps to Reproduce (for bugs)
1. Create an itemrenderer subclass in code
2. Create a ListView and assign it to use the custom itemRenderer class created in step 1
3. Create a datasource
4. Try to find a way to add buttons to the itemrenderer using the datasource, and have each button do something when clicked

## Context
In this specific case I am trying to allow the user to select from a dynamic list of objects. These objects are displayed as a list of buttons and when the user clicks on the main class needs to be notified that that specific object was selected

## Your Environment
Windows 7
HaxeDevelop
Currently building javascript
Bug was discovered during irc chat with Ian Harrigan

**Comment by ianharrigan** [comment]
This is fixed, you can add an event listener to the list view "ItemEvent.COMPONENT_EVENT" - obviously this is a very old issue and im cleaning the issues up, so im going to close it myself. Feel free to open another issue if its still a problem

Cheers,
Ian
