### ISSUE TITLE
is Dialogs ready to use?

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#168]
Hi. Is [haxeui-dialogs ](https://github.com/haxeui/haxeui-core/tree/master/haxe/ui/containers/dialogs)  ready to use? And how to show a simple dialog window?

I'm tried something like a:
UI.xml
```
<?xml version="1.0" encoding="utf-8"?>
<vbox>
	<script>
		dlg1.dialogOptions = new DialogOptions();
		dlg1.dialogOptions.title = "My dialog 1";
		dlg1.dialogOptions.icon = DialogOptions.ICON_INFO;
		dlg1.dialogOptions.addStandardButton(DialogButton.OK);
		dlg1.dialogOptions.addStandardButton(DialogButton.CANCEL);
		dlg1.top = 50;
		dlg1.left = 50;
		dlg1.width = 200;
		dlg1.height = 100;
	</script>
	<dialog id="dlg1" visible="false" />
	<button text="click me!" onClick="dlg1.show()" />
</vbox>
```
But:
1) for openfl -neko target I have exception `Uncaught exception - load.c(181) : Module not found : -livereload`
2) with openfl -hxcpp I saw:
* empty space of invisible component
![1](https://user-images.githubusercontent.com/15020827/30919656-b74db2fc-a3aa-11e7-9e07-c7b581cd880f.png)
* dialog without title, icon and buttons (and it can't be moved by mouse)
![2](https://user-images.githubusercontent.com/15020827/30919680-cca96b3c-a3aa-11e7-8285-15895e3f4770.png)

I'm on Linux Mint 18.2 x64
haxe 3.4.2
neko 2.1.0
openfl 6.1.2, Lime 5.5.0
hscript 2.1.1
hxcpp 3.4.188
haxeui-core & haxeui-openfl from git (master)

(maybe this issue applies to haxeui-openfl?)
Thanks.

**Comment by ianharrigan** [comment]
Its not really how dialogs are used in haxeui, ill knock up and example when i get a moment (tomorrow-ish)... i the mean time this might shed some light: http://haxeui.org/api/haxe/ui/core/Screen.html

**Comment by ianharrigan** [comment]
Hey - there is an example of how to use dialogs here: https://github.com/haxeui/haxeui-core/issues/181

Let me know if that clears anything up?

**Comment by r3d9u11** [comment]
@ianharrigan ok, I'll play with dialogs in the near future

**Comment by r3d9u11** [comment]
@ianharrigan great! it works for me (tested only for html5 target), I'll do a several samples and add them to haxe-basics repo (and test for other targets). thanks!

**Comment by r3d9u11** [comment]
@ianharrigan how to use callback?
I tried
```
<?xml version="1.0" encoding="utf-8"?>
<vbox>
	<button
		id="openDialog"
		text="Show dialog message"
		onClick="Screen.instance.messageDialog(
			'Do something?',
			'Question dialog',
			{
				icon: DialogOptions.ICON_QUESTION,
				buttons: [
					DialogButton.YES,
					DialogButton.NO,
					DialogButton.CANCEL
				]
			},
			function (callback:DialogButton) trace(callback)
		)" />
</vbox>
```
but after click I have exception in Parser.hx

**Comment by ianharrigan** [comment]
Yeah, thats a lot of code for an inline click handler... I havent really used it woth script but ill try and knock something up a little later... but fyi, you could also do something like this with scripting (which is neater / cleaner) imo:

```xml
<vbox>
	<script>
		function myFunction() {
			trace("myFunction");
		}
	</script>
	<button text="Test" onclick="myFunction()" />
</vbox>
```

My first guess is there are alot of probably invalid chars in that xml attribute (maybe the new lines) and the haxe xml parser is getting confused - ill confirm that later though anyway. 

Cheers,
Ian
