### ISSUE TITLE
font-size doesn't change via css 

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#169]
## Expected Behavior
font-size of label doesn't change via css

## Current Behavior
font-size must be changed to 24px

## Steps to Reproduce (for bugs)
tested only for openfl backend (neko & hxcpp)

## Test app / minimal test case
style.css
```
.style2 {
	font-size: 24px;
}
```
UI.xml
`<text text="My label text 2" styleName="style2" />`

## Your Environment
Haxe 3.4.2
haxeui-openfl & haxeui-core from git (master)
[full project here](https://github.com/r3d9u11/haxe-basics/tree/master/4_ExtLib/4.4_GuiFrameworks/4.4.2_HaxeUI/4.4.2.4_Styling/4.4.2.4.2_StylesCombination)

Thanks.

**Comment by sh-dave** [comment]
Shouldn't `styleName` actually be `styleNames`?

**Comment by MSGhero** [comment]
Both are accepted.

**Comment by r3d9u11** [comment]
Last test with openfl 6.5.3
![1](https://user-images.githubusercontent.com/15020827/34418364-bdadafc4-ec0e-11e7-8b2f-1845c2eefba6.png)
font size wasn't changed :(
tested application: [test.zip](https://github.com/haxeui/haxeui-core/files/1591749/test.zip)

**Comment by intoxopox** [comment]
Any progress on this issue?

**Comment by ianharrigan** [comment]
None as of yet - but i can reproduce - so thats the good news

**Comment by flashultra** [comment]
I have same issue, but I think also  text-decoration: underline and font-style: bold; not works.
This is new-component-method branch. I think it works on master 
( using openfl - html5 and flash target)

**Comment by ianharrigan** [comment]
Ive provided a fix for this in master and a temp fix for this in new-component-method branch

**Comment by ianharrigan** [comment]
Can we retest this and close if it all works?

Cheers,
Ian

**Comment by flashultra** [comment]
For me font-size  and font-style works.
I also test  text-decoration: underline; for label , but this doesn't works.

**Comment by r3d9u11** [comment]
I can't test it soon, sorry. If it works for you, close this issue or I can do it
