### ISSUE TITLE
Validation Branch - Project breaking

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#175]
Sorry for the generic issue.  

project
[ContinioiusTest.zip](https://github.com/haxeui/haxeui-core/files/1364165/ContinioiusTest.zip)

attached project compiles to NME/openfl - windows -MASTER branch
![image](https://user-images.githubusercontent.com/2074385/31302860-1cbdf776-aaba-11e7-97ad-05d38236d6d9.png)
 NME/openfl - flash -MASTER branch
![image](https://user-images.githubusercontent.com/2074385/31302869-3791a232-aaba-11e7-929f-0a475fb69372.png)

Also compiles to HTML5.  They all mostly look ok

Here they are in validation Branch

NME doesnt compile flash (see eror below) and crashes on launch in windows
`C:\sdks\haxe\haxe\lib\haxeui-nme/validation/haxe/ui/backend/TextDisplayBase.hx:61: characters 16-52 : Null<String> should be flash.text.TextFormatAlign
C:\sdks\haxe\haxe\lib\haxeui-nme/validation/haxe/ui/backend/TextDisplayBase.hx:61: characters 16-52 : String should be flash.text.TextFormatAlign
C:\sdks\haxe\haxe\lib\haxeui-nme/validation/haxe/ui/backend/TextDisplayBase.hx:62: characters 16-51 : Null<String> should be flash.text.TextFormatAlign
C:\sdks\haxe\haxe\lib\haxeui-nme/validation/haxe/ui/backend/TextDisplayBase.hx:62: characters 16-51 : String should be flash.text.TextFormatAlign
`

openfl flash and openfl html5 -validation branch look like
![image](https://user-images.githubusercontent.com/2074385/31303029-fdcfdbc0-aabb-11e7-8012-8356c96fb434.png)

openfl windows crashes on launch

straight html5 looks similar to openfl html5

**Comment by aW4KeNiNG** [comment]
The commit https://github.com/haxeui/haxeui-core/commit/783e5113fcca4ea726e643a7eb30b0d27654e51f fixes the problem. 

Test again. Also you don't need the `resizeMe(new UIEvent(UIEvent.RESIZE));` in the new.

**Comment by hoseyjoe** [comment]
That fixes html5 and openfl html5.  

Rmoving 
resizeMe(new UIEvent(UIEvent.RESIZE));
Fixes crash in  nme and openfl .  There are rendering issues, nothing major, but I will make tickets in appropriate repo
