### ISSUE TITLE
Recompiling does not always update XML

### ISSUE THREAD

**Issue by JacobPariseau** [haxeui/haxeui-core#177]
I have a `main.xml` file that contains a `<vbox>` which parents the rest of my UI. When I modify the XML for it, such as adding a button, list item, or style information, it doesn't always come into effect when I rebuild the application (OpenFL targeting HTML5).

I copied some sample code from a different issue on here such that my file became

`main.xml`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox x="10" y="10">
	<listview width="150" height="150">
        <itemrenderer width="100%">
            <hbox width="100%">
                <image id="icon" />
                <checkbox id="value" />
                <label id="text" />
            </hbox>
        </itemrenderer>
        <data>
            <item icon="res/img/tuxIcon.png" value="true" text="Item 1" />
            <item icon="res/img/tuxIcon.png" value="false" text="Item 2" />
            <item icon="res/img/tuxIcon.png" value="true" text="Item 3" />
        </data>
    </listview>
</vbox>
```

and rebuilt the application with `openfl build html5`. None of the list items appeared. Without touching that XML file, I switched to the validation branch with

`haxelib git haxeui-core https://github.com/haxeui/haxeui-core validation`
`haxelib git haxeui-openfl https://github.com/haxeui/haxeui-openfl validation`

and rebuilt the application once those had installed. Now, the list items appeared and worked perfectly. I then deleted them such that my file became

`main.xml`
```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox x="10" y="10">
</vbox>
```

and rebuilt the application. They still appeared on the screen as if I hadn't changed the XML file at all. I have tried hard refreshing to clear my cache and restarting the development server that Haxe uses to deliver my app.

I am definitely saving between tests, and I have opened my XML file in Notepad++ to verify that yes, it is saving successfully and is not a bug with VSCode.

```
haxelib list
actuate: [1.8.7]
ash: [1.0.0]
box2d: [1.2.3]
haxeui-core: [git]
haxeui-openfl: [git]
hscript: [2.1.1]
hxcpp: [3.4.188]
layout: [1.2.1]
lime-samples: [4.0.1]
lime: [5.6.0]
openfl-samples: [6.0.0]
openfl: [6.2.0]
```

**Comment by ianharrigan** [comment]
Hmm, thats quite strange, ive not had any issues about that personally. How are you loading the XML?

**Comment by JacobPariseau** [comment]
`Main.ui = ComponentMacros.buildComponent("assets/ui/main.xml");`

**Comment by ianharrigan** [comment]
Hmm, thats very strange then - do you have a test app where this happens? Is this all backends? All openfl targets?

**Comment by sh-dave** [comment]
To make sure the browser cache is clear, just open the Development Console (CTRL+SHIFT+I), navigate to the ```Network``` tab and check the ```Disable cache``` option. Also when reloading the page you can now see in the ```Size``` column where the files actually come from (say 'front disk cache', 'from memory cache' or if they were downloaded).

**Comment by ianharrigan** [comment]
CTRL+F5 should do the trick too - or use a a non-html5 target and see if the issue persists

**Comment by JacobPariseau** [comment]
I'm not having issues anymore but I'm not sure what changed to fix it. I'll close the issue anyhow. Problems that go away on their own can come back on their own though, and I'll reopen if I find out anymore.
