### ISSUE TITLE
Tabbed Dialog?

### ISSUE THREAD

**Issue by JacobParis** [haxeui/haxeui-core#179]
Is there any way to create a dialog with tabs? I have three different categories of settings and I'd like to have a way to tab between them within a single dialog.

**Comment by ianharrigan** [comment]
There would be a couple of ways, ill knock up a quick demo shortly... any specific backend?

**Comment by ianharrigan** [comment]
There is an example in the linked GH issue (#181) - let me know if that helps!

**Comment by ianharrigan** [comment]
Closing this issue as its marked for retest and not closed. Feel free to open another issue if thats still not working.

Cheers,
Ian
