### ISSUE TITLE
Dialog does not scale on mobile (openfl-html5)

### ISSUE THREAD

**Issue by JacobParis** [haxeui/haxeui-core#181]
I have a dialog that appears fine on desktop, but when I view it through a mobile browser it appears (relatively speaking) twice the size that it needs to be. I seem unable to change the width at all, so scaling it down does not appear to be an option.

I have a live example in this little WIP game of mine at https://www.jacobpariseau.com/miner/
Click the blue screen to start and then click the little house to show the dialog

Latest git validation for core and openfl backend

**Comment by ianharrigan** [comment]
Hi Jacob, thanks for this - I dont suppose you have a minimal code sample i could work with do you? Another thing, are you using the `validation` branches? There are a few things off with that (from a haxeui perspective)

**Comment by ianharrigan** [comment]
i just realised this is related to: https://github.com/haxeui/haxeui-core/issues/179 also (i assume)

**Comment by JacobPariseau** [comment]
https://gist.github.com/JacobPariseau/61c4b3ce4e53a7403b4fe81010a7fb03

The only other HaxeUI related code is in my `main.hx` and it just loads a vbox from an xml and adds it to the screen. I was using this to build the dialog before I realised HaxeUI had dialogs built in.

**Comment by ianharrigan** [comment]
OK, great thanks

**Comment by ianharrigan** [comment]
Ok, so i did the following:

events.xml
```xml
<vbox width="100%" height="400">
    <style>
        #notification-tabs .tabview-content {
            padding: 0px;
        }
    
        #events, #tech {
            border: none;
        }

        .modal-component {
            filter: none; /* openfl seems to underperform with filters */
        }
    </style>
    <tabview id="notification-tabs" width="100%" height="100%">
        <vbox width="100%" height="100%" text="Events" style="padding: 0;" >
            <scrollview id="events" width="100%" height="100%" contentWidth="100%" />
        </vbox>    
        <vbox width="100%" height="100%" text="Tech">
            <scrollview id="tech" width="100%" height="100%" contentWidth="100%" />
        </vbox>    
    </tabview>
</vbox>
```

Main.hx
```haxe
class Main {
    public static function main() {
        var app = new HaxeUIApp();
        app.ready(function() {
            var main:Component = ComponentMacros.buildComponent("assets/ui/main.xml");
            app.addComponent(main);

            main.findComponent("openDialog", Button).onClick = function(e) {
                trace("open");
                
                var options = new DialogOptions();
                
                var dialog = ComponentMacros.buildComponent("assets/ui/events.xml");
                var tabview = dialog.findComponent(TabView);
                var events:ScrollView = dialog.findComponent("events");
                var tech:ScrollView = dialog.findComponent("tech");
                
                // create some events
                for (i in 0...100) {
                    var button = new Button();
                    button.text = 'Event ${i}';
                    button.percentWidth = 100;
                    events.addComponent(button);
                }
                
                
                Screen.instance.showDialog(dialog, options);
            };

            app.start();
        });
    }
}
```

And it all seems to work fine:

![image](https://user-images.githubusercontent.com/3024242/32723647-8ce5cd68-c86e-11e7-845f-f021e29afdd4.png)

Am i missing something?

**Comment by ianharrigan** [comment]
PS: your css rule: `image { width: 32px; height: 32px }` does make a huge amount of sense, it means that EVERY haxeui Image component will be created with those dimentions - which is why the scrollbar and close button on the dialog are strange.

**Comment by ianharrigan** [comment]
oh, i just reread the original issue too... I wonder if `Toolkit.autoScale = false` might help?
