### ISSUE TITLE
TextArea null object reference crash when highlighting text input

### ISSUE THREAD

**Issue by kevansevans** [haxeui/haxeui-core#182]
Tried to highlight some random garbage I typed in to test the wordwrap of TextArea, got a null object reference crash:

`Called from openfl._internal.renderer.opengl.GLRenderer::render openfl/_internal/renderer/opengl/GLRenderer.hx line 212`
`Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 842`
`Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 842`
`Called from openfl.display.DisplayObjectContainer::__renderGL openfl/display/DisplayObjectContainer.hx line 831`
`Called from openfl.display.DisplayObject::__renderGL openfl/display/DisplayObject.hx line 836`
`Called from openfl.display.DisplayObject::__updateCacheBitmap openfl/display/DisplayObject.hx line 1113`
`Called from openfl.display.BitmapData::__draw openfl/display/BitmapData.hx line 1787`
`Called from openfl.display.DisplayObjectContainer::__renderCairo openfl/display/DisplayObjectContainer.hx line 631`
`Called from openfl.text.TextField::__renderCairo openfl/text/TextField.hx line 1302`
`Called from openfl._internal.renderer.cairo.CairoTextField::render openfl/_internal/renderer/cairo/CairoTextField.hx line 349`
`Called from openfl.text.TextField::getCharBoundaries openfl/text/TextField.hx line 191`

How it's being used in my source:

`this.textarea_trackDescription = new TextArea();

		this.textarea_trackDescription.y = 65;

		this.textarea_trackDescription.x = 80;

		this.textarea_trackDescription.width = 300;

		this.textarea_trackDescription.height = 150;

		this.textarea_trackDescription.wrap = true;

		this.addChild(this.textarea_trackDescription);`

**Comment by ianharrigan** [comment]
Looks like it might be openfl related, will test it out though... what was the text you put in there? Can you recreate to a specific char?

**Comment by kevansevans** [comment]
I can't seem to consistently reproduce the bug with any character I type
