### ISSUE TITLE
Need advice

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/haxeui-core#183]
Hi. [Here](https://github.com/r3d9u11/haxe-basics/tree/master/4_ExtLib/4.4_GuiFrameworks/4.4.2_HaxeUI#haxe-basics-haxeui) is updated collection of samples for haxeui v2. Maybe somebody have an some advices or intresting samples/tips and tricks and samples, which I can be included to samples tree? Maybe I've missed some interest features of library?

Thanks.

**Comment by ianharrigan** [comment]
These are super useful. Id like to incorporate them into the website somehow, im sure many people will find them extremely useful!

**Comment by ianharrigan** [comment]
Im currently working on a set of very simple applications, similar to your repo, but more single component based - as well as being useful as a guide of sorts, the secondary use (for me at least) will be to use them as a sort of "checklist" for all the backends - ie, a set of simple examples that should work the same across each backend (something that is actually in dire need for sanity checking).

To that end if you want, once i upload the basic set, i can give you access and you can add to them as you see fit? The only "rule" is that they have to use `HaxeUIApp` (that way it just makes it simple to use all the different backends) 

What do you think?

Cheers,
Ian

**Comment by r3d9u11** [comment]
@ianharrigan ok, I can do at free time (most of my samples also uses HaxeUIApp, excepted backaend-specific samples)

**Comment by ianharrigan** [comment]
sure - it may very will be a little bit of duplicated effort, for sure - but it would be nice to have them in the haxeui repo - and, as i mentioned, it would also serve as a sort of "checklist" for the backends - ie, "this should all work" sort of stuff. eg (for buttons):

![image](https://user-images.githubusercontent.com/3024242/33229738-e0f8012c-d1d4-11e7-85c0-341363618f76.png)
![image](https://user-images.githubusercontent.com/3024242/33229742-ee360dc0-d1d4-11e7-9592-f7f41da52f41.png)


```
<vbox style="padding: 5px;">
    <script>
        function add() {
            var button = new Button();
            button.text = "Button " + container.childComponents.length;
            container.addComponent(button);
        }
        
        function remove() {
            if (container.childComponents.length > 0) {
                container.removeComponent(container.childComponents[container.childComponents.length-1]);
            }
        }
    </script>
    
    <style>
    
    #styled {
        font-size: 24px;
        background-color:#AAFFAA;
        color: green;
        border-color: green;
        border-size: 2px;
        border-radius: 5px;
        filter: drop-shadow(1, 45, #000000, 0.6, 2, 2, 1, 3, false);
    }
    
    #styled:hover {
        background-color:#AAAAFF;
        color: blue;
        border-color: blue;
    }
    
    #styled:down {
        background-color:#FFAAAA;
        color: red;
        border-color: red;
        filter: drop-shadow(1, 45, #000000, 0.6, 2, 2, 1, 3, true);
    }
    
    </style>
    
    <hbox>
        <button text="Basic" onclick="this.text='Clicked'" />
        <button text="Left" icon="haxeui-core/styles/default/haxeui_small.png" />
        <button text="Right" icon="haxeui-core/styles/default/haxeui_small.png" iconPosition="right" />
        <button text="Top" icon="haxeui-core/styles/default/haxeui_small.png" iconPosition="top" />
        <button text="Bottom" icon="haxeui-core/styles/default/haxeui_small.png" iconPosition="bottom" />
    </hbox>
    
    <hbox>
        <button text="Big" style="font-size: 24px;" />
        <button text="Color" style="font-size: 24px;color:red;" />
        <button text="Background" style="font-size: 24px;color:red;background-color:#AAAAFF;border-color:red;" />
        <button id="styled" text="Styled" />
    </hbox>
    
    <hbox>
        <button text="Add" onclick="add()" />
        <button text="Remove" onclick="remove()" />
    </hbox>
    <grid columns="3" id="container">
        
    </grid>
</vbox>
```

**Comment by ianharrigan** [comment]
Im going to close this as im cleaning up issues and not sure its still relevant?

Feel free to open another issue if thats not the case.

Cheers!
Ian
