### ISSUE TITLE
haxeui is unusable if haxelib path contains "bin/"

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#184]
When haxelib path contains "bin/" it causes compilation error for most haxeui projects.

## Expected Behavior
Haxeui doesn't put any restrictions on haxelib repository path (set with haxelib setup).

## Current Behavior
Compilation fails with error similar to
```
 /home/karlis/bin/haxe/lib/haxeui-core/0,0,1/haxe/ui/macros/ComponentMacros.hx:131: WARNING: no class found for component: vbox
 /home/karlis/bin/haxe/lib/haxeui-core/0,0,1/haxe/ui/macros/ComponentMacros.hx:118: characters 24-26 : Unknown identifier : c0
 src/Main.hx:11: characters 33-82 : Called from macro here
 /home/karlis/bin/haxe/lib/haxeui-core/0,0,1/haxe/ui/macros/ComponentMacros.hx:119: characters 24-26 : Unknown identifier : c0
```
This happens due to path blacklist in `MacroHelpers.SKIP_PATTERNS`.

## Possible Solution
Proper fix would involve changing the way modules are listed. Maybe some of the approaches from [jasononeil/compiletime](/jasononeil/compiletime) can be used? As a temporary workaround haxelib can be installed in different path.

It would also be nice if CI tests tried to compile the templates created with haxeui-core create.

## Steps to Reproduce (for bugs)
1. `haxelib setup somepath/bin/haxe/lib`
2. `haxelib install haxeui-html5`
3. `haxelib run haxeui-core create html5`
4. `haxelib run haxeui-core build html5`
5. Observe compilation error

## Context
I came across this problem while trying out haxeui for the first time. Workaround is reasonable, but It took me a few hours debugging haxeui-core as error message was far from the location of problem. 

## Your Environment
* haxe -version 3.4.4
* haxelib config /home/karlis/bin/haxe/lib/
* haxeui-core: [0.0.1]
* haxeui-html5: [0.0.1]

**Comment by ianharrigan** [comment]
Hmmm, ok, this is interesting, i wonder why this is... Ill check it out.

Thanks!

**Comment by ianharrigan** [comment]
Ah, ok, i can see whats happening, i was attempting to skip paths to speed up compilation times: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/macros/MacroHelpers.hx#L11-L17 - will rethink this approach. 

Thanks again - great catch!

**Comment by ianharrigan** [comment]
This should be fixed now... Ive decided to remove the "bin" entry all together... On a little investigation it never "kicked in" anyway... i mean, "bin" (as your application output dir) isnt on the classpath anyway!

**Comment by ianharrigan** [comment]
Can you let me know if that it working when you get a moment?

**Comment by karliss** [comment]
Seems to be working now, thanks.
