### ISSUE TITLE
App using percent width using css vs percent width as property in xml

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#185]
Using width as style doesnt get  app width
`<vbox id="main"  style="padding:10;width:100%;height:100%">`
However assigning it to the properties does
`<vbox id="main" width="100%" height="100%" style="padding:10;">`
For the following xml
`<?xml version="1.0" encoding="utf-8"?>
<vbox id="main" width="100%" height="100%">
    <style source="../css/main.css" />

    <script>
        
    </script>
	<hbox width="100%">
		<button width="156px" height="34px" styleNames="logo" />
		<box width="100%"/>
		<button width="68px" height="34px" styleNames="submit" />
		<button styleNames="submit" />
		<button styleNames="submit" />
	</hbox>
    <textfield text="ASD"></textfield>    
</vbox>`

**Comment by ianharrigan** [comment]
Hmmm, interesting... Good find. I working on a new css engine, so good timing. Will see if it applies to this branch and then check master.

**Comment by hoseyjoe** [comment]
Ask and you shall receive. This isnt the test project I was working on but I thin kit displays the issue.  Use the html5.hxproj
[ContinioiusTest.zip](https://github.com/haxeui/haxeui-core/files/1473075/ContinioiusTest.zip)
image with style on main vbox
![image](https://user-images.githubusercontent.com/2074385/32813820-e71233ce-c960-11e7-93e2-17d801f13424.png)

Image with property
![image](https://user-images.githubusercontent.com/2074385/32813842-113fd548-c961-11e7-96a2-fccd5330c47c.png)
