### ISSUE TITLE
Fix for validation haxeui/core/TextInput.hx crash

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#186]
I was getting weird crashes when compiling to NME targets.  To fix I changed haxeui/core/TextInput.hx  line 35 from 

if ((value.fontName != null && _textStyle == null) || (value.fontName != _textStyle.fontName)) {

to

if (value.fontName != null && (_textStyle == null || value.fontName != _textStyle.fontName)) {

Sorry I did not make pull request

**Comment by ianharrigan** [comment]
Thanks, do you have the conditions of the crash? I mean, was it a test project? Might be indicative of a deeper issue. 

Cheers.

**Comment by hoseyjoe** [comment]
No.  I think it was when I was dynamically adding label or textfields (no
assigned css)

**Comment by JJayet** [comment]
Hi,
I'm new to OpenFL and HaxeUI and I've just tested with the example given in the README (see below).
It gives me the aforementioned error.

```
import haxe.ui.components.Button;
import haxe.ui.containers.VBox;
import haxe.ui.core.Screen;

var main = new VBox();

var button1 = new Button();
button1.text = "Button 1";
main.addComponent(button1);

var button2 = new Button();
button2.text = "Button 2";
main.addComponent(button2);

Screen.instance.addComponent(main);
```
