### ISSUE TITLE
Option boxes do not update visuals of other option boxes when in same group (openFL)

### ISSUE THREAD

**Issue by kevansevans** [haxeui/haxeui-core#187]
If multiple option boxes are set to the same group, selecting any one that isn't selected will not deselect any others within the group. https://imgur.com/a/Op1lp

`		
		package;

		import openfl.display.Sprite;
		import openfl.Lib;

		import haxe.ui.Toolkit;
		import haxe.ui.components.OptionBox;

		class Main extends Sprite 
		{
			var option_a:OptionBox;
			var option_b:OptionBox;
			var option_c:OptionBox;
			var option_d:OptionBox;
			public function new() 
			{
				super();
		
				Toolkit.init();
		
				this.option_a = new OptionBox();
				this.option_a.groupName = "Group_one";
				this.addChild(this.option_a);
		
				this.option_b = new OptionBox();
				this.option_b.groupName = "Group_one";
				this.addChild(this.option_b);
				this.option_b.y = 30;
		
				this.option_c = new OptionBox();
				this.option_c.groupName = "Group_one";
				this.addChild(this.option_c);
				this.option_c.y = 60;
		
				this.option_d = new OptionBox();
				this.option_d.groupName = "Group_one";
				this.addChild(this.option_d);
				this.option_d.y = 90;
			}
		}
`

**Comment by ianharrigan** [comment]
Hi, this should be fixed now - can you retest when you get a moment and close if appropriate? 

Cheers.

**Comment by kevansevans** [comment]
This fixed it, thanks!
