### ISSUE TITLE
Clicking cross in dialog causes a crash

### ISSUE THREAD

**Issue by tienery** [haxeui/haxeui-core#19]
I'm currently testing on the C++ Windows target, but I'm sure it's the same for others. Basically, if you click the cross button in a popup dialog, the application will crash.

```haxe
private static function showBasicDialog(view:Component, onOk:Function = null)
{
	var options = new DialogOptions();
	options.addStandardButton(DialogButton.OK);
	options.addStandardButton(DialogButton.CANCEL);

	Screen.instance.showDialog(view, options, function(b:DialogButton) {
		if (b.id == '${DialogButton.OK}')
		{
			if (onOk != null)
				onOk();
		}
	});
}
```

It might be the case that it really does not matter what code you use, but I have provided my example code above for this instance.

**Comment by ianharrigan** [comment]
Ok, this should also be fixed now, when you get a chance, can you retest and close if working?

Cheers.
