### ISSUE TITLE
addChild odd behaviour

### ISSUE THREAD

**Issue by JJayet** [haxeui/haxeui-core#197]
Hi guys,

So I'm creating a UI using HaxeUI (so far so good).
I'm doing something like this:

```
var buttons = myArray.map(function(v) { return '<button style="background-color:red;" text="$v"/>});
var component = '
                    <?xml version="1.0" encoding="utf-8" ?>
                    <hbox width="80%" height="50%" horizontalAlign="center" verticalAlign="center">${buttons.join("")}</hbox>';

addChild(component);
```

It basically works:
![capture d ecran 2017-12-25 a 15 52 10](https://user-images.githubusercontent.com/6474450/34340832-98de88ba-e98b-11e7-8494-7b1d758a79ca.jpg)

But if I modify the map function to set either a height or a width, it bugs:
Height:
![capture d ecran 2017-12-25 a 15 53 37](https://user-images.githubusercontent.com/6474450/34340850-d9063438-e98b-11e7-9f4b-7953852c3a65.jpg)

Width:
![capture d ecran 2017-12-25 a 15 53 55](https://user-images.githubusercontent.com/6474450/34340851-e2ca7646-e98b-11e7-8378-b62d779fa7c6.jpg)

If I use `Screen.instance.addComponent`, it works:
![capture d ecran 2017-12-25 a 15 56 09](https://user-images.githubusercontent.com/6474450/34340878-2ece35a0-e98c-11e7-9fda-83905fb1be54.jpg)

Any idea ?

I'm testing in HTML5 with Air but the same thing happens without Air.

**Comment by ianharrigan** [comment]
Hi sorry for the (very) late reply... is this still an issue... i dont suppose you could zip up the project / minimal test case could you?

Cheers,
Ian
