### ISSUE TITLE
Allow specifying index during addComponent()

### ISSUE THREAD

**Issue by kevinresol** [haxeui/haxeui-core#202]
## Current Behavior

If I want to add a component at specific index, I need to do it in two calls

```haxe
parent.addComponent(c);
parent.setComponentIndex(c, index);
```

## Possible Solution

1. add a optional `?index:Int` param to `addComponent()`
2. create a separate function `addComponentAt(comp, index)`

**Comment by ianharrigan** [comment]
I think addComponentAt is the nicest solution, this could then delegate to the backend which can either perform those two calls, or, if it can use another function like openfs addChildAt

**Comment by kevinresol** [comment]
It would be nice to also have `removeComponentAt(index)`

**Comment by ianharrigan** [comment]
Agreed.
