### ISSUE TITLE
proper type for the Toolkit.init() parameter

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-core#203]
## Current Behavior
Everytime i see the completion for `Toolkit.init()`, i die a little inside.

## Media
![image](https://user-images.githubusercontent.com/13007175/34848608-abfe6702-f71f-11e7-9ee4-9d9c53e003bf.png)

## Possible Solution
Use the same principle that basically drives all the backend code (e.g. ComponentBase) and implement a proper `ToolkitOptions` type defined in the backends. So if you take the html5 backend as an example it would be defined in haxeui/haxeui-html5

```haxe
typedef ToolkitOptions = {
    container: js.html.Element,
}
```

In kha it would currently be just empty
```haxe
typedef ToolkitOptions = {
}
```

**Comment by ibilon** [comment]
@MSGhero I've left the implementation of this for haxeui-flixel to you ;)

**Comment by ibilon** [comment]
Works now.
