### ISSUE TITLE
button.customStyle.fontName = "some font" throwing

### ISSUE THREAD

**Issue by f-rank** [haxeui/haxeui-core#205]
Was trying to assign a font to a button but keep getting:

"uncaught exception: [lime.utils.Assets] ERROR: There is no FONT asset with an ID of "Vivaldi Italic""

Added:
@:font("Assets/fonts/VIVALDII.TTF") class DefaultFont2 extends Font {}

and:
Font.registerFont(DefaultFont2);

can see the added font when I do:
trace(Font.enumerateFonts(false));

but if I try to use it it throws.

Am on Windows, using haxeui-core 0.0.3 | haxeui-openfl on git, using openfl 7.0.0 | lime 6.0.0
Happens in windows compile and html, tested in latest chrome and firefox.

**Comment by ianharrigan** [comment]
Ok, thanks for this, i dont suppose you could zip up your / a test project could you? Would be easier than me trying to recreate it.

Cheers,
Ian

**Comment by f-rank** [comment]
Sure can.
Just sent to your profile email link through sendspace:
https://www.sendspace.com/file/q7dhcu

thank you,
Franky

**Comment by ianharrigan** [comment]
Thanks.

Seemed to work just fine for me. 

![image](https://user-images.githubusercontent.com/3024242/35068567-b46631d8-fbd7-11e7-9ba1-2d1c0e6dc7ec.png)
![image](https://user-images.githubusercontent.com/3024242/35068570-b78d4220-fbd7-11e7-81db-c7166a56b74f.png)

Are you using latest openfl? What about latest haxeui (git version), but i dont think anything has changed from haxeui's perspective.

**Comment by ianharrigan** [comment]
ah, ok, so the font isnt "right"? and this in console: 

`Assets.hx:240: [Assets] There is no Font asset with an ID of "Vivaldi Italic"`?

**Comment by ianharrigan** [comment]
The problem is something to do with this (openfl):

`trace(Assets.getFont("Vivaldi Italic"));`

**Comment by ianharrigan** [comment]
ok, so im waiting for confirmation to know if haxeui-openfl is doing things wrong, but in the meantime:

`btn_criar.customStyle.fontName = "fonts/VIVALDII.TTF" ; //FAILING`

works.

**Comment by ianharrigan** [comment]
Ok, so i made a small update (git only until next release), so you should be able to use either methods now thanks to some clarification from Josh.

**Comment by f-rank** [comment]
Yes, it isn't able to pick up the vivaldi font. Sorry if that wasn't clear.
