### ISSUE TITLE
Screen's addComponent() should return the passed component

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-core#211]
For consistency with Component's addComponent(), Screen's addComponent() should also return the passed component. Currently it returns nothing.

## Expected Behavior
var myBtn:Button = cast Screen.instance.addComponent(new Button());

## Current Behavior
var myBtn:Button = cast Screen.instance.addComponent(new Button()); // Cannot use Void as value

## Possible Solution
Screen and ScreenBase should have Component as return for addComponent().

**Comment by ianharrigan** [comment]
Good point... as well as `HaxeUIApp::addComponent` - would like to clean up screen soon anyway.

Thanks for the reminder! :)

**Comment by intoxopox** [comment]
Fixed with PR
