### ISSUE TITLE
question:Backend for starling

### ISSUE THREAD

**Issue by varadig** [haxeui/haxeui-core#222]
Any plane to create backend for starling?
there is no ui framework for stage3d on openfl.

**Comment by idanasher** [comment]
I was wondering the exact same question

**Comment by ianharrigan** [comment]
Honestly, i know next to nothing about starling, i can say that it would be 100% possible to add a starling backend, but i cant say how easy it would be - or when / if it would happen. Ill have to play with starling a little i guess. Do you know of any straight forward "hello worlds" to get a feel for it? 

Cheers,
Ian
