### ISSUE TITLE
project doesn't compile, there's an inheritance\naming problem between invalidate func of Displayobject and Component 

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#223]
C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:2113: chars 11-71 : Error: Field invalidate should be declared with 'override' since it is inherited from superclass haxe.ui.backend.ComponentBase
C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:2113: chars 11-71 : Error: Field invalidate overloads parent class with different or incomplete type
C:\HaxeToolkit\haxe\lib\haxeui-core\git\haxe\ui\core\Component.hx:2113: chars 11-71 : Error: Different number of function arguments

I used: haxelib git haxeui-core https://github.com/haxeui/haxeui-core
so in cases like this what should I do? there are no tags or fixed releases so I can't rollback..
thanx

**Comment by ianharrigan** [comment]
Hmmm, is this openfl 8? Thats kinda annoying, i guess we could rename all "invalidate*" functions to "invalidateComponent*" :(

**Comment by Helgiii** [comment]
yep openfl 8.
great!

**Comment by intoxopox** [comment]
See https://github.com/haxeui/haxeui-openfl/issues/24

**Comment by ianharrigan** [comment]
Ok, this should be fixed now. Can you retest and close if thats the case please? 

Cheers,
Ian

**Comment by ianharrigan** [comment]
really??? Did you update everything?

**Comment by Helgiii** [comment]
yep, haxelib update (no git versions used)
and the file haxe.ui.backend.ToolkitOptions is missing
I searched the whole haxe\lib folder with ... search tool

**Comment by ianharrigan** [comment]
can you do a `haxelib list` and paste results here? Its very strange as ToolkitOptions was introduced quite a while ago

**Comment by Helgiii** [comment]
C:\Users\Admin>haxelib list
actuate: [1.8.7]
as3hx: [1.0.6]
box2d: [1.2.3]
flixel: 4.3.0 [4.4.1]
haxeui-core: 0.0.1 0.0.3 [0.0.4]
haxeui-openfl: 0.0.1 [0.0.2]
hscript: 2.1.1 [2.2.0]
hxcpp: [3.4.188]
layout: [1.2.1]
lime-samples: 4.0.1 [6.2.0]
lime: 2.9.1 5.8.2 5.9.1 6.0.1 [6.3.0]
openfl-samples: [6.0.0]
openfl: 3.6.1 6.5.0 6.5.1 6.5.3 7.0.0 [8.0.1]

**Comment by intoxopox** [comment]
I'm not having that issue and new invalidateComponent methods work as expected. So this issue is closed for me. Perhaps it should be noted that I removed all of haxeui-core and haxeui-openfl via haxelib before running install again, so mine was a clean install.

**Comment by Helgiii** [comment]
intoxopox , thanx) 
removed all libs, installed them back
compiles just fine)))
