### ISSUE TITLE
Setting DropDown's selectedIndex should change its list selection

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-core#225]
If you manually (mouse-click, etc) select from dropdown and later change selection thru api's selectedIndex, the previous selection is incorrectly highlighted in the dropdown list. Consequently, you can't reselect that option, because the dropdown's list thinks it's already selected.

## Steps to Reproduce (for bugs)

1. Select item 'Bob' from dropdown via UI (mouseclick, for instance).
2. Change selection via api's selectedIndex to 'Alice'.
3. Note selection is correctly 'Alice', but opening the dropdown reveals previous ui selection of 'Bob' is still highlighted in the dropdown's list.
4. Try selecting 'Bob' from dropdown list. You can't because it's already highlighted.

## Your Environment

This issue was found on OpenFL backend, but I suspect other backends may also have issue.

**Comment by ianharrigan** [comment]
Looking at this i actually feels it doesnt feel right that you cant event select the same item over and over again... I mean, i get that you can just click the main dropdown selector, but feels a little strange that i cant select "Bob" over and over again.

**Comment by ianharrigan** [comment]
For completeness this is the xml to reproduce:

```
    <dropdown id="cb" width="200" text="Bob">
        <data>
            <item value="Bob" />
            <item value="Alice" />
        </data>
    </dropdown>
    
    <button text="Test" onclick="cb.selectedIndex = 1" />
```

**Comment by ianharrigan** [comment]
This should be fixed now. Ive fixed both issues, now you can selected the same list item over and over again, and also, selectedIndex is propagated correctly to the listview. 

Can you retest and close if it works?

Cheers,
Ian

**Comment by intoxopox** [comment]
Works now. Nice job!
