### ISSUE TITLE
 TextField - caret is not visible

### ISSUE THREAD

**Issue by upperxcode** [haxeui/haxeui-core#227]
## Expected Behavior
The TextField should display the caret when selecting allowing the user to know where the typing character will appear

## Current Behavior
When I click on the component it does not appear the caret, I can still type the text normally and everything seems to work as expected, except the caret.

## Possible Solution
Looking at the component in haxeui.org, the behavior is exactly as expected, which leads me to believe that it may be the way I'm using it or even the backed used.

## Steps to Reproduce (for bugs)

1. I'm using TextField on a form, I declare it in .xml like this:
2. `<textfield id="leDescricao" placeholder="Descrição do produto" />`

## Test app / minimal test case
I'm using the following command to compile
`haxelib run nme build Project.nmml`

## Environment

* Version used:
* Operating System Linux (Arch Linux)
* project: https://github.com/upperxcode/haxetest.git

thanks!

**Comment by ianharrigan** [comment]
Im cleaning up issues, ive tested this and it doesnt seem to be an issue so am closing it, feel free to open another if you need to

Thanks,
Ian
