### ISSUE TITLE
 OptionBox never dispatch UIEvent.CHANGE

### ISSUE THREAD

**Issue by nitrobin** [haxeui/haxeui-core#229]
It is not possible to track OptionBox changes in standard way: `<optionbox onchange="handler()"/>`

## Expected Behavior
Everything works like in precompiled version of official sample app.
https://github.com/haxeui/haxeui-examples/tree/master/Buttons/build/html5

## Current Behavior
App does not handle "Icon position" option change (with latest haxeui).
OptionBox never dispatch UIEvent.CHANGE

## Possible Solution
Revert https://github.com/haxeui/haxeui-core/commit/216ea00da7e42d2346ecd46903050388d94ed1d2 https://github.com/haxeui/haxeui-core/commit/f976300c7e3bf78cd780143ffb8c891ff8d23f23

## Steps to Reproduce (for bugs)
1. git clone https://github.com/haxeui/haxeui-examples
2. Compile sample app with latest haxeui-core from git
3. Try to change "Icon position" option
4. Nothing change

## Test app / minimal test case
https://github.com/haxeui/haxeui-examples

**Comment by ianharrigan** [comment]
Im cleaning up issues, ive checked this isnt still an issue, and it isnt, so closing.

Feel free to open another if the problem persists.

Cheers,
Ian
