### ISSUE TITLE
Will there be Calender Components like in the old haxeui?

### ISSUE THREAD

**Issue by Fuzzipede** [haxeui/haxeui-core#230]
Hi there, 
I'm missing the calender functions in the new haxe ui. Is there something planned? Or must I build it by my own?

thanks for the help.

**Comment by intoxopox** [comment]
Great question! I'm happy to help in either case.

**Comment by ianharrigan** [comment]
There is a new calendar component in the new-component-method branch, but this branch is currently under dev. You could, for the time being, extract that and use it in your own project (pretty sure it should work as is on the master branch)

Or, if you prefer, you could use the new-component-method branch until it becomes master.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Can this be closed? (fyi - master is the most up to date version now - no need to use new-component-method anymore)

**Comment by ianharrigan** [comment]
Im going to close this issue since i havent heard anything and its pretty old.

Cheers,
Ian
