### ISSUE TITLE
Question: How to use ScrollViews?

### ISSUE THREAD

**Issue by Fuzzipede** [haxeui/haxeui-core#231]
I try to achieve a scroll view and fill it at runtime with data from da sql database. But it doesn't work and i don't know why.

I build a small component with a scrollview on it and in my haxecode I use addComponent to add the entries. But nothing happens. 

What am i doing wrong? 
I build a small example app where I have a button and a scroll view and everytime the button gets pressed it adds a button to the scroll view. But it still doesnt work. I tested it on neko and html5 with haxe-openfl backend. Can someone help me?  Thanks

[scrollView.zip](https://github.com/haxeui/haxeui-core/files/2254624/scrollView.zip)

**Comment by ianharrigan** [comment]
Is this still an issue for you? One of the main things i can see from you sample is you are using "contentWidth = 100%" and "contentHeight = 100%"... this means the contents of the scrollview will always be 100% (on both directions) so this means it will never actually scroll. Also, you should probably set a width and height for the actual scrollview (width = 100% / height = 100% - or fixed)... eg:

```xml
<vbox width="100%" height="100%">
    <button id="make" text="New" width="100%" />
    <scrollview width="100%" height="100%" id="view" contentWidth="100%">
    </scrollview>    
</vbox>
```

![image](https://user-images.githubusercontent.com/3024242/62655252-dfd8bb80-b961-11e9-8639-08f38bd389f9.png)


... ... incredibly late response... :/

**Comment by ianharrigan** [comment]
Im going to close this issue now since i havent heard anything. Feel free to open another if you need to.

Cheers,
Ian
