### ISSUE TITLE
Textfield has pointer position problems with non-ASCII characters

### ISSUE THREAD

**Issue by algorev** [haxeui/haxeui-core#232]
## Expected Behavior

The cursor in textboxes should view non-ASCII characters as individual characters, and thus be able to move over them by moving by one position.

## Current Behavior

Non-ASCII characters seem to be seen by HaxeUI as a group of characters, with one character corresponding to each byte. This does not cause any problem for the rendering of the characters themselves. However, it causes problems with the position of the pointer. For example, if we enter the character "é" (two bytes), the rightmost position the cursor will be able to go is the position before the final letter. Also, the same arrow key will need to be pressed two times to go over the "é" character as it corresponds to 2 positions in the textbox.

## Possible Solution

I haven't looked into the code, but it would seem that the number of characters in a textbox is deduced from the number of bytes. It should fix the problem to deduce it from the actual number of characters. I am not sure this is the cause, however.

## Steps to Reproduce (for bugs)

1. Make a program containing a textbox.
2. Write inside the textbox a text with non-ASCII characters. (sample: "döner", or if the font permits it, "花鳥風月".)

## Test app / minimal test case

https://gist.github.com/algorev/828e865811d6de9b0872836144a15bff

## Context

It was a test app to get started with HaxeUI.

## Your Environment

* Version used: haxeui-core 0.0.4 and haxeui-openfl 0.0.2
* Environment name and version: Haxe 3.4.7, Haxelib 3.3.0, Neko 2.2.0
* Operating System and version (desktop or mobile): macOS High Sierra 10.13.6
* Link to your project: https://gist.github.com/algorev/828e865811d6de9b0872836144a15bff

**Comment by aW4KeNiNG** [comment]
It is a recurrent problem with OpenFL. Check here:

https://github.com/openfl/openfl/issues/1739

HaxeUI can't do anything to fix that.

**Comment by algorev** [comment]
Ah, ok, thanks for the quick reply!

-------- Original Message --------
