### ISSUE TITLE
HaxeUI bug with TextField?

### ISSUE THREAD

**Issue by DominikGrebien** [haxeui/haxeui-core#233]
## Expected Behavior

The expected behavior is that the generated input in the div  fits and look normal.

## Current Behavior

If the hight of the TextField is set in the css stylesheet with 100px or100% the generatet input in the div of the html does not fit perfectly and this does not look very good to me.

## Steps to Reproduce (for bugs)

1. Open the Test app to see the problem

## Context

 I would like to use the TextField as a normal looking component in my project.

## Your Environment

* Version used: haxeui-core from git:  93accfc662d9c81b264dccc6d47717c88899bda7,
  haxeui-html5 from git: eb959f7bbd0d764722f073acc68a419297f7da61
* Environment name and version: Firefox: version 61.0.2 (64-Bit), Visual Studio Code: version1.26.1
* Operating System and version: Win 10 64-Bit version 1803
* Link to your project: https://drive.google.com/file/d/1AX_Jz5zwAIjbDcep11WKz8WVk9akdWh7/view?usp=sharing

**Comment by ianharrigan** [comment]
Hi, sorry for the delay... can you paste the relevant parts of the project (i assume quite small / simple) here? I cant seem to access that link to the project.

Cheers,
Ian

**Comment by DominikGrebien** [comment]
Hi Ian, no problem. I tested the link and i can access the project to download it. I think it is something with the css that is the problem.

> .txtFieldPix {
    height: 100px;
    width: 50%;
    font-size: 10px;
}
.txtFieldPerc {
    height: 100%;
    width: 50%;
    font-size: 10px;
}

I hope that helps you.

Cheers,
Domi

**Comment by ianharrigan** [comment]
Ok, strange, it worked this time. Yeah, i see the issue you mean. Ill check it out.

**Comment by ianharrigan** [comment]
Ok, this should be fixed now, you'll need latest version of haxeui-core and haxeui-html5 (master branches)

If that all works, can you close this issue when you get a moment?

Cheers,
Ian

**Comment by DominikGrebien** [comment]
Hm it seems that there is a new issue. I have put a text in the TextField in the xml and the font-size a little bit bigger. If the page is now loaded the input in the div is to small and looks like this:

![unclicked](https://user-images.githubusercontent.com/42865973/45685437-a03a9280-bb49-11e8-83d7-85bf38e0d0d2.PNG)

And after you click in the TextField it seems to look normal and looks like this:

![clicked](https://user-images.githubusercontent.com/42865973/45685518-cf510400-bb49-11e8-9101-335a23021783.PNG)

Cheers,
Domi

**Comment by ianharrigan** [comment]
hmmm... whats you css / xml? And also, what browser?

**Comment by ianharrigan** [comment]
Seems to be something to do with the heights being set, either 100% _or_ 100px... strange... im looking into it.

**Comment by ianharrigan** [comment]
Ok, can you retry that? Should be working now.

**Comment by DominikGrebien** [comment]
Yes now it works as it should.
Thank you very much.

Cheers,
Domi
