### ISSUE TITLE
findComponent bug

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#242]
`
<vbox id="main" width="100%" height="100%" style="padding:10px;">
    <style>
        #scroll1 .scrollview-contents {
            width: 100%;
        }

        #scroll2 .scrollview-contents {
            height: 100%;
        }
    </style>
    <hbox width="100%" height="100%">
        <vbox width="70%" height="100%">
            <scrollview id="scroll1" width="100%" height="50%">
                <button text="Button 1" id="button1" width="100%" />
                <button text="Button 2" width="100%" onClick="trace('hello world')"/>
                <button text="Button 3" width="100%" />
                <button text="Button 4" width="100%" />
                <button text="Button 5" width="100%" />
                <button text="Button 6" width="100%" />
                <button text="Button 7" width="100%" />
                <button text="Button 8" width="100%" />
                <button text="Button 9" width="100%" />
                <button text="Button 10" width="100%" />
            </scrollview>
            <tabview  id="tabView" width="100%" height="50%">
                <vbox text="Positive Bullets" id="Positive Bullets" width="100%" height="100%">
                    <button text="very good height and distance" width="100%" toggle="true" />                                  
                </vbox>
                <vbox text="Negative Bullets" id="neg_bullets" width="100%" height="100%">
                </vbox>
            </tabview>
        </vbox>
	<scrollview id="program_elements" width="30%" height="100%" native="true" >
        </scrollview>

        
    </hbox>
</vbox>`

FindComponent cannot find "neg_bullets" when it can find "Positive Bullets". It seems it can only find the first element in a tabview.

**Comment by ianharrigan** [comment]
I think this might fix it: https://github.com/haxeui/haxeui-core/pull/143

**Comment by Shallowmallow** [comment]
I'll finish my project (as I have a work around for this problem) then I'll try it :)

**Comment by ianharrigan** [comment]
I think this is working now. Can this be closed?

**Comment by ianharrigan** [comment]
Im going to close this issue since its quite old and i think its all working.

Feel free to open another should you need to.

Cheers,
Ian
