### ISSUE TITLE
Dispatch Mouse Event don't use hscript interp context

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#243]
## Normal Behavior
With the xml as
```
<optionbox text="Simple" id="desc_simple" groupName="spin_type" onClick='trace("clicked");'/>
```
When you do `component.dispatch(new haxe.ui.core.MouseEvent("click"));` it traces "clicked".

## Problem Behavior
With the xml and hscript separated
```
<script source="tracet.hscript" />
<optionbox text="Simple" onClick='myOwnTrace("clicked");'/>
```
or 
```
<script>
function myOwnTrace(s:String) {
trace(s);
}

</script>
<optionbox text="Simple" onClick='myOwnTrace("clicked");'/>
```

when you do `component.dispatch(new haxe.ui.core.MouseEvent("click"));` 
it doesn't find myOwnTrace even though it is described in the hscript and it works when you click on the component with your mouse

In flash, it will say EUnknownVariable(myOwnTrace) but it will then work.
On linux, it crashes.

**Comment by ianharrigan** [comment]
Ill have to check it out, but just in case is `s:String` valid hscript? (it may be im not sure myself)

is this any better:

```haxe
function myOwnTrace(s) {
trace(s);
}
```

**Comment by Shallowmallow** [comment]
In fact, this code was a simplified version of my own ;)
The original was this kind of code
```
function show_combination_spins() {
    hideBoxes();

this.findAncestor("new_spin_element").findComponent("spin_combination_box").show();

this.findAncestor("new_spin_element").findComponent("spin_other_box").show();

this.findAncestor("new_spin_element").findComponent("change_foot").hide();
}
```
And the funny thing is that it works when you click normally with the mouse.

Le mer. 28 nov. 2018 à 19:54, Ian Harrigan <notifications@github.com> a
écrit :

**Comment by ianharrigan** [comment]
ok, cool - il check it out... i use that type of script pretty often so something is strange. 

Cheers,
Ian

**Comment by ianharrigan** [comment]
Hi, so i tested and it all works fine, however, if i use the original script in your issue:

```haxe
function myOwnTrace(s:String) {
trace(s);
}
``` 

Then i get the error as you specified. If i remove the `:String` then all works fine ,eg:

```haxe
function myOwnTrace(s) {
trace(s);
}
``` 

So the first issue is that, as i thought, the script isnt valid - however, you are saying that even with a fixed script it still errors? Can you paste / zip a full (non)working example?

Cheers,
Ian

**Comment by sh-dave** [comment]
> Ill have to check it out, but just in case is s:String valid hscript? (it may be im not sure myself)

Just FYI, you can use types if you set `parser.allowTypes` to `true` see https://github.com/HaxeFoundation/hscript#advanced-usage

**Comment by ianharrigan** [comment]
Closing this issue and it think its fixed / was a non issue.

Feel free to open another if need be.

Cheers,
Ian
