### ISSUE TITLE
hi, did haxeui-core develop the tooltip class?

### ISSUE THREAD

**Issue by tuanntjvb** [haxeui/haxeui-core#252]

**Comment by ianharrigan** [comment]
Hi, not yet but its on the list as a high priority component as its been asked for a few times

**Comment by tuanntjvb** [comment]
So sad, I want to ask you a question, how to use mouse events, please write me an example of it. Tks sir

**Comment by uvtc** [comment]
Yes, would be excellent to have tooltips in HaxeUI. Being able to hover and see some explanation of what a widget will do or means is one of the things that makes desktop GUI's so useful.

**Comment by sh-dave** [comment]
I'd like to see this implemented as well.

**Comment by ianharrigan** [comment]
Yeah, i need them too :)

I think im going to have a first pass iteration of them this weekend 

Ian

**Comment by ianharrigan** [comment]
![tooltips_4](https://user-images.githubusercontent.com/3024242/101996512-611d2c80-3cd3-11eb-8def-749776706ec6.gif)

(progress so far, first pass, but seems ok, shouldnt be too much longer)

**Comment by ianharrigan** [comment]
This should be available in git version of haxeui now... i want to make a few more (unrelated) updates before i make a haxelib release
