### ISSUE TITLE
Display overrides an element

### ISSUE THREAD

**Issue by tuanntjvb** [haxeui/haxeui-core#256]
How to display tooltip up 1 element before? Please help me!
![image](https://user-images.githubusercontent.com/34291081/50807361-9cb35d00-132c-11e9-8587-0fb1974df91a.png)

**Comment by ianharrigan** [comment]
Can you paste some code? You probably need to use `Screen.instance.addComponent(...)`

**Comment by tuanntjvb** [comment]
Class: Tooltip
![image](https://user-images.githubusercontent.com/34291081/50942510-8091f600-14bb-11e9-9a99-6fc3eff07f01.png)
Class main: 
![image](https://user-images.githubusercontent.com/34291081/50942528-943d5c80-14bb-11e9-9c32-bbd8452a8f9c.png)

[Tooltip.zip](https://github.com/haxeui/haxeui-core/files/2743354/Tooltip.zip)
Hi guy, My code is in this file. Thanks you.

**Comment by ianharrigan** [comment]
So instead of `btn.addComponent(tooltip)` try `Screen.instance.addComponent(tooltip)`... but _after_ the `Screen.instance.addComponent(grid)`

**Comment by tuanntjvb** [comment]
Thank you for answering my question, I tried but it still suffers.
![image](https://user-images.githubusercontent.com/34291081/50959590-e3a07e80-14f5-11e9-91e3-c8dae0ed21db.png)

**Comment by ianharrigan** [comment]
you added the tooltip _after_ the grid?

**Comment by ianharrigan** [comment]
can you paste your code (but in text, not an image)?

**Comment by tuanntjvb** [comment]
Class: Main:
package ;

import haxe.ui.Toolkit;
import nmx.containers.VBox;
import haxe.ui.containers.Box;
import nmx.containers.Grid;
import haxe.ui.core.Screen;
import haxe.ui.core.Component;
import nmx.controls.Button;
import nmx.controls.Tooltip;
import haxe.ui.core.MouseEvent;
import haxe.Timer;

class Main {
    public static function main() {
        Toolkit.init();
		
		//create Grid
		var grid = new VBox();
		grid.setHeight(500);
		grid.setWidth(500);
		grid.setStyle('border', 'solid 2px red');
		
		//Button
		var btn = new Button();
		btn.setText('Btn');
		btn.width = 95;
		btn.marginLeft = 10;
		btn.marginTop = 10;
		grid.addComponent(btn);
		
		//Button
		var btn1 = new Button();
		btn1.setText('Btn1');
		btn1.width = 95;
		btn1.marginLeft = 10;
		btn1.marginTop = 10;
		btn1.setStyle('position', 'static');
		grid.addComponent(btn1);
			
		Screen.instance.addComponent(grid);
		
		var tooltip = new Tooltip(btn.width, btn.height, btn.top, btn.left);
		
		Screen.instance.addComponent(tooltip);
		btn.height = 30;
		
		btn.registerEvent(MouseEvent.MOUSE_OVER, function(e) {
			tooltip.show();
			//btn1.marginTop = 
		});
		btn.registerEvent(MouseEvent.MOUSE_OUT, function(e) {
			tooltip.hide();
		});
		
		Screen.instance.addComponent(grid);
    }
}

Class Tooltip: 

package nmx.controls;

import haxe.ui.containers.Box;
import nmx.controls.Text;

class Tooltip extends Box {
	public var _textT = 'Example text';
	public var _compatStyle: Map<String, String> = new Map<String, String>();
	
	public function new(widthT : Float = 0, heightT : Float = 0, topT : Float = 0, leftT : Float = 0, position : String = '') {
		super();
		this.width = 200;
		this.height = 30;
		//this.setX(widthT * 2 / 3 + leftT);
		this.setY(heightT + topT + 35);
		this.id = '_tooltip';
		var txt = new Text();
		txt.text = _textT;
		txt.setX(5);
		txt.setY(5);
		txt.setStyle('word-break', 'break-all');
		txt.setStyle('color', 'white');
		this.addComponent(txt);
		this.hide();
    }
	
	/**
	 * 
	 * Set text Text Tooltip
	 * @param	p_value
	 * @return	value
	 */
	public function setText(p_value: String) : String {
		this.text = p_value;
		return this.text;
	}
	
	/**
	 * 
	 * Set width x-axis Tooltip
	 * @param	p_value
	 * @return	value
	 */
	public function setX(p_value : Float) : Float {
        this.marginLeft = p_value;
        return this.marginLeft;
    }
	
	/**
	 * 
	 * Set width y-axis Tooltip
	 * @param	p_value
	 * @return	value
	 */
	public function setY(p_value : Float) : Float {
        this.marginTop = p_value;
        return this.marginTop;
    }
	
	/**
	 * 
	 * @param	attribute
	 * @param	value
	 * @return
	 */
    public function setStyle(attribute: String, value: String) {
        this._compatStyle.set(camelToKebab(attribute), value);

        var styles:String = "";
        for (attr in this._compatStyle.keys()) {
            styles += attr + ":" + this._compatStyle[attr] + ";";
        }

        this.styleString = styles;
    }
	/**
	 * 
	 * Validate css style name
	 * @param	str
	 * @return
	 */
	public function camelToKebab(str: String): String {
		var r = ~/([a-z])([A-Z])/g;
		return r.replace(str, '$1-$2').toLowerCase();
	}
}

Sorry sir, my bad.

**Comment by ianharrigan** [comment]
OK, so you are still adding the tooltip _after_ you are adding the grid to the screen, which means it will be behind it.

**Comment by sh-dave** [comment]
Well actually, he's adding `grid` twice.

**Comment by ianharrigan** [comment]
Oh yeah, good catch... I think the html5 backend will reparent it if that happens...

**Comment by tuanntjvb** [comment]
okay! thanks you so much! I try it.
