### ISSUE TITLE
callback:DialogButton example.?

### ISSUE THREAD

**Issue by tranvantruongjvb** [haxeui/haxeui-core#259]
i have a little trouble about dialog. i used Screen.instance.messageDialog("messagediaolog", "titledialog", optionsdialog, callback:DialogButton) . But i don't know about callback:DialogButton, i just use by null for callback. 
Can you show me example different about null for  callback..
Can you help me.? thank you so much....

**Comment by ianharrigan** [comment]
I can knock up an example, but keep in mind that the dialog code has completely changed from `master` to `new-component-method` - in fact the new dialogs in the new branch (which will become master) isnt completely finished yet either.

**Comment by tranvantruongjvb** [comment]
yes. But i need an example exactly about it,,,please... thanks

**Comment by ianharrigan** [comment]
Ok, heres an example based on `master`, again, keep in mind that dialogs in general have been totally reworked in a newer version, and in fact work much nicer now (for example, you dont have to switch on `.text` anymore), but there are not completely finished yet either. 

```haxe
var button = main.findComponent("test", Button);
button.onClick = function(e) {
    var dialogOptions:Dynamic = {
        buttons: [DialogButton.YES, DialogButton.NO, DialogButton.CANCEL],
        icon: DialogOptions.ICON_QUESTION
    }
    Screen.instance.messageDialog("Test Message", "Test Title", dialogOptions, function(button:DialogButton) {
        switch (button.text) {
            case "Yes":
                trace("User clicked Yes!");
            case "No":
                trace("User clicked No!");
            case "Cancel":
                trace("User clicked Cancel!");
        }
    });
}
```

![image](https://user-images.githubusercontent.com/3024242/50892868-d1441900-13ff-11e9-9616-fcc689e703ec.png)

**Comment by ianharrigan** [comment]
Ok, glad it helped. Im going to close this issue now.
