### ISSUE TITLE
Tableview - Item renderer - when adding to a datasource strings that start with numbers get truncated to number

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#26]
When adding to a datasource strings that start with numbers get truncated to number

## Expected Behavior
Whole string should appear

## Current Behavior
Truncated to first numbers

## Test app / minimal test case
[HaxeUITableTest.zip](https://github.com/haxeui/haxeui-core/files/463008/HaxeUITableTest.zip)

Line 33 should add "111crapsa asoasdfoisadfuoshd fshadf siadufasdfo usda fhasuodf ioasduas dhfouasdhfouasdfh iasudfh u" to the table.  Instead all you see is "111"

**Comment by ianharrigan** [comment]
I think this should be fixed now, can you retest?

Cheers,
Ian

**Comment by hoseyjoe** [comment]
awesome. done
