### ISSUE TITLE
Can i use folder menu on branch new-component-method.? Thanks

### ISSUE THREAD

**Issue by tranvantruongjvb** [haxeui/haxeui-core#261]

**Comment by ianharrigan** [comment]
Im not 100% sure i understand what you mean. 

Btw, ive just opened a discourse community: https://community.haxeui.org/ that maybe be a better place for questions. It might also be more useful for questions to be there (and bugs to be here) as other uses might find answers to the same / similar questions.

Cheers,
Ian

PS: you should be able to login there with your github account

**Comment by tranvantruongjvb** [comment]
Sorry for the inconvenience... I sent another message for you on the https://community.haxeui.org/, let's see it

**Comment by ianharrigan** [comment]
Im going to close this now, as it was answered on https://community.haxeui.org/
