### ISSUE TITLE
how can i remove item in dropdown dataSource ? 

### ISSUE THREAD

**Issue by TranThiNgocHa** [haxeui/haxeui-core#263]
i can add item into dataSource but i can't remove item in dataSource this is my source code : 
Main.hx
![image](https://user-images.githubusercontent.com/46014506/51520343-f4d27f00-1e55-11e9-967b-2cffcba6f764.png)
Dropdown.hx : 
![image](https://user-images.githubusercontent.com/46014506/51520364-087de580-1e56-11e9-87c1-cf28759fe2fc.png)
can u help me ian harrigan ?

**Comment by ianharrigan** [comment]
If you wanted to remove by index you would need to do something like "dataSource.remove(dataSource.get(2))"
