### ISSUE TITLE
when i create Radio class extends Optionbox it not result

### ISSUE THREAD

**Issue by tranvantruongjvb** [haxeui/haxeui-core#264]
when i use branch new-component-method and i create Radio class extends OptionBox it not show for me radio button to click.. Can you help me about this problem.?Thanks
![51520403-1fbcd300-1e56-11e9-9bed-b72674fbfc92](https://user-images.githubusercontent.com/34053656/51654368-29ffde00-1fca-11e9-8d9c-c60f467f3633.png)

**Comment by ianharrigan** [comment]
Can you zip up the code please?

**Comment by tranvantruongjvb** [comment]
[Radio.zip](https://github.com/haxeui/haxeui-core/files/2790715/Radio.zip)
i run it by openfl test html5  and including haxeui-core,haxeui-openfl all on branch new-component-method.. thank you

**Comment by ianharrigan** [comment]
Can you restest this with latest haxeui-core (new-component-method) - and if it works, close this issue.

Cheers.

Thanks to @intoxopox for repoducing / tracking down the issue.

**Comment by tranvantruongjvb** [comment]
Thank you..it working... let's close this issue...
