### ISSUE TITLE
i can't edit buttons in dialog2 move to bottom of the dialog

### ISSUE THREAD

**Issue by tranvantruongjvb** [haxeui/haxeui-core#265]
i'm in branch new-component-method. i use dialog2 to write my alert class . but i have a trouble about button when it is not at the bottom of the dialog.. please help me move the button to the bottom of the dialog.. thank you so much
![image](https://user-images.githubusercontent.com/34053656/51723744-e28e5600-208c-11e9-966e-ef92f92b6ba5.png)

**Comment by ianharrigan** [comment]
Ill check this later today... some of the Dialog2 stuff _should_ be working, it may be an openfl issue.

**Comment by ianharrigan** [comment]
This should be fixed now. You no longer need to use new-component-method branch either. Since this is quite old, im going to close it. Feel free to open a new issue if it persists.

Cheers,
Ian
