### ISSUE TITLE
i create MenuEvent. i can't add new item for MenuEvent like this.. let's help me. thanks

### ISSUE THREAD

**Issue by tranvantruongjvb** [haxeui/haxeui-core#266]
![image](https://user-images.githubusercontent.com/34053656/51903944-05539e00-23f0-11e9-8223-1c6a2745fd4f.png)

![image](https://user-images.githubusercontent.com/34053656/51904200-a2163b80-23f0-11e9-9334-3bbea03143a8.png)

**Comment by ianharrigan** [comment]
Im not sure i understand the question.... wouldnt you just use:

```haxe
c,item = this.item
```

?

**Comment by tranvantruongjvb** [comment]
yes.. i want to return about the item (the item is MenuItem, it can be empty ) but it not return item. i tried c.item = this.item but it not working

**Comment by ianharrigan** [comment]
Unfortunately, you've lost me. `item` would need to be assigned (in the pre-cloned MenuEvent) in order for it to work. If im understanding this isnt a haxeui issue (assuming im understanding correctly ofc).

```haxe
class MySomething {
    var bob:String = null;
    public function clone():MySomething {
        var c = new MySomething();
        c.bob = this.bob;
        return c;
    }
}

var e1 = new MySomething();
var e2 = e1.clone(); // .bob is null here
e1.bob = "tim";
var e2 =e1.clone(); // .bob is "tim" now (as a copy of "MySomething")
```

Am i misunderstanding the issue?

**Comment by tranvantruongjvb** [comment]
i trace(e.clone()) to show function clone():MenuEvent to see what have  in Event of the MenuEvent.. and it haven't item

**Comment by ianharrigan** [comment]
You are using your menu event and essentially using a "click" event, so haxeui wont populate things it doesnt know about. You would have to wire that up. If you used this for example: https://github.com/haxeui/haxeui-core/blob/new-component-method/haxe/ui/containers/menus/Menu.hx#L11-L29

Then `menu` and `menuItem` would be populated correctly.

**Comment by ianharrigan** [comment]
Closing this, presuming no longer an issue.
