### ISSUE TITLE
handleSetComponentIndex is not a function

### ISSUE THREAD

**Issue by markknol** [haxeui/haxeui-core#27]
I installed the git version of haxe ui and the flashdevelop templates, then opened a haxe ui nme project and tried to compile that (without doing anything else).

## Expected Behavior

No errors, beautiful UI.

## Current Behavior

Component.hx and Screen.hx gives error in from `setComponentIndex` function about a missing handleSetComponentIndex function.
```
C:\HaxeToolkit\haxe\lib/haxeui-core/git/haxe/ui/core/Screen.hx:64: characters 12-35 : Unknown identifier : handleSetComponentIndex
C:\HaxeToolkit\haxe\lib/haxeui-core/git/haxe/ui/core/Component.hx:603: characters 12-35 : Unknown identifier : handleSetComponentIndex
```

## Possible Solution

Removing the line did work to make it compile and run, however since I don't know anything about the internals this most likely  breaks stuff (?)

## Your Environment

* Version used: git
* Operating System and version (desktop or mobile): Windows

**Comment by ianharrigan** [comment]
Can you pull latest and retest? This should have been fixed.

**Comment by ianharrigan** [comment]
![image](https://cloud.githubusercontent.com/assets/3024242/18469295/f3030eec-79a7-11e6-9072-ff4152c297cf.png)

**Comment by markknol** [comment]
I dont see any changes, not in this repo, also not on my screen. forgot to push?

**Comment by ianharrigan** [comment]
You'll need to pull haxeui-nme also, this change: https://github.com/haxeui/haxeui-nme/commit/28d4ebe46f709b4b87a58a0bdf986e1fb4d9dfc5

**Comment by ianharrigan** [comment]
that working now? Can this be closed?

**Comment by markknol** [comment]
Yep it now works! 
Side question is there documentation of the elements you can use in xml?

**Comment by ianharrigan** [comment]
There is just this: http://haxeui.github.io/haxeui-api/. Its a little out of date now also.

But generally anything in the components or containers package can be used with that class name (all lower case) and any properties that are in the component can just be used directly from xml.

**Comment by markknol** [comment]
Yes, I've seen that. I didnt see `listview` mentioned there

**Comment by ianharrigan** [comment]
Yeah, it is a little out of date... No TableView or DropDown either... will update when i get a spare hour.

**Comment by markknol** [comment]
Great, thanks!

Btw you could consider deploy it automatically using Travis :+1: 
Like [here](https://github.com/HaxeFoundation/hxnodejs) (see dox.hxml and doc-deploy.sh)
