### ISSUE TITLE
ScrollView2 wrong positon of scrollbar ( hide/show )

### ISSUE THREAD

**Issue by flashultra** [haxeui/haxeui-core#270]
When hide ScrollView2 and after that show it again the scrollbar is moved to the left side .
If not hide it , scrollbar is in correct position ( right side )
Here is wrong position ( when use hide() and show() methods on ScrollView2  )
![incorrect image](https://media.giphy.com/media/4NnQQ6btNUNSmmFWXR/giphy.gif)
 Here is correct one ( without use hide()  and  show())
![correctimage](https://media.giphy.com/media/9zW1IUooSliZAchHfi/giphy.gif)

I'm using the latest new-component-model branch with ScrollView2 
with Openfl -> HTML 5 target

**Comment by ianharrigan** [comment]
This should be fixed now - can you retest and close if this works?

Cheers,
Ian

**Comment by flashultra** [comment]
It works. Thank you.
