### ISSUE TITLE
HBox / VBox - not working vertical and horizontal align

### ISSUE THREAD

**Issue by flashultra** [haxeui/haxeui-core#272]
When have in HBox or Vbox  object Button and set my var vbox / hbox to `vbox.verticalAlign = "center"`  or `vbox.horizontalAlign = "center"` nothing change i.e. button is still in position top left.

( using new-component-model , haxeui-openfl and target html5)

**Comment by ianharrigan** [comment]
Do you have an example? 

Cheers,
Ian

**Comment by flashultra** [comment]
Just created simple example:
```haxe
		var hBox : HBox = new HBox();
		hBox.styleString = "border-size: 1px; border-color: #ff0056;padding: 5px;";
		hBox.width = 570;
		hBox.height = 230;
		hBox.horizontalAlign = "center";
		hBox.verticalAlign = "center";
		var title = new Label();
		title.styleString = "font-size:19px;color: #ff0056;font-style: Arial;border: none;";
		title.text = "Title";
		hBox.addComponent(title);
```
 I think title should be at the center or I'm wrong ?

**Comment by ianharrigan** [comment]
Ok, so i havent run the code yet, but i think you assumptions are wrong, the `verticalAlign` should be on the component you want to align, it doesn mean "align the children this way" it means "align me in the parent this way"... consider:

```xml
<hbox height="100">
    <button text="Top" verticalAlign="top" /> <!-- this is the default so not actually needed -->
    <button text="Center" verticalAlign="center" />
    <button text="Bottom" verticalAlign="bottom" />
</hbox>
```

That wouldnt be possible if the hbox was "align everthing to the bottom" (for example)... i suppose this is another problem with a total lack of docs in haxeui :)

Ian

**Comment by flashultra** [comment]
Thank you Ian, I appreciate your help, as always.
