### ISSUE TITLE
[new-component-method] ScrollView - add / remove / add components problem

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-core#276]
When use latest ScrollView ( from new-component-model ) and add components , remove all or some of them and add it again , ScrollView is empty . Is this a bug or need to set some option ?
On the first add everything is ok, but on the second ( after remove ) , scrollview is empty.
I’m using haxeui-openf ( new-component-model ) with target html5

[HaxeUI (1).zip](https://github.com/haxeui/haxeui-core/files/3025262/HaxeUI.1.zip)

**Comment by ianharrigan** [comment]
This should be fixed now (looking at the hide / show issue separately) - can you retest and close if this works?

Cheers,
Ian

**Comment by flashultra** [comment]
It works with ```dispose = true```.
Thank you.
I can't close this issue, because you open it

**Comment by ianharrigan** [comment]
Ah, ok... good point :)

Cheers.
