### ISSUE TITLE
[new-component-method] haxedevelop hangs cpu busy 90-99% openfl,html5

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#277]
not much to say here
haxedevelop does some very heavy work, unusually.
closing all, and reopening doesnt help
and this happens not at once, but after some small time

I reverted haxeui-openfl and haxeui-core to an old commit (before march 2019)
and use them now

**Comment by ianharrigan** [comment]
does this still happen with latest? You'll need to pull haxeui-core (and whatever backend you are working on)

**Comment by Helgiii** [comment]
I just pulled latest haxeui-core, haxeui-openfl  from git and there is a compile time error
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/scripting/ScriptInterp.hx:3: characters 7-18 : Type not found : haxe.ds.Map

If I comment out this and one more imports of haxe.ds.Map
2 other compile errors rise.. 
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/macros/Macros.hx:84: characters 16-38 : Invalid call (1 args instead of 2)
C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/macros/Macros.hx:25: characters 12-35 : Called from

**Comment by ianharrigan** [comment]
.... great... what version of haxe are you on?

**Comment by Helgiii** [comment]
i'm not sure, but in the c:\HaxeToolkit\haxe\changes.txt
top line reads 2018-02-21: 3.4.7

so I assume it is 3.4.7

**Comment by ianharrigan** [comment]
Ive fixed the two "Map" imports.... not sure what the best way to debug 3.4.7 is... im on 4 - might have to use lix

**Comment by Helgiii** [comment]
I switched to 4.0 too, everything seems to work fine)

**Comment by ianharrigan** [comment]
Ok, great... ill still see whats up with 3.4.7 though - feel free to close this if you are happy.
