### ISSUE TITLE
[new-component-method] ScrollView cuts off contents, openfl, html5

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#278]
Here's a sample project to reproduce the bug:
http://oleg-vorontsov.com/tests/haxe/newcompmethod-scroller.zip

the contents of the ScrollView is not fully visible (it is cut) although there is enough space inside it to show the contents

**Comment by Helgiii** [comment]
There is also a bug with scrolling inside scrolling, for example you have a ScrollView and a scrolled page with another scrollview inside it.

**Comment by Helgiii** [comment]
this bug is also fixed by now

**Comment by ianharrigan** [comment]
great!
