### ISSUE TITLE
Component.cloneComponent(); only copis main level components

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#28]
Some data is not copied when copying a component.  2 part issue?
1.  A component needs to be added to a screen instance or the copy will not include styles. I only tested this on html
2. Data tag on a dropdown was not copied (data was in XML).  Value attribute of a textfield (in xml) was not copied

## Expected Behavior
All data to be copied

## Test app / minimal test case
[RC_HAXEUI_test.zip](https://github.com/haxeui/haxeui-core/files/470487/RC_HAXEUI_test.zip)

**Comment by ianharrigan** [comment]
Ok, ill check them out... they are probably just missing the `@:clonable` metadata on the property.  (A macro builds the clone function based on that meta data)

**Comment by ianharrigan** [comment]
Can you retest this if you get a moment and close if fixed.

Cheers,
Ian
