### ISSUE TITLE
[new-component-method] Focus event: Incorrect parameter type

### ISSUE THREAD

**Issue by nixbody** [haxeui/haxeui-core#283]
Please see [https://github.com/haxeui/haxeui-core/blob/new-component-method/haxe/ui/components/TextField.hx#L297](https://github.com/haxeui/haxeui-core/blob/new-component-method/haxe/ui/components/TextField.hx#L297)

I believe that event parameter type in `TextField::onFocusChange(event: MouseEvent)` should be changed to `FocusEvent`. This change solves two other related issues with Flash/AIR target (haxeui/haxeui-openfl#36 and haxeui/haxeui-flixel#11).

**Comment by ianharrigan** [comment]
Ah ha! Thanks!

(Thats been annoying me for a while, how i didnt track it back to there ill never know!)

Cheers!
Ian
