### ISSUE TITLE
[new-component-method] Virtual ListView renders slow, when dataSource is empty on start

### ISSUE THREAD

**Issue by DominikGrebien** [haxeui/haxeui-core#285]
## Expected Behavior
The virtual ListView should render fast at start without adding one item and then replace it with the real data.

## Current Behavior
The current bahavior is that the virtual ListView renders very slow on start, when the dataSource is empty. If one item is added on start and then is replaced with 1000 new items on a click on a button the ListView renders fast (first ListView in example). In the second ListView the 1000 items are added without adding a single item at start. The time to load the second ListView is at the moment about 10 sec. If there are more labels in the itemrenderer the loading time gets more longer.

## Steps to Reproduce (for bugs)
1. Minimal test case in the link below

## Test app / minimal test case
Main.hx is this: 

```
import haxe.ui.HaxeUIApp;
import haxe.ui.core.Component;
import haxe.ui.macros.ComponentMacros;

class Main {
    public static function main() {
        var app = new HaxeUIApp();
        app.ready(function() {
            var main:Component = ComponentMacros.buildComponent("assets/main.xml");
            app.addComponent(main);
            var btn1: haxe.ui.components.Button = main.findComponent("btn1");
            var btn2: haxe.ui.components.Button = main.findComponent("btn2");
            var lv1 = (main.findComponent("lv1"): haxe.ui.containers.ListView);
            var lv2 = (main.findComponent("lv2"): haxe.ui.containers.ListView);
            lv1.dataSource = new haxe.ui.data.ArrayDataSource<{vTest: String}>();
            lv2.dataSource = new haxe.ui.data.ArrayDataSource<{vTest: String}>();
            var isNew = false;
            function addData(count: Int) {
                var ds = lv1.dataSource;
                if (isNew) ds.clear();
                isNew = false;
                for (i in 1...count + 1) ds.add({vTest1: "test " + i});
            }
            function addData2(count: Int) {
                var ds = lv2.dataSource;
                for (i in 1...count + 1) ds.add({vTest2: "test " + i});
            }
            addData(1);
            isNew = true;
            btn1.onClick = function (_) {
                addData(1000);
            }

            btn2.onClick = function(_) {
                addData2(1000);
            }

            app.start();
        });
    }
}
```

Xml is this: 

```
<?xml version="1.0" encoding="utf-8"?>
<vbox width="100%" height="100%">
    <hbox height="5%" />
    <hbox width="70%" height="70%">
        <button id="btn1" text="click me" />
        <listview id="lv1" width="40%" height="100%" virtual="true" >
            <itemrenderer width="100%">
                <hbox width="100%" style="vertical-align:center;">
                    <label width="1%" />
                    <label width="1%" />
                    <label width="1%" />
                    <label width="1%" />
                    <label id="vTest1" width="10%" />
                </hbox>    
            </itemrenderer>
        </listview>

        <button id="btn2" text="click me" />
        <listview id="lv2" width="40%" height="100%" virtual="true" >
            <itemrenderer width="100%">
                <hbox width="100%" style="vertical-align:center;">
                    <label width="1%" />
                    <label width="1%" />
                    <label width="1%" />
                    <label width="1%" />
                    <label id="vTest2" width="10%" />
                </hbox>    
            </itemrenderer>
        </listview>
    </hbox>
</vbox>
```

## Your Environment

* Haxe version: 4.0.0-rc.3+b20434e1a
* HaxeUI version: new-component-method branch from git
* OS: Windows 10 version 1809
* Backend: html5
* Link to your project: https://drive.google.com/file/d/1PngZBKItpfbDoAT8cSkRM_KykGd8W-A5/view?usp=sharing

**Comment by ianharrigan** [comment]
Thanks for this, its a great test case, there are other issues too ive noticed, even when scrolling the 1st virtual list it chokes. Ill defo look into this asap, but thanks again for a great test app :)

Cheers,
Ian

**Comment by ianharrigan** [comment]
Im looking at this now, but if you need to "fix" it for yourself at the moment you can set "itemHeight='25'" on the listview... Im investigating a correct fix now.

**Comment by ianharrigan** [comment]
This should be fixed now... Can you retest and close when you get a moment.

Thanks,
Ian

**Comment by ianharrigan** [comment]
Can this be closed? (fyi - master is the most up to date version now - no need to use new-component-method anymore)

**Comment by DominikGrebien** [comment]
Yes this can be closed. I changed from new-component-method to master and from ListView to TableView. Tanks for your help as always.
Cheers Dominik
