### ISSUE TITLE
running CLI in windows ? 

### ISSUE THREAD

**Issue by SyedAsimAliSE** [haxeui/haxeui-core#287]
Hi,

this is not really a bug or something to the framework but it is about the CLI
which really is giving me hard time running it, basically i just tried everything which i could:

- adding the run.exe / run.n to && file directory in the windows env variables.
- running directly from the path : 

i always get the error when i run it without ```-flash-develop```
```haxe
neko I:\SDKS\HAXE\haxe\lib\haxeui-core\0,0,4\run create html5 --flash-develop
```
```haxe
 ERROR: no backend specified
```
&&
```haxe
neko I:\SDKS\HAXE\haxe\lib\haxeui-core\0,0,4\run create html5 --flash-develop
```
```haxe
std@sys_read_dir
```

i really want to use it as it saves me bunch of clicks for new projects. and is really fast to test something real quick.  

thanks.

**Comment by SyedAsimAliSE** [comment]
to answer my own question :

i figured out i have to run this :

```haxe
neko I:\SDKS\HAXE\haxe\lib\haxeui-core\0,0,4\run.n setup haxeui
```

and it copied the haxeui.exe file into the sdk folder.

**Comment by ianharrigan** [comment]
Hi, sorry, late reply! Yup you got it exactly. Another option would be `haxelib run haxeui-core setup` (from anywhere) and that should achieve the same, after running that command you can just use `haxeui ...`  from anywhere
