### ISSUE TITLE
Add new TextArea component

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#29]
textfileds dont wrap at given size.
## Expected Behavior

If a textfiled is given a particular width then the text should wrap when its width its that
## Current Behavior

Textfiled has 1 line and just continues to right forever
## Possible Solution

Wrap at width. If textfield has height also then put in  scrollbar if height is exceeded (maybe give option)?
## Test app / minimal test case

[RC_HAXEUI_test.zip](https://github.com/haxeui/haxeui-core/files/470490/RC_HAXEUI_test.zip)

Just click in one of the boxes and type.

**Comment by ianharrigan** [comment]
This needs a new component, a `TextArea`, there are a couple of reasons for this, one it means that `TextField` can remain relatively simple, but it also means that native components can use a totally different control.

**Comment by ianharrigan** [comment]
This component should be written, i realise there are some basic issues with it, but i think this log itself could be fulfilled. 

Can you close if you agree? Thanks.
