### ISSUE TITLE
Double-click selectable textfield should select word under

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-core#292]
Double-clicking inside a textfield, textinput, etc. should select any contiguous characters beneath the point clicked. Currently, it does not.

**Comment by MSGhero** [comment]
Which backend? Like I think this would happen by default in OpenFL.

**Comment by intoxopox** [comment]
I know better than to have not specified. Sorry. This definitely happens in OpenFL backend. Was going to test other backends maybe tomorrow.
