### ISSUE TITLE
unreachable code in ItemRenderer 

### ISSUE THREAD

**Issue by AlexHaxe** [haxeui/haxeui-core#295]
While trying to get my TableView demo running I noticed something inside `ItemRenderer.updateValues` that seems odd: 
When v is a TObject it always triggers https://github.com/haxeui/haxeui-core/blob/083e08bd4c21f579f855ba6f5daae448328db75e/haxe/ui/core/ItemRenderer.hx#L89-L91
so it will never reach https://github.com/haxeui/haxeui-core/blob/083e08bd4c21f579f855ba6f5daae448328db75e/haxe/ui/core/ItemRenderer.hx#L96-L112 

[edit]also findComponent https://github.com/haxeui/haxeui-core/blob/083e08bd4c21f579f855ba6f5daae448328db75e/haxe/ui/core/ItemRenderer.hx#L94-L95 appears to be duplicated[/edit]

**Comment by ianharrigan** [comment]
Nice catch... ... ... ... ... copy paste... :/

**Comment by AlexHaxe** [comment]
it works, but https://github.com/haxeui/haxeui-core/blob/ca50c623cf1c4ca0b85bfb1397fb7e1769a88448/haxe/ui/core/ItemRenderer.hx#L93-L94 is still a bit redundant :)

**Comment by ianharrigan** [comment]
Whoops - thought i got that too. 

Should be sorted now.

**Comment by AlexHaxe** [comment]
thanks, it works!
