### ISSUE TITLE
what component should I use to display and image loaded from a url

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#302]
as long as I can see now Image component accepts a resource id only.
whats the way to display a bitmapdata loaded from url, thanx

**Comment by ianharrigan** [comment]
It should work with http:// and file:// also... do you have an example that isnt work? What backend?

**Comment by Helgiii** [comment]
html5 target,
I just tried loading am img from http:// and it works fine (thanks)
but https:// does not

**Comment by ianharrigan** [comment]
ah, ok, good catch.

**Comment by Helgiii** [comment]
i changed the ImageLoader.hx line 14 to
if (StringTools.startsWith(_resource, "http://") || StringTools.startsWith(_resource, "https://")) {
back then, and it fixed the problem :)

**Comment by ianharrigan** [comment]
Sorry, forgot about this, ill make the change now.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Thats commited btw, can you close this if it works for you?

Cheers,
Ian

**Comment by Helgiii** [comment]
cool! closing now)
