### ISSUE TITLE
bug with ScrollView and disabled property

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-core#304]
Here's a test code to reproduce the bug: http://www.oleg-vorontsov.com/tests/haxe/ui/optionbox-and-scrolling.zip

To reproduce the bug, please, do the following:
- uncheck the checkbox, it disables the vbox with optionboxes
- grab and drag the disabled vbox
- set checkbox selected again, vbox get enabled again
- try clicking any of the optionbuttons and we can't

**Comment by Helgiii** [comment]
when we start dragging the scrolledpage's contents we get into
scrolledview
pauseContainerEvents
onContainerEventsStatusChanged
disableInteractivity

so it pauses interactivity of the scrolled contents' while we are dragging,
and some of this contents could be already disabled

with the mouseup the contens regains interactivity recursively
while some of it could be initially .disabled=true
but it gains interactivity

hm) digging further))

**Comment by Helgiii** [comment]
events in the _disabledEvents are lost, that's why controls dont work..
we dragged the disabled contents, dropped it, interactivity is attempted to be turned on for the scrolledpage..
_disabledEvents contains our old handlers, but disabled = true .
registerEvent tries to readd them and since disabled=true tries adding them again to _disabledEvents, there is a check and they are not added since they are already there, then _disabledEvents = null.. and our handlers are lost.

**Comment by Helgiii** [comment]
i remember having)) this kind of problems before somewhere)) the double disabling))
maybe we could use counters m_disabledCnt:Int
or array of pointers like.. m_disabledForTheseGuys
so if length is >0 its disabled, when all are removed we are enabled again
with counters you dont really know who are still on list..

**Comment by ianharrigan** [comment]
This should be fixed now. If its working for you, can you close this issue?

Thanks!

Ian

**Comment by Helgiii** [comment]
retested, thanks for fixing this ;)
