### ISSUE TITLE
Not uniform license

### ISSUE THREAD

**Issue by lublak** [haxeui/haxeui-core#305]
In https://github.com/haxeui/haxeui-core/blob/master/haxelib.json the code is declarated as MIT-License (like the most other haxe libraries), but in https://github.com/haxeui/haxeui-core/blob/master/CONTRIBUTING.md it is declarated as Apache 2.0.
It should be the same.

The same applies to all other (backend) libraries.

**Comment by xet7** [comment]
I'm trying to start creating new MIT-licensed software, so that it would be copyfree software http://copyfree.org . Would it be possible for all HaxeUI related code be MIT license, so that I could use HaxeUI in my software? Or is there some specific reason for Apache license?

**Comment by ianharrigan** [comment]
Howdy,

All haxeui code _is_ MIT licence... i just havent gotten around to updating all the repos - which ill do so asap - but rest assured, its all MIT.

Cheers,
Ian

**Comment by ianharrigan** [comment]
There is a uniform license now in all the repos (MIT) - closing.
