### ISSUE TITLE
Dropwdown selectedItem is delayed

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#311]
After changing `selectedIndex` for `DropDown` `selectedItem` isn't immediately updated.

## Expected Behavior
After changing `selectedIndex` `selectedItem` immediately reports new value.

## Current Behavior
`selectedItem` gets updated after a while I guess it currently needs a pass of callbacks triggering to get updated.

## Steps to Reproduce (for bugs)

1. Build the testApp for HTML5
2. Click on button B1 observe following output, `dd.selectedItem` doesn't match`dd.dataSource.get(dd.selectedIndex)`
```
src/Main.hx:28: Change and print 1 {value : v0, v2 : 0} {value : v1,  v2 : 1 }
```
3. Click on B2, observe that after given time to run callbacks or whatever is happening `selectedItem` returns correct value
```
src/Main.hx:31: Print 1 {value : v1, v2 : 1} {value : v1,  v2 : 1}
```

## Test app / minimal test case
```haxe
package;

import haxe.ui.data.ArrayDataSource;
import haxe.ui.HaxeUIApp;
import haxe.ui.components.Button;
import haxe.ui.components.DropDown;
import haxe.ui.containers.HBox;

class Main {
	public static function main() {
		var app = new HaxeUIApp();
		app.ready(function() {
			var main = new HBox();
			app.addComponent(main);
			var dropDown = new DropDown();
			var ds = dropDown.dataSource = new ArrayDataSource();
			ds.add({value: "v0", v2: 0});
			ds.add({value: "v1", v2: 1});
			ds.add({value: "v2", v2: 2});

			var button1 = new Button();
			button1.text = "B1";
			var button2 = new Button();
			button2.text = "B2";

			button1.onClick = function(_) {
				dropDown.selectedIndex = (dropDown.selectedIndex + 1) % 3;
				trace('Change and print ${dropDown.selectedIndex} ${dropDown.selectedItem} ${dropDown.dataSource.get(dropDown.selectedIndex)}');
			};
			button2.onClick = function(_) {
				trace('Print ${dropDown.selectedIndex} ${dropDown.selectedItem} ${dropDown.dataSource.get(dropDown.selectedIndex)}');
			};

			main.addComponent(dropDown);
			main.addComponent(button1);
			main.addComponent(button2);
			app.start();
		});
	}
}

```

## Your Environment

* Version used: haxeui-core: [1.0.5], haxeui-html5: [1.0.1]
* Environment name and version: 70.0.1 
* Operating System and version (desktop or mobile): ArchLinux

**Comment by ianharrigan** [comment]
Nice find.. can you try that again on the latest haxelib (1.0.6) of haxeui-core. Should be fixed there.

If it is, can you close this issue?

Thanks very much!

Cheers,
Ian

**Comment by karliss** [comment]
Thanks, was able to remove workaround from my code. Test case also works.
