### ISSUE TITLE
Support code before super call in constructor

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#312]
Current macro code generating code inside constructor makes an assumption that `super()` call will be instruction will be the first expression inside constructor.

## Expected Behavior
Generated code gets inserted after `super()` call

## Current Behavior
Generated code gets inserted after first instruction.

## Possible Solution
Supporting conditional or multiple `super()` calls is probably difficult. Allowing only one super() call as top level expression inside constructor is probably sufficient for most cases.

## Steps to Reproduce (for bugs)

If necessary will create detailed steps in a few days.
1.
2.
3.
4.

## Test app / minimal test case
See Steps for reproduce.

## Context

I came across this when I tried to enable nullSafety checks for my code. There were a bunch of errors about calling methods before all fields are initialized coming from macro. Correctly inserting generated code after `super()` would allow initializing them before generated code gets executed. That doesn't necessarily solve all the problems with null checks but it would be good first step.
If i am not mistaken there was also a runtime error when the code was generated before super call as some of it expected `component` to be initialized.

## Your Environment

* Version used: 1.0.6

**Comment by ianharrigan** [comment]
Hmmm... i how about something like:

The generated code gets put into an "initializeCustomComponent" (or similar) function. That function, by default, gets called after super() (as is the case now), however, there could be a check maybe to see if it already has an "initializeCustomComponent" in the constructor and if it does, do nothing except build that init function.

That i think should help, right?

Cheers,
Ian
