### ISSUE TITLE
Moving a node to a new parent is broken

### ISSUE THREAD

**Issue by XANOZOID** [haxeui/haxeui-core#314]
## Expected Behavior
Transferring a child component from one parent component to another should work correctly.

## Current Behavior
Moving a child component, from component A, into Component B will not add it correctly. 

IE: It gets removed from A and it is "technically" in B, but it does not render correctly and there's a lot of things wrong with it.

## Steps to Reproduce (for bugs)
1. Create an xml with two components.
2. Component A should be filled with 1 or more components.
3. Move any component from A to B (removing it from A before B, or not)
4. It never gets moved over.

## Media
![image](https://user-images.githubusercontent.com/29788070/69212926-da257100-0b1f-11ea-88e3-fe22a107376f.png)
![image](https://user-images.githubusercontent.com/29788070/69212888-c417b080-0b1f-11ea-8f81-e85537731ed7.png)

## Test app / minimal test case
[moving_component_bug.zip](https://github.com/haxeui/haxeui-core/files/3867560/moving_component_bug.zip)

```xml
<vbox id="main" width="100%">
    <vbox id="l1">
        <label id="a" text="BLOCK A"/>
        <label id="b" text="BLOCK B"/>
    </vbox>

    <vbox id="l2">
        <label text="list 2" />
    </vbox>
</vbox>
```
```haxe
var main:Component = ComponentMacros.buildComponent("assets/main.xml");
app.addComponent(main);
app.start();
var com:Component = main.findComponent("a", true);
var l2:Component = main.findComponent("l2", true);

if (com != null) com.parentComponent.removeComponent(cast com);
l2.addComponent(com);
```

## Context
Was working on a quick drag and drop and when attempting to move a component from list 1 to list 2 it did not populate correctly.

## Your Environment
* Version used: haxeui-core 1.0.7
* Environment name and version: OpenFL neko export
* Operating System and version (desktop or mobile): Ubuntu linux

## Note:
For some reason right before I was about to send you the zip it was working . . . but I didn't change my code. So this might be a random bug, or I'm just tired.

**Comment by ianharrigan** [comment]
Ive run your app you a few times and keep just getting this:

![image](https://user-images.githubusercontent.com/3024242/69214681-e1706d00-0b67-11ea-8009-d97b7aad9758.png)

Ie, it seems to work, can you make it _not_ work? What conditions?

Cheers,
Ian

**Comment by XANOZOID** [comment]
I think this might not be an issue, I'll re-open this if I come across it actually breaking again.
