### ISSUE TITLE
View jumps to wrong location in ScrollView*

### ISSUE THREAD

**Issue by XANOZOID** [haxeui/haxeui-core#315]
## Expected Behavior
Focus should jump to the correct position.

## Current Behavior
When a textfield component is "focused" inside of a VBox, that's in a scroll view, it will jump way way higher than the clicked textfield.

## Possible Solution
.... look into focusmanager or the focus event on a textfield. . . I tried tracing up the focus event but apparently it's a backend thing; so I stopped.

## Steps to Reproduce (for bugs)
```xml
<scrollview contentWidth="100%" width="100%" height="200px">
     <vbox width="100%">
           <spacer height="100px" />
           <textfield text="text 1" />
           <spacer height="100px" />
           <spacer height="100px" />
           <textfield text="text 2" />
           <spacer height="100px" />
     </vbox>
</scrollview>
```

## Media
- todo

## Test app / minimal test case
Todo later?

## Your Environment
* Version used: OpenFL (neko/linux) 1.0.7
* Environment name and version: OpenFL
* Operating System and version (desktop or mobile): Ubuntu

# Note 
~~I tried the sample on the playground - looks like it worked there.~~ Nevermind, it's broken on html5 too.

**Comment by ianharrigan** [comment]
This should be fixed now, can you retry when you get a moment, and if it is, close this issue?

Thanks!

Ian
