### ISSUE TITLE
Adding components to scrollview causes shift !BREAKING!

### ISSUE THREAD

**Issue by XANOZOID** [haxeui/haxeui-core#316]
## Expected Behavior
Adding to the scrollview should not cause the entire scrollview itself to start shifting upwards out of whatever html-element it's inside of. 

It should just continue to add elements to the view, like on OpenFL, and let us scroll through it later on.

## Current Behavior
It currently moves the entire view on HTML5, and completely breaks the layout until you move the cursor back onto it and it somehow fixes itself.

## Steps to Reproduce (for bugs)
1. Create a vbox (expand to fit screen)
2. Put a scroll view in a vbox (expand to fit vbox)
3. Make a keyboard event listener for adding components
4. On event, add component to the scroll view and it'll eventually break

### Working on OpenFL Neko
![haxeui-no-offset-correct](https://user-images.githubusercontent.com/29788070/69223094-eae1e100-0b37-11ea-9d17-15a0dc62406c.gif)

### Broken for HTML5
![haxeui-offsethtml5](https://user-images.githubusercontent.com/29788070/69222836-7f980f00-0b37-11ea-9584-47c8685126b8.gif)

## Test app / minimal test case
... to do ... (probably send over discord)

## Context
This broke the entire view! I'm just trying to add elements into a scroll view dynamically to use it like a list.

## Your Environment
* Version used: 1.0.1 - 1.0.7 HTML4
* Environment name and version: Chrome Latest
* Operating System and version (desktop or mobile): Desktop

**Comment by ianharrigan** [comment]
Heres a super minimal case that reproduces this issue:

```xml
<vbox style="padding: 5px;">
    <scrollview width="250" height="200">
        <vbox id="container">
            <vbox id="itemContainer">
                
            </vbox>
            <textfield id="itemText" />
        </vbox>
    </scrollview>
</vbox>
```

```haxe
@:build(haxe.ui.macros.ComponentMacros.build("assets/main.xml"))
class MainView extends Box {
    public function new() {
        super();
        addItem();
    }
    
    private function addItem() {
        var hbox = new HBox();
        var textfield = new TextField();
        var button = new Button();
        button.text = "+";
        hbox.addComponent(textfield);
        hbox.addComponent(button);
        itemContainer.addComponent(hbox);
    }
    
    @:bind(itemText, KeyboardEvent.KEY_DOWN)
    function onKeyDown(e) {
        if (e.keyCode == 13) {
            trace("add new");
            addItem();
        }
    }
}
```

if you just keep pressing [enter] then its all fine... if however, you actually type in the bottom textfield then things get _weird_ - such strange behavior!

**Comment by ianharrigan** [comment]
Interestingly, this might be some type of chrome issue. Seems to work find on FF and edge :/

**Comment by ianharrigan** [comment]
So, its something to with the field not being in view when you type in it, and only happens in chrome... Really the field should be in view automatically anyway when you start typing, but i think you opened another issue relating to this, in the mean time, this is a workaround:

In the "addItem" function above in my example, add the following to the end:

```haxe
        Toolkit.callLater(function() {
            scrollview.vscrollPos = scrollview.vscrollMax;
        });
```

This keeps the textfield in view so chrome doesnt choke. Ill look at getting the "ensureVisible" to work correct (which it should really, and this is "accidentally" get around this isssue on chrome)

**Comment by ianharrigan** [comment]
Fixing this issue should fix this one too: https://github.com/haxeui/haxeui-core/issues/315

**Comment by ianharrigan** [comment]
This should be fixed now... was a pretty interesting one (https://github.com/haxeui/haxeui-html5/commit/d15ea697bab10bc58b24d6a6a17db1abb9f0914e). Can you retest and if working, close this issue?

Cheers,
Ian
