### ISSUE TITLE
Custom Component property not validated thru XML in HTML5

### ISSUE THREAD

**Issue by XANOZOID** [haxeui/haxeui-core#317]
## Expected Behavior
If I have a custom component, using the build macro with a Haxe class, and it has properties that I would like to use between xml and other, it should work consistently between targets.

## Current Behavior
A custom component has a property that is binded to the visibility of a component inside of its xml. When the property of the Custom Component is assigned thru xml, it does not do it correctly. It appears to work on hxcpp/neko targets for OpenFL.

## Steps to Reproduce (for bugs)
1. Create an xml component with a child that you want to toggle
```xml
<vbox>
     <label id="toggle" text="hello world" />
</vbox>
```

2. Create a custom component that inherits it and binds to child visiblity
```haxe
@:build(haxe.ui.macros.ComponentMacros.build("toggle-text.xml"))
final class ToggleText extends VBox {
    // PROPS    
    @:bind(new_task.visible)
    public var adding:Bool = true;
}
```
3. Make sure the modules.xml file reflects this component
4. Use this custom component in xml somewhere else with that property
```xml
<vbox>
      <ToggleText adding="false" />
      <ToggleText />
</vbox>
```

## Media
See ticket #316 , this is where I found out it happened. 
( If you notice in that ticket there's a button in active tasks that allows me to enter a new task.... Well, that shouldn't be visible in this case. )

## Test app / minimal test case
Will send over discord.

## Context
I was just trying to create a declarative custom-component where I could use the flag to toggle its visibility through a controlled property.

## Your Environment
* Version used: haxeui-html5 v1.0.1 
* Environment name and version:Chrome latest
* Operating System and version: Ubuntu stable

**Comment by XANOZOID** [comment]
Turns out this wasn't really an error. Looks like visible was a valid property to change visiblity in the openfl target . . . but that's not a valid property to bind to with HaxeUI specifically. 

What can we do about this? No compile-time error came through, which is a bit baffling to me. 

Also @ianharrigan we have a property for "hidden" but I do think we should have a negated alias for hidden . . . .

Feel free to close this unless you think there's something you can/want to-do about that silent bug.

**Comment by ianharrigan** [comment]
The "issue" is the binding manager uses reflection, this is so you can rebind and runtime, as well as send bound xml docs via a network / fs / etc and they will still "work". One thing that is strange, is i would have expected a runtime error - but i dont seem to get one.

**Comment by ianharrigan** [comment]
OK, you should get runtime warnings now. Lemme know if you think this issue can be closed, and if so, can you close it?

Cheers,
Ian
