### ISSUE TITLE
ComponentMacros.build doesn't assign ids to components

### ISSUE THREAD

**Issue by Gulvan0** [haxeui/haxeui-core#318]
I try to create a simple menu component from XML, but my components cannot be found when I try to access it from my class.

TreeContextMenu.hx:
```
@:build(haxe.ui.macros.ComponentMacros.build("graphic/components/abilityscreen/TreeContextMenu.xml"))
class TreeContextMenu extends Menu
{
    public function new ()
    {
        super();
        trace(learn);
        trace(findComponent("learn"));
    }
}
```

TreeContextMenu.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<menu>
    <menuitem id="learn" text="Learn" />
    <menuitem id="pattern" text="Edit Patterns" />
</menu>
```
## Expected Behavior
Both traces should print corresponding MenuItem

## Current Behavior
Both traces print null

## Context
I investigated the issue using the debugger and found out that the _id field of all the components equal null

## Your Environment
* Version used: 1.0.8
* Environment name and version (e.g. Chrome 39, node.js 5.4): hxcpp Windows 10
* Operating System and version (desktop or mobile): Windows 10

**Comment by ianharrigan** [comment]
The issue with trying to get ids from the menu component via macros (ie, build macro) is that the menu items dont exist until runtime. Can i ask what you are trying to do with your menu component? Ie, how you are trying to use it?

Cheers,
Ian

**Comment by Gulvan0** [comment]
> The issue with trying to get ids from the menu component via macros (ie, build macro) is that the menu items dont exist until runtime. Can i ask what you are trying to do with your menu component? Ie, how you are trying to use it?
> 
> Cheers,
> Ian

I'm just trying to create and add the component to the stage:
```
var m = new TreeContextMenu();
m.init(2, 3, new SAbility());
add(m, 20, 20);
```
The component also init method that throws an exception (because learn == null) and this exception was the initial problem, after whichI started to investigate

```
@:build(haxe.ui.macros.ComponentMacros.build("graphic/components/abilityscreen/TreeContextMenu.xml"))
class TreeContextMenu extends Menu
{
    public function new ()
    {
        super();
    }

    public function init(selectedAbI:Int, selectedAbJ:Int, parent:SAbility) 
    {
        learn.onClick = function (e)
		{
			parent.learn(selectedAbI, selectedAbJ);
		}
		pattern.onClick = function (e)
		{
			parent.editPattern(selectedAbI, selectedAbJ);
		}
    }
}
```

**Comment by ianharrigan** [comment]
So im looking at a menu, which i presume is a right click context menu, and actually, its not so easy to make custom components out of them. They are quite specialized components, esp. on native - im looking at it now and hoping to make the whole process a little simpler.

Bear with me. :)

Cheers,
Ian

**Comment by Gulvan0** [comment]
> So im looking at a menu, which i presume is a right click context menu, and actually, its not so easy to make custom components out of them. They are quite specialized components, esp. on native - im looking at it now and hoping to make the whole process a little simpler.
> 
> Bear with me. :)
> 
> Cheers,
> Ian

So what's the easiest way to make the custom right-click context menu for elements on the screen (not haxeui components)? Code it myself?

**Comment by ianharrigan** [comment]
something like this:

```haxe
            main.onRightClick = function(e) {
                var menu = ComponentMacros.buildComponent("assets/mymenu.xml");
                menu.left = e.screenX;
                menu.top = e.screenY;
                menu.registerEvent(MenuEvent.MENU_SELECTED, function(e:MenuEvent) {
                    trace(e.menuItem.text);
                });
                app.addComponent(menu);
            }
```

Is that the sort of thing you mean?

**Comment by Gulvan0** [comment]
> something like this:
> 
> ```hx
>             main.onRightClick = function(e) {
>                 var menu = ComponentMacros.buildComponent("assets/mymenu.xml");
>                 menu.left = e.screenX;
>                 menu.top = e.screenY;
>                 menu.registerEvent(MenuEvent.MENU_SELECTED, function(e:MenuEvent) {
>                     trace(e.menuItem.text);
>                 });
>                 app.addComponent(menu);
>             }
> ```
> 
> Is that the sort of thing you mean?

Seems right, but I can't understand what is _app_ and what is _main_. 😕

**Comment by ianharrigan** [comment]
"main" is just the main view... and app is basically the same as: `Screen.instance.addComponent(menu)`
