### ISSUE TITLE
@build macro issue 1.0.10

### ISSUE THREAD

**Issue by turdparty** [haxeui/haxeui-core#319]
I switched from git to version 1.0.10 and ran into weird compilation errors, pretty much the same as described [here](https://github.com/haxeui/haxeui-core/issues/184)
--edit: my git version was outdated

> Source/Main.hx:20: characters 20-73 : Warning : no class found for component: button
C:/trunk/dev/Haxetoolkit/haxe/lib/haxeui-core/1,0,10/haxe/ui/macros/ComponentMacros.hx:136: characters 26-28 : Unknown identifier : c0
Source/Main.hx:20: characters 20-73 : Called from macro here
C:/trunk/dev/Haxetoolkit/haxe/lib/haxeui-core/1,0,10/haxe/ui/macros/ComponentMacros.hx:137: characters 26-28 : Unknown identifier : c0
Source/Main.hx:20: characters 20-73 : Called from macro here
C:/trunk/dev/Haxetoolkit/haxe/lib/haxeui-core/1,0,10/haxe/ui/macros/helpers/CodeBuilder.hx:11: lines 11-12 : Void should be haxe.ui.core.Component
C:/trunk/dev/Haxetoolkit/haxe/lib/haxeui-core/1,0,10/haxe/ui/macros/helpers/CodeBuilder.hx:11: lines 11-12 : For function argument 'component'
Source/Main.hx:8: lines 8-30 : Defined in this class

It does not seem related to a path issue however. The errors do not occur when I comment out the @build macro. ComponentMacros.buildComponent does not cause compilation issues, but it could be related to [this issue](https://github.com/haxeui/haxeui-core/issues/318)

Code to reproduce the issue:

**Main.hx**
`import haxe.ui.Toolkit;
import haxe.ui.HaxeUIApp;
import haxe.ui.macros.ComponentMacros;

class Main {
	public static function main() {
		Toolkit.init();
		var app = new HaxeUIApp();
		app.ready(function() {
			app.addComponent(ComponentMacros.buildComponent("Assets/Xml/test.xml"));
			app.start();
		});
	}
}

@:build(haxe.ui.macros.ComponentMacros.build("Assets/Xml/test.xml"))//comment this out and it builds fine
class SignatureView extends haxe.ui.core.Component {
	public function new() { super(); }
}`

**test.xml**
`<button text="Ok"/>
`

**project.xml**
`<project>
	<meta title="Test" package="" version="1.0.0" company="" />
	<app main="Main" path="Export" file="Main" />
	<source path="Source" />
	<haxelib name="openfl" />
	<haxelib name="haxeui-core" />
	<haxelib name="haxeui-openfl" />
</project>`

**Comment by ianharrigan** [comment]
Does the git version work? I think there might be an issue with 1.0.10, but not im 100% sure, would be great to confirm that. 

Cheers,
Ian

**Comment by turdparty** [comment]
You're right, that works fine.
Sorry, I'll close the issue then.

**Comment by ianharrigan** [comment]
OK, good to know though... Ill get another release out shortly.

Thanks!

Ian

**Comment by ianharrigan** [comment]
OK, im going to close this now as there is a new release which should have resolved this issue. Let me know if it doesnt!

Cheers,
Ian
