### ISSUE TITLE
validateComponent doesn't update size after Label text change

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-core#320]
Given the following, I would expect the label's width to change, but it doesn't.
```
_label = new Label();
_label.text = "initial size";
addComponent(_label);
registerEvent(MouseEvent.CLICK, function(e) {
	trace(_label.width);
	_label.text = "test me";
	trace(_label.width);
	_label.validateComponent();
	trace(_label.width);
});
```

## Your Environment
Latest haxeui-core and haxeui-openfl.

**Comment by ianharrigan** [comment]
validateNow should work (added as an alias for syncComponentValidation)

**Comment by ianharrigan** [comment]
Can this be closed now? Ie, the validateNow alias...
