### ISSUE TITLE
Actuator returning null

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#322]
The following tween call didnt work (lines 27, 29 in main.hx)

var ani=Actuator.tween(main.tabs, { percentHeight : 50 }, 0.5, ao);

I trace followed its path to line 157 in haxe.ui.styles.animation.util.Actuator.hx where a null is returned.

I appended to the IF statement to make it work
```
}else{
   var details:PropertyDetails<T> = new PropertyDetails(target, componentProperty, start, end - start);
   _propertyDetails.push (details); 
 }
```
However that is most likely wrong.

Click the bottom left button, of the index.html should animate.  Recompile and it should be broken.

[HaxeUITest.zip](https://github.com/haxeui/haxeui-core/files/3956515/HaxeUITest.zip)

**Comment by hoseyjoe** [comment]
I added openfl and nme as targets.  The accordion appears to crash in all (windows cpp, flash) but html5 targets?
I'm trying to get debuggers working to provide more information

[HaxeUITest.zip](https://github.com/haxeui/haxeui-core/files/3974071/HaxeUITest.zip)

**Comment by ianharrigan** [comment]
So, the thing is you are trying to use the actuator directly with integer values, where as the actuator deals with "values", you can make it work with something like:

```haxe
if (button.percentWidth == 50) {
    Actuator.tween(button, {percentWidth: Value.VNumber(100), percentHeight: Value.VNumber(100)}, 1, ao);
    // you could also use this way, which means an initial % w/h wouldnt need to be set
    //Actuator.tween(button, {width: Value.VDimension(Dimension.PERCENT(100)), height: Value.VDimension(Dimension.PERCENT(100))}, 1, ao);
} else {
    Actuator.tween(button, {percentWidth: Value.VNumber(50), percentHeight: Value.VNumber(50)}, 1, ao);
}
```

That should work, _however_ you could also just use css animations and let it do all the hard work for you:

```html
<style>
    @keyframes animateSize {
        0% {
            height: 50%;
            width: 50%;
        }
        100% {
            height: 100%;
            width: 100%;
        }
    }

    .button:normal {
        animation: animateSize 1s ease 0s 1 reverse backwards;
    }

    .button:large {
        animation: animateSize 1s ease 0s 1;
    }
</style>
```

Then to start the animation you could just add, remove or swap the pseudo classes (ive used pseudo classes, but you dont need to):

```haxe
if (button.hasClass(":large") == false) {
    button.swapClass(":large", ":small");
} else {
    button.swapClass(":normal", ":large");
}
```

Either would work, but personally, i think the css animations are simpler to use and more flexible also. Your call though ;)

Cheers,
Ian

**Comment by ianharrigan** [comment]
To make the actuator a little easier to work with, ive also added your fix, which works well, so if you dont use any values the actuator will still at least work. Beware though, things like colours will likely work a little strange!

Thanks for the fix!

Ian

**Comment by hoseyjoe** [comment]
The second attached issue (sorry this was a 2 in one!) was a crash in haxeui-openfl/nme.  It can be fixed by adding to haxe.ui.styles.ValueTools.calcDimension

It should look like
```
public static function calcDimension(value:Value):Null<Float> {
		if (value == null)
			return null
		else
			switch (value) {
...```

**Comment by ianharrigan** [comment]
Nice one, fixed now, and applied similar fix to other calls, not quite sure why it doesnt fall in the default case though, but either way, should be sorted now.
