### ISSUE TITLE
NumberStepper pos field cant be set to other float number than 0.0 in xml

### ISSUE THREAD

**Issue by mundusnine** [haxeui/haxeui-core#326]
## Summary:
A class named SceneSettings has an xml markup of how the ui should look. In that markup we have this field: `<numberstepper id="gravity_y" pos="20.0" step="0.1" width="35%" />`.

If the pos value is 0.0 at compilation time no errors occur but if the value of pos is other than 0.0 compilation fails with this error: ```/home/jsnadeau/foundsdk/haxeui-core/haxe/ui/macros/ComponentMacros.hx:271: characters 37-68 : String should be Float
/home/jsnadeau/Documents/projects/editor/Sources/SceneSettings.hx:9: lines 9-39 : Defined in this class```

The class uses this build macro: `@:build(haxe.ui.macros.ComponentMacros.build("../Assets/custom/scene-settings.xml"))`
## Expected Behavior

We should be able to build with other default values than 0.0
## Current Behavior

Compilation fails with error described above.
## Possible Solution

Setting it by code in class creation(i.e. new).
## Steps to Reproduce (for bugs)

1. Have a class use a build macro
2. Have a field in markup be a numberstepper with a pos value other than 0.0

## Your Environment

* Version used: Git version most recent
* Environment name and version (e.g. Chrome 39, node.js 5.4): debug-html5 Kha
* Operating System and version (desktop or mobile): Debian 10

**Comment by ianharrigan** [comment]
This should be fixed now, note, you can also use the "precision" attribute to get nicer formatted strings if you are working with decimals:

´<numberstepper id="gravity_y" pos="20.0" step="0.1" precision="3" width="35%" />´

If this is all working as expected, can you close the issue?

Thanks,
Ian

**Comment by ianharrigan** [comment]
Closing as no response, assuming fixed
