### ISSUE TITLE
Markup defined sliders with related labels crash when using ${sliderid.value}

### ISSUE THREAD

**Issue by mundusnine** [haxeui/haxeui-core#327]
## Summary:

Given a class that looks like: 
 ```
@:build(haxe.ui.macros.ComponentMacros.build("../Assets/custom/scene-settings.xml"))
class SceneSettings extends Component{

    public function new(){
        super();
    }
}
```
And a markup that looks like: 
```
<vbox>
   <hbox>
            <slider id="iterations" pos="0" precision="0" min="1" max="10" />
            <label id="itText" text="${iterations.value}" />
        </hbox>
        <hbox>
            <slider id="history" pos="0" precision="0" min="1" max="100" />
            <label id="histText" text="${history.value}" />
    </hbox>
</vbox>
```
When we dynamically try to create(new) SceneSettings class we get an exception thrown saying:
```
Exception has occurred: TypeError
TypeError: Cannot read property 'get_value' of null
    at new SceneSettings (/home/jsnadeau/Documents/projects/editor/Sources/SceneSettings.hx:8:1)
    at haxe_ui_util__$Listener_ListenerInternal.onClicked [as callback] 
```

## Expected Behavior

Have no null get_value field that throws an exception on new of class with markup ${slider.value}
## Current Behavior

Exception thrown because  get_value field is null when newing the SceneSettings class

## Steps to Reproduce (for bugs)

1. Create a class with a build macro
2. Create markup file for build macro that has a slider with a label.text="${slider.value}"

## Your Environment

* Version used: Git version most recent for haxeui core and kha
* Environment name and version (e.g. Chrome 39, node.js 5.4): debug-html5 Kha(electron)
* Operating System and version (desktop or mobile): Debian 10

**Comment by karliss** [comment]
There is an easy fix for exact case mentioned above by moving the named member initialization next to object creation, I tested and it works. It only works if the binding is to a component defined previously in the xml. Supporting general case with multiple ${} expressions chained would require toposorting them to find valid initialization order. Can ${} expression contain arbitrary expression or just "id.field"?

**Comment by ianharrigan** [comment]
> Can ${} expression contain arbitrary expression or just "id.field"

Ideally, it should be able to be anything that the script interp can handle, so something like this should also work:

`<label id="histText" text="${history.value + 100 / 33}" />`

**Comment by ianharrigan** [comment]
This should work now, just to be clear, this also works:

```xml
<vbox>
   <hbox>
        <slider id="iterations" pos="0" precision="0" min="1" max="10" />
        <label id="itText" text="${iterations.value + 100}" />
    </hbox>
    <hbox>
        <slider id="history" pos="0" precision="0" min="1" max="100" />
        <label id="histText" text="${history.value / 2 + 3}" />
    </hbox>
</vbox>
```
