### ISSUE TITLE
Space exists between 2 50% width inside hbox

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#33]
Space exists between 2 50% width inside hbox.  I tested HTML5 and NME.  Both have same space (5 pixels). If the width of column 1 is 100 then the left of column 2 is 105.  I think the space to the far right of column 2 (which occurs very little) only appears when slowly resizing html window

## Expected Behavior
No space

## Media

![image](https://cloud.githubusercontent.com/assets/2074385/18559527/744a7320-7b2c-11e6-994e-667a5033ce4b.png)

## Test app / minimal test case
<hbox id="main"  width="100%"  height="100%" style="padding:0" >
    <hbox width="50%" height="100%" style="background-color:#44fc04;padding:0" >		
	</hbox>
	<hbox width="50%" height="100%" style="background-color:#22c002;padding:0">		
	</hbox>
</hbox>

[BlankTemplate.zip](https://github.com/haxeui/haxeui-core/files/475194/BlankTemplate.zip)

**Comment by ianharrigan** [comment]
There are css properties for to handle horizontal and vertical spacing, these default to 5px as in general when you layout out components you want some space around them, the properties are:

```css
.something {
    horizontal-spacing: 0;
    vertical-spacing: 0;
    spacing: 0; /* this sets both */
}
```

This a separate calculation to padding (padding-left, padding-top, padding-bottom, padding-right) and margins  (margin-left, margin-top, margin-bottom, margin-right).

**Comment by hoseyjoe** [comment]
yep fixed. Created #34 fro the werid space issue
