### ISSUE TITLE
Virtual layout doesn't invalidate ItemRenderer instances  on itemRenderer change

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#330]
## Expected Behavior
When one of the ItemRenderer properties changes old item renderer instances don't get reused.

## Current Behavior
When ItemRenderer gets changed old instances from child list in non virtual mode and from _rendererPool in virtual mode are reused even though they are clones of wrong ItemRenderer.

## Possible Solution
When one of `itemRenderer*` from `IVirtualContainer` interface are changed it needs to notify `VirtualLayout` that previously created `ItemRenderer` instances in the child list or _rendererPool can't be reused.

## Steps to Reproduce (for bugs)

TODO: needs to updated once test case is finished
1. Run the example
2. Click "Add column"
3. Click "Add some items"
4. Observe that only new items are using the new item renderer

## Media

First three rows were added before second column with number editor was added.
![table screenshot](https://user-images.githubusercontent.com/7101031/74585587-a1921800-4fe6-11ea-8fcc-2ad0df001146.png)

## Test app / minimal test case
For simplicity I am demonstrating using listview, but I am more interested in doing similar thing with tableview.
```xml
<?xml version="1.0" encoding="utf-8" ?>
<vbox width="100%">
    <script>
    var columnCount = 1;
    function addItems(lv, count) {
        lv.dataSource.allowCallbacks = false; // speeds things up a little
        for (i in 0...count) {
            lv.dataSource.add(lv.dataSource.get(0));
        }
        lv.dataSource.allowCallbacks = true;
    }
    function addColumn1(lv) {

        columnCount += 1;
        var renderer = new haxe.ui.core.ItemRenderer();
        renderer.layoutName = "horizontal";
        for (i in 0...columnCount) {
            var label = new Label();
            label.id = 'c'+Std.string(i);
            renderer.addComponent(label);
        }
        lv.itemRenderer = renderer;
    }
    </script>
    <hbox>
        <vbox>
            <listview id="lv2" width="200" height="150" selectedIndex="1">
                <item-renderer layoutName="horizontal" width="100%">
                    <label id="c0" />
                </item-renderer>
                <data>
                    <item c0="c0" c1="c1" c2="c2" c3="c3" c4="c4" c5="c5" c6="c6" c7="c8" />
                </data>
            </listview>
            <vbox>
                <button text="Add some items" onclick="addItems(lv2, 2)" />
                <button text="Add column" onclick="addColumn1(lv2)" />
            </vbox>
        </vbox>    
    </hbox>
</vbox>
```

## Your Environment

* Version used: haxeui-core 1,0,21
* Environment name and version (e.g. Chrome 39, node.js 5.4): chromium 80.0.3987.87 
* Operating System and version (desktop or mobile): Linux
* Link to your project: https://github.com/karliss/kb-editor/

**Comment by ianharrigan** [comment]
Am i right in thinking this isnt related to virtual lists? Ive ran your example (which doesnt include virtual=true btw) and get:

![image](https://user-images.githubusercontent.com/3024242/75673418-33ef1880-5c83-11ea-89d0-a023f5cce72b.png)

And am i right in thinking that yo uwould have expected all previous rows to also show c1, c2, etc?

**Comment by karliss** [comment]
As I said before It affects both virtual and non virtual mode but the code responsible for caching items in each case is different. It needs to be fixed in both cases.

**Comment by karliss** [comment]
From what I remember list without virtual=true still uses "VirtualLayout" with bunch of `if (comp.virtual == true)` and `if (comp.virtual == false)` in it.

**Comment by ianharrigan** [comment]
Yeah, just needed to sanity check i was understanding the issue

**Comment by ianharrigan** [comment]
Can we retest this and see if it works? It should do now.

Cheers,
Ian

**Comment by karliss** [comment]
Works.
