### ISSUE TITLE
Scrollbar break tableview in virtual mode

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#332]
Changing amount of items in table can lead to a state where scrollbar is displayed but there aren't enough items. At that point touching scrollbar allows scrolling very with the same content repeating.

## Expected Behavior
When there aren't enough items scrollbar isn't displayed or the scrollbar limits have reasonable values.

## Current Behavior
Reducing item count leaves the scrollbar visible and table reacts badly to attempts using it.

## Steps to Reproduce (for bugs)

1. Add items to table until scrollbar appears
2. Remove items so that there are few less than widget height
3. Observe that scrollbar remains
4. Observe that trying to use the scrollbar causes weird behavior

## Media
![virtual_table_scrollbar_bug](https://user-images.githubusercontent.com/7101031/74831313-b1c73180-531d-11ea-9264-bddb56bd43ff.png) 
In the screenshot table is supposed to have 11 items with numbers in order.

## Context
Has little effect on my project as I can use the table in non virtual mode. Expected number of rows is low so performance shouldn't be a problem.

## Your Environment

* Version used: 1.0.21 with some changes that I was going to make PR for, need to test with clean 1.0.21
* Environment name and version (e.g. Chrome 39, node.js 5.4): Firefox 73.0 (64-bit)
* Operating System and version (desktop or mobile): Linux

**Comment by ianharrigan** [comment]
Can we retest this on latest git?

**Comment by karliss** [comment]
Scrollbar gets removed, seems to be fixed.

**Comment by ianharrigan** [comment]
Cool - im going to close this now - fixed a couple of other issues around this kinda area too.

Cheers,
Ian
