### ISSUE TITLE
Slowly resizing causes space on right side of hbox

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#34]
Using the example.  Slowly resize the window. It seems to happen on window reduction.  You should see a space appear on the right side. I think this only happens in JS/HTML as the CPP resize may be quicker?

## Expected Behavior
Space should not appear

## Media
![image](https://cloud.githubusercontent.com/assets/2074385/18559527/744a7320-7b2c-11e6-994e-667a5033ce4b.png)

## Test app / minimal test case
BlankTemplate.zip](https://github.com/haxeui/haxeui-core/files/475194/BlankTemplate.zip)

**Comment by ianharrigan** [comment]
Can you retest this? It should be fixed now.

Cheers,
Ian

**Comment by hoseyjoe** [comment]
Looks good
