### ISSUE TITLE
Android Events.cpp build error

### ISSUE THREAD

**Issue by gpaluk** [haxeui/haxeui-core#345]
## Expected Behavior

I was expecting to be able to include the library as part of an Android build.

## Current Behavior

Get the following build error:

```
Error: ./src/haxe/ui/components/_Switch/Events.cpp:80:21: error: no member named '_switch' in 'haxe::ui::components::_Switch::Events_obj'
HXLINE(  35)            this->_switch = s;
```

## Steps to Reproduce (for bugs)

1. Include haxe-ui in a project
2. Select Android build
3. Build

**Comment by ianharrigan** [comment]
What version of haxeui-core are you using haxelib or git? I believe this should be fixed in git version, but i have released a haxelib yet

**Comment by gpaluk** [comment]
Yeah, I'm using the latest that gets pulled via:
`> haxelib install haxeui-core`

**Comment by ianharrigan** [comment]
this should be fixed in the git version, before creating a release, any chance you could confirm that by using the git version of haxeui-core?

**Comment by ianharrigan** [comment]
Closing as no response, assuming fixed.
