### ISSUE TITLE
Number stepper  in box with scroll openfl 

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#347]
It happens  when you have number stepper inside a box which has a scroll

## Expected Behavior
When you click you button "up" of the button stepper , the number should go up.

## Current Behavior
The first time you click on the button "up", of the number stepper, it goes at the top of the container box.

## Steps to Reproduce (for bugs)

```xml
<vbox id="Settings List" width="100%" height="30%" >
		<property-grid id="pg" width="100%" height="100" onchange="trace(event.target.id + ' = ' + event.target.value)">
			<property-group text="Secondary Group">
				<property label="String Property" value="Value 2" />
				<property label="Bool Property" type="boolean" value="false" />
				<property label="Int Property" type="int" value="102" />
				<property label="List Property" type="list" value="Item 2">
					<data>
						<item value="Item 1" />
						<item value="Item 2" />
						<item value="Item 3" />
						<item value="Item 4" />
						<item value="Item 5" />
						<item value="Item 6" />
					</data>
				</property>    
			</property-group>
			
			<property-group text="Tertiary Group">
				<property label="String Property" value="Value 3" />
				<property label="Bool Property" type="boolean" value="true" />
				<property label="Int Property" type="int" value="103" />
				<property label="List Property" type="list" value="Item 3">
					<data>
						<item value="Item 1" />
						<item value="Item 2" />
						<item value="Item 3" />
						<item value="Item 4" />
						<item value="Item 5" />
						<item value="Item 6" />
					</data>
				</property>    
			</property-group>
		</property-grid>
	</vbox>
```

I don't why , the whole code doesn't appear in my preview, but it's the xml demonstrating the property grid on your website.

   There must be a scroll in the box "Settings List" , so change the height as needed
1. Click "up" on the on the number stepper  , it goes at the top of the box
2.  Click  "up" on the on the  same number stepper, it works normally.

## Your Environment

* Version used:  haxeui-openfl
* Environment name and version (e.g. Chrome 39, node.js 5.4): html Firefox 75.0
* Operating System and version (desktop or mobile): Ubuntu,

**Comment by Shallowmallow** [comment]
Thanks :)
Indeed, it does.  
More precisions  : 
 - it does  the same in openfl, ubuntu  desktop as in  openfl, ubuntu  firefox .
 - whether you click on the button up or down of the number stepper,   it goes at the top of the container box
- I tried clicking everywhere to change the focus to ther components, containers, but it seems to only do it once.

**Comment by ianharrigan** [comment]
Great... thanks... I think i know what it is. :)

**Comment by ianharrigan** [comment]
Pretty late :/

But this should be fixed now in latest git version. 

Cheers,
Ian
