### ISSUE TITLE
Can't find item MenuItem with findComponent

### ISSUE THREAD

**Issue by guifes** [haxeui/haxeui-core#348]
## Expected Behavior
This snippet works fine for me. (this one has id="test" in a Button item in main.xml)
```haxe
var main: VBox = ComponentMacros.buildComponent("assets/ui/xml/main.xml");
Screen.instance.addComponent(main);
var button: Button = main.findComponent("test", Button, true);
trace(button);
```
## Current Behavior
This one traces: null (this one has id="test" in a MenuItem item in main.xml)
```haxe
var main: VBox = ComponentMacros.buildComponent("assets/ui/xml/main.xml");
Screen.instance.addComponent(main);
var button: MenuItem = main.findComponent("test", MenuItem, true);
trace(button);
```
## Possible Solution
From @ianharrigan 

> The problem here is the menu items are created dynamically, on demand as they parent menu are shown
i think there is a way around it though, ill have to have a look.

## Context
I can't find another another way of adding actions to MenuItens by code.

**Comment by ianharrigan** [comment]
This should be fixed now. Can you close when you get a moment?

Cheers,
Ian

**Comment by guifes** [comment]
Working 100% now
