### ISSUE TITLE
Scrollview with width=auto, or no width, explodes(?)

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#35]
Scrollview with width=auto, or no width, explodes(?) when vertical scrollbaris required
I wanted the balck area to fit the buttons width.  I expect translations for the buttons at some point so their width could be variable.

## Expected Behavior
if a width is set to auto then the width should match

## Possible Solution
adding a fixed width resolves issue

## Steps to Reproduce (for bugs)
1. run the test app in html 
2. resize until a vertical scroll bar would be required

## Media
Before 
![image](https://cloud.githubusercontent.com/assets/2074385/18567893/1fb7b8ae-7b4f-11e6-9ae9-4bbc214567f8.png)

after
![image](https://cloud.githubusercontent.com/assets/2074385/18567898/29d923a4-7b4f-11e6-8d2b-1dd2c7060e82.png)

## Test app / minimal test case
[BlankTemplate.zip](https://github.com/haxeui/haxeui-core/files/475604/BlankTemplate.zip)

**Comment by ianharrigan** [comment]
This should be fixed, can you retest and close if working as expected?

Cheers,
Ian

**Comment by hoseyjoe** [comment]
This appears fixed to me
