### ISSUE TITLE
Inner scroll with outer scroll

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#350]
2 scroll areas with parent child relationship.  Inner scroll area ignored

## Expected Behavior
It would scroll and parent would not

## Current Behavior
Parent scroll doesnt scroll

use html project but I repeated in nme also.  it is assumed to be generally wrong
[Full.zip](https://github.com/haxeui/haxeui-core/files/4595029/Full.zip)

**Comment by ianharrigan** [comment]
can you retry this will latest git version? I think ive fixed _some_ of the issues in the app, but there is some noise in the test app, so its hard to know fully if the issue i fixed is the issue the app is describing

**Comment by hoseyjoe** [comment]
It works as expected except maybe for mouse wheel. Video attached


[2020-08-11 17-46-29.zip](https://github.com/haxeui/haxeui-core/files/5060072/2020-08-11.17-46-29.zip)
