### ISSUE TITLE
HaxeUI Do Not Work With Haxe 4.1

### ISSUE THREAD

**Issue by 3mic4nia** [haxeui/haxeui-core#354]
The compilation fails with Haxe 4.1

## Expected Behavior

The program should have been compiled

## Current Behavior

The program is not compiled

## Steps to Reproduce (for bugs)

1. Update to Haxe 4.1
2. Start an HaxeUI sample
3. Compile
4. See the error

## Your Environment

* Version used:
HaxeUI 1.8.21
OpenFl 8.9.6
* Environment name and version (e.g. Chrome 39, node.js 5.4):
Haxe 4.1
* Operating System and version (desktop or mobile):
Windows 10
* Link to your project:

**Comment by hoseyjoe** [comment]
My project compiles to Hashlink, Html, openfl windows.... But I am using 
Haxeui Core Git
Haxe 4.1
and the appropriate target lib
HaxeUI-openfl Git

try using the GIT version of HaxeUI as Haxe4.1 is newer than HaxeUI release

It may be helpful to supply you test project as well.  Cheers

**Comment by ianharrigan** [comment]
Yeah, this because the haxelib version is fairly out of date now, im trying to get a new 1.1 version together but keep finding little things that need to be fix, im going to close this as the git version (and therefore the next haxelib version) is working fine with 4.1 and higher.

Cheers,
Ian
