### ISSUE TITLE
HaxeUI app no longer quits Haxe 4.1.1 on MacOSX

### ISSUE THREAD

**Issue by KanedaFr** [haxeui/haxeui-core#355]
Launch an app which you know was working on 4.0.5
Click on close app icon (at top left of window)
Window closed but is still present in background (Force quit needed)

**Comment by KanedaFr** [comment]
Only one of my 2 apps no longer quits
I'll try to find why...

**Comment by ianharrigan** [comment]
Hmmm, thats strange, and this is only just started happening with haxe 4.1? Or maybe there was a commit to something in haxeui-core, haxeui-hxwidgets, hxWidgets that broke something? Are you on git versions of all of them?

**Comment by KanedaFr** [comment]
Yes : git version of haxeui and backends
Yes : it worked with 4.0

**Comment by ianharrigan** [comment]
Am i right in thinking this not longer an issue but was something to do with hxcpp_debugger? 

Ian
