### ISSUE TITLE
In hxwidgets skeleton app, consider renaming main Component

### ISSUE THREAD

**Issue by uvtc** [haxeui/haxeui-core#356]
When creating a brand new skeleton project via

    haxeui create hxwidgets

the main Component (for assets/main.xml) is named "main", but that name is the same as the "public static function main", and would need to be renamed if moved out to be a static variable in the Main class.

Could it be renamed to "mainView", "mainXML", "mainGUI", or similar?

**Comment by ianharrigan** [comment]
Yeah, not a bad idea, mainView would work, its actually what i call my... erm... main views... anyway ;)

**Comment by uvtc** [comment]
:)

I don't know my way around here. Is it a change that only needs to be made in one file?

**Comment by ianharrigan** [comment]
Yeah, its just this file: https://github.com/haxeui/haxeui-core/blob/master/cli/templates/shared/Main.hx, and then the CLI app needs to be rebuilt.

**Comment by ianharrigan** [comment]
This is fixed now, im going to close as ive test and it does work, new template looks like this:

```haxe
package ;

import haxe.ui.HaxeUIApp;
import haxe.ui.core.Component;
import haxe.ui.macros.ComponentMacros;

class Main {
    public static function main() {
        var app = new HaxeUIApp();
        app.ready(function() {
            var mainView:Component = ComponentMacros.buildComponent("assets/main-view.xml");
            app.addComponent(mainView);

            app.start();
        });
    }
}
```

**Comment by uvtc** [comment]
Ah, you changed the filename as well. Excellent! Thank you!
