### ISSUE TITLE
NumberStepper change request: Don't commit text input change until enter, lose focus, or other qualifier

### ISSUE THREAD

**Issue by intoxopox** [haxeui/haxeui-core#357]
When given a keyboard entry, don't commit change until enter key or focus change (or other qualifying event), so that min/max correction doesn't happen until user entry is complete.
For example, min=5 and max=100. User should be able to type 22 without it changing to 52 (2 currently changes to min 5 immediately).

## Expected Behavior
NumberStepper with min of 5 and max of 100. Typing 22 and hitting enter or changing focus (or some other qualifying event) should commit the change, but not before then.

## Current Behavior
Typing "22" in the above case immediately changes the "2" to the min value of "5", resulting in "52". As you can imagine, other min/max values could cause even more confusion from user perspective.

## Possible Solution
Don't commit free-typed value as change until "enter" key is pressed, focus changes, or any other reasonable event occurs. Not currently sure what other reasonable event here, but leaving that as an open question.

**Comment by ianharrigan** [comment]
Im going to close this since the PR was merged
