### ISSUE TITLE
Scrollbar wont release when registrEvent MOUSE_UP applied

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#36]
Scrollbar wont release when registrEvent MOUSE_UP applied.  

## Expected Behavior
When mouse up occurs the scroll should release

## Steps to Reproduce (for bugs)
1. Compile sample app
2. make sure the list needs to scroll
3. click on thumnb and slide it up and down
4. release mouse

## Media
After mouse is up you can see it is still highlight like it is tracking
![image](https://cloud.githubusercontent.com/assets/2074385/18572526/11a1a14a-7b71-11e6-88cb-2cf861ec7e21.png)

## Test app / minimal test case
[BlankTemplate.zip](https://github.com/haxeui/haxeui-core/files/475907/BlankTemplate.zip)

**Comment by ianharrigan** [comment]
Ok, i think i can see what the problem was, its when you move the mouse out of the browser document. Ive supplied a fix, however, it wont work in chrome currently.

**Comment by hoseyjoe** [comment]
this is fixed
