### ISSUE TITLE
haxe.ui.macros.Macro.hx causes compiler to fail when a class extends component and expects argument in constructor

### ISSUE THREAD

**Issue by kevansevans** [haxeui/haxeui-core#364]
Adding arguments to the extended classes causes compile errors:

``Building HaxeUIMacroBug
Running Pre-Build Command Line...
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "project.xml" windows -release -Dfdb
Warning: Lime version 7.8.0 may not be compatible with OpenFL 8.9.7 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
C:/HaxeToolkit/haxe/lib/haxeui-core/1,1,1/haxe/ui/macros/Macros.hx:320: characters 20-35 : Not enough arguments, expected _someDumbArgumentHere:String
src/AClassThatExtendsBoxAndExpectsArguments.hx:9: lines 9-17 : Defined in this class
Build halted with errors.``

``src/AClassThatExtendsBoxAndExpectsArguments.hx:9: lines 9-17 : Defined in this class``

``C:/HaxeToolkit/haxe/lib/haxeui-core/1,1,1/haxe/ui/macros/Macros.hx:320: characters 20-35 : Not enough arguments, expected _someDumbArgumentHere:String``

Extend box class and add expected argument to new(), then declare new class.

    class Main extends Sprite 
    {

	var someDumbVarThing:AClassThatExtendsBoxAndExpectsArguments;
	
	public function new() 
	{
		super();
		
		someDumbVarThing = new AClassThatExtendsBoxAndExpectsArguments("HURR DURR");
	}

    }

///////////////////

    import haxe.ui.containers.Box;

    class AClassThatExtendsBoxAndExpectsArguments extends Box \\ <--- Line 9
    {

	public function new(_someDumbArgumentHere:String) 
	{
		super();
	}
	
    }

HaxeDevelop/FlashDevelop project
[Haxeui-bug.zip](https://github.com/haxeui/haxeui-core/files/5003642/Haxeui-bug.zip)

Haxeui-core 1.1.1
Haxeui-openfl 1.1.0
Haxe 4.1.3
Windows 10

**Comment by ianharrigan** [comment]
This should be fixed now in latest git version (haxeui-core)... any chance you can retest and close if you have a minute.

Cheers,
Ian

**Comment by kevansevans** [comment]
No compile errors, this fix works. Thank you Ian!
