### ISSUE TITLE
Setting BorderSize and BorderColor in .hx file doesn't work for Grid

### ISSUE THREAD

**Issue by davzrm** [haxeui/haxeui-core#368]
Hello, 

Tried to set the border attributes for a grid from the .hx file, but it's not showing the border.
```
import haxe.ui.containers.grid; 

@:build(haxe.ui.macros.ComponentMacros.build('assets/custom/cell.xml')
class Cell extends Grid{
... some code 
this.borderColor = 0x000000;
this.borderSize = 2;
}
```
... doesn't work.
Unless I am misunderstanding the behaviour.
Setting ```styleString = 'border: 2px solid black' ```  in the .hx file  works.

Setting  ```style = 'border: 2px solid black' ``` in the ```<grid/>``` from the xml file itself works as well .

Only tried for Grid, not sure about the other containers.

**Comment by ianharrigan** [comment]
Hi, thanks for this, any chance you could paste the contents of cell.xml? Just to be sure were looking at the same thing.

Thanks,
Ian

**Comment by davzrm** [comment]
Sure thing. It's only one line. 
cell.xml 
```
<grid/>
```

**Comment by ianharrigan** [comment]
Ah, ok... cool :)

**Comment by ianharrigan** [comment]
This should be fixed now in git version, im going to close this but let me know if you have any issues

Cheers,
Ian
