### ISSUE TITLE
Label.width is incorect if .htmlText used

### ISSUE THREAD

**Issue by NipponSunrise** [haxeui/haxeui-core#370]
`Label.width` returns `0` if `Label.htmlText` is used instead of `Label.text`.

## Expected Behavior
`Label.width` should return correct label's width

## Steps to Reproduce 
Run the code:

        Toolkit.init();
        var label:Label = new Label(); 
        label.htmlText = "some text";
        Screen.instance.addComponent(label);
        trace(label.width); //<-- prints 0

## Context
Can't use labels with HTML markup in containers without explicit width setting.

## Environment
`haxeui-core 1.1.2`
`haxeui-openfl 1.1.0`
`openfl 8.9.7`
`lime 7.8.0`

html5 target with canvas rendering

**Comment by ianharrigan** [comment]
What happens if you use .text rather than .htmlText? I wonder if it needs a frame to update?

**Comment by NipponSunrise** [comment]
> 
> 
> What happens if you use .text rather than .htmlText? I wonder if it needs a frame to update?

        Toolkit.init();
        var label:Label = new Label(); 
        label.text = "some text";
        Screen.instance.addComponent(label);
        trace(label.width); //<-- prints 54 as expected

**Comment by ianharrigan** [comment]
Ok, great, thanks for the info, ill look into it.

**Comment by ianharrigan** [comment]
Ok, so this should be fixed now... was a silly mistake :)

Im going to close this, let me know if you have further issues
