### ISSUE TITLE
Haxe 4.2 Compile Errors

### ISSUE THREAD

**Issue by Shaylin** [haxeui/haxeui-core#377]
Upon upgrading to Haxe version 4.2, I've noticed some compiler errors. These do not occur when I was on version 4.1.5.
I have an OpenFL test project where the issue occurs: https://gitlab.com/Shaylin/haxeui-test
This issue also occurs on another internal project that is using haxeui-html5 without OpenFL.

## Expected Behavior
The compilation should succeed.

## Current Behavior
As mentioned above, here are some of the errors produced:

```
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : ... For function argument
 'value'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/containers/ScrollView.hx:27: lines 27-99 : ... Defined in this cla
ss
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:26: characters 51-65 : haxe.ui.constants.Scale
Mode should be Null<haxe.ui.util.Variant>
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:26: characters 51-65 : ... For optional functi
on argument 'defaultValue'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:27: characters 51-73 : haxe.ui.constants.Horiz
ontalAlign should be Null<haxe.ui.util.Variant>
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:27: characters 51-73 : ... For optional functi
on argument 'defaultValue'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:28: characters 51-71 : haxe.ui.constants.Verti
calAlign should be Null<haxe.ui.util.Variant>
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:28: characters 51-71 : ... For optional functi
on argument 'defaultValue'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:377: characters 25-58 : haxe.ui.util.Variant shou
ld be haxe.ui.constants.ScaleMode
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:20: lines 20-31 : ... Defined in this class
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : haxe.ui.constants.ScaleMo
de should be haxe.ui.util.Variant
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : ... For function argument
 'value'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:20: lines 20-31 : ... Defined in this class
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:377: characters 25-58 : haxe.ui.util.Variant shou
ld be haxe.ui.constants.HorizontalAlign
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:20: lines 20-31 : ... Defined in this class
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : haxe.ui.constants.Horizon
talAlign should be haxe.ui.util.Variant
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : ... For function argument
 'value'
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:20: lines 20-31 : ... Defined in this class
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:377: characters 25-58 : haxe.ui.util.Variant shou
ld be haxe.ui.constants.VerticalAlign
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/components/Image.hx:20: lines 20-31 : ... Defined in this class
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : haxe.ui.constants.Vertica
lAlign should be haxe.ui.util.Variant
C:/Dev/haxeui-test-master/.haxelib/haxeui-core/1,1,3/haxe/ui/macros/Macros.hx:407: characters 56-61 : ... For function argument
 'value'
```

## Possible Solution
There does seem to be a lot of breaking changes in Haxe 4.2. One would have to go through and address these compiler errors while trying to keep the API the same.

## Steps to Reproduce (for bugs)
1. Install Haxe version 4.2
2. Clone this test repository: https://gitlab.com/Shaylin/haxeui-test
3. Run through the readme steps to install the required haxelibs
4. Run `lime test windows` (or your platform of choice)
5. Using `lime test html5` also produces the error

## Test app / minimal test case
See steps to reproduce.

## Context
I can't compile any projects with Haxe 4.2. I've since downgraded to 4.1.5 as a temporary solution, but we're inevitably going to use the new features that 4.2 provides (such as rest args). So it would be helpful to have haxe-ui work with this version.

## Your Environment
* Version used: 1.1.3
* Environment name and version: Haxe 4.2, NodeJS 14 LTS, MSVC Build Tools 2019
* Operating System and version: Windows 10 Build 1909
* Link to your project: https://gitlab.com/Shaylin/haxeui-test

**Comment by ianharrigan** [comment]
Damn, i thought i might have gotten away with the 4.2 upgrade woes since i hadnt heard anything and ive been on 4.2-rc1 for a while - guess i wasnt so lucky :)

Ill upgrade shortly and fix the issues... 

Cheers,
Ian

**Comment by ianharrigan** [comment]
Does openfl work in 4.2 yet? Ive just tried to compile a test project with 4.2 (haxeui-html5) and got warnings but no errors...

a haxeui-openfl project didnt work because of openfl failures (which may already be fixed?)

Ian

**Comment by Shaylin** [comment]
Hello, I can confirm that the errors go away when I use the git versions of haxeui-core and haxeui-html5. The test project builds correctly now and I think I've just got the same warnings as you. 
![Screenshot from 2021-02-16 20-28-17](https://user-images.githubusercontent.com/13178548/108105702-a1af7280-7095-11eb-9bd0-da5591b1b450.png)

So it does look like the issue is just with 1.1.3 then. Thanks for the feedback 👍

**Comment by ianharrigan** [comment]
Ok, thats great to know... more reason to get a new release out asap... thanks!
