### ISSUE TITLE
 C:\SDK\haxe\std/neko/_std/Date.hx line 126  on Linux

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#378]
## Current Behavior
when I do

`haxelib run haxeui-core`

I have this error
```
Called from C:\SDK\haxe\std/neko/_std/Date.hx line 126
Uncaught exception - load.c(357) : Primitive not found : std@date_utc_format(2)
```

The funny thing is that I am on Linux. So I don't see where c:\SDK\ is coming from

I think the haxe std installed  by default is too old.

## Possible Solution

What I have tried
 - export $HAXE_STD_PATH to a more recent SDK 
 But it doesn't work

I suppose I have to rebuild the client. But I don't know how
I tried installing https://github.com/Montycarlo/hxproj but it doesn't seem to recognise the hxproj.
It says "Failed to find a .hxproj file." But maybe I don't know how to use it.

## Steps to Reproduce (for bugs)

install haxeui-core by haxelib
install haxe by apt-get

## Your Environment
I've tested on Ubuntu 16.04 and raspberry ( raspios or raspbian)

Thanks for your great work.

**Comment by ianharrigan** [comment]
Thats weird... C:\SDK is _my_ local windows haxe installation dir... no idea why that would be in the neko run file... i just realised there isnt a build.hxml file in there either (which there should be). Lemme try and rebuild it first (the .n) and add a build.hxml file

**Comment by ianharrigan** [comment]
Ok, so i rebuilt and git didnt think there were any changes to the .n file... Ive looked at the .n file and there are refs to things like `C:\SDK\haxe\std/Any.hx` which is specific to my machine... super weird... what version of haxe / neko are you using? 

Also, btw, ive added a "build.hxml" file now in the haxeui-core/cli dir, so you could, at least, be able to build your own version of run.n...

Let me know if that fixes the issue... still really strange though

**Comment by Shallowmallow** [comment]
It seems to work :) Rebuild it and everything seems to work

( Haxe was 3.4.7  on the raspberry and 4.05 on the ubuntu, for the neko not sure how to check)

**Comment by Shallowmallow** [comment]
I'm not sue of the problem ..  I think in fact , it happens when you have an old version of neko.
Neko tries to find to found the original path of STD for some reason.
So you just need the to update neko ( for some reason when I update haxe on Linux, it doesn't update automatically neko)

**Comment by tom-hines** [comment]
I just got this error too.

```
$ haxelib run haxeui-core help
Called from C:\SDK\haxe\std/neko/_std/Date.hx line 126
Uncaught exception - load.c(357) : Primitive not found : std@date_utc_format(2)
```

Haxe and neko are installed and working properly.

Linux Mint 19.3
Haxe 4.2.5
Neko 2.2.0-2build1
haxeui-core git (1.4.0 ?)

**Comment by ianharrigan** [comment]
Have you tied using dates in neko outside of haxeui, this looks to be a neko / haxe issue.

**Comment by tom-hines** [comment]
Definitely not a haxeui-core problem.

None of the Date UTC methods worked.  I thought I was on the latest neko version but it turns out the latest is 2.3.0.  I followed the instructions at [nekovm download](https://nekovm.org/download/) for installing from the PPA.  Problem solved.

**Comment by ianharrigan** [comment]
cool - glad you got it fixed - any chance you could close this if you are happy haxeui isnt the culprit?

Cheers,
Ian

**Comment by tom-hines** [comment]
I can't close it because I didn't open it.

I just discovered there's a haxe docker image that includes the proper neko version.  I'll use that next time.

**Comment by ianharrigan** [comment]
Oh - sorry - my bad - i wasnt looking at names :)

I think im going to close it then.
