### ISSUE TITLE
haxe 3.4.7 cannot compile

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#379]
I cannot use the latest version of haxeui-core with haxe 3.4.7

## Current Behavior
when I create a project with a haxeui-core
and then I try to compile the project it says

`haxe/ui/tooltips/ToolTipOptions.hx:6: characters 8-9 : Unexpected ?`

It's because the class notation is only valid since haxe 4.0.0
https://haxe.org/manual/types-structure-optional-fields.html 

## Possible Solution
to not use the class notation in 
haxe/ui/tooltips/ToolTipOptions.hx  and
haxe/ui/dragdrop/DragOptions.hx

or to abandon haxe 3.4.7

**Comment by Shallowmallow** [comment]
You also cannot clear a map in haxe 3.4.7

haxe/ui/core/TextDisplay.hx:268: characters 8-32 : Map<String, Bool> has no field clear
haxe/ui/core/ComponentValidation.hx:174: characters 8-32 : Map<String, Bool> has no field clear
haxe/ui/core/ComponentValidation.hx:185: characters 8-39 : Map<String, Bool> has no field clear

## Solution
Iterating on all keys, and call remove from there.

Now it seems to compile  :)

**Comment by ianharrigan** [comment]
Is there a reason you are using 3.4.7? Im just wondering if there is a valid reason to support it.

Cheers,
Ian

**Comment by Shallowmallow** [comment]
I use it because it's the default haxe on raspbery pi. Haxe 4.0 on raspberry pi seems quite difficult to compile/install, I wasn't able to do it even though it seems some  people could https://community.haxe.org/t/solved-haxe-4-14-on-raspbian/2707 .
Hopefully it will be on the repositories soon

**Comment by ianharrigan** [comment]
OK, cool - so that seems like a pretty valid reason. Ill see about supporting 3.4.7, at least for the time being, doesnt seem like there are a huge amount of issues anyway

**Comment by Shallowmallow** [comment]
I was able to install haxe 4.1.2 on Raspberry pi 4. Hopefully, it will soon available on the repositories. I wrote how on the mentioned link https://community.haxe.org/t/solved-haxe-4-14-on-raspbian/2707

**Comment by ianharrigan** [comment]
This should work now, there are also GH actions for various haxe versions, one being 3.4.7, so if in the future i accidently use a 4.x feature this should let us know (its already happened once or twice).

Im going to close this.
