### ISSUE TITLE
Problem when no haxe/ui/_module/styles folder ( With Solution)

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#380]
## Current Behavior
when doing 
`haxe hxwidgets.hxml `

```

/usr/share/haxe/std/neko/_std/sys/FileSystem.hx:59: characters 21-74 : Error stat /home/pi/Ste/plaf/haxe/lib/hscript/2,4,0/haxe/ui/_module/styles
/home/pi/Ste/plaf/haxe/lib/haxeui-core/1,2,2/haxe/ui/macros/ModuleMacros.hx:222: characters 24-49 : Called from
/home/pi/Ste/plaf/haxe/lib/haxeui-core/1,2,2/haxe/ui/macros/ModuleMacros.hx:53: characters 40-60 : Called from
/home/pi/Ste/plaf/haxe/lib/haxeui-core/1,2,2/haxe/ui/Toolkit.hx:72: characters 8-37 : Called from
Aborted

```

## Possible Solutions
https://github.com/haxeui/haxeui-core/blob/b528779c91ea8b6e5243452b51d6386b1aa59249/haxe/ui/macros/ModuleMacros.hx#L222

Just invert
var isDir =  FileSystem.exists(p) && FileSystem.isDirectory(p);

**Comment by ianharrigan** [comment]
Nice one, i fixed something just like that in another place - that should be fixed it git now, if that works can you close?

Cheers,
Ian

**Comment by Shallowmallow** [comment]
It works, so closing ! :)
