### ISSUE TITLE
App crashes clicking on switch component

### ISSUE THREAD

**Issue by Sartoric** [haxeui/haxeui-core#384]
I have a very simple view just to test components

```
<vbox  style="padding: 5px;">
    <button id="toggle1" toggle="true" selected="false" text="Camera" style="font-size: 24px;"/>
    <switch styleName="pill-switch"  />
</vbox>
```

and a basic Main class

```
class Main {
    public static function main() {
        var app = new HaxeUIApp();
        app.ready(function() {
            var mainView:Component = ComponentMacros.buildComponent("assets/main-view.xml");
            app.addComponent(mainView);
            app.start();
        });
    }
}
```

When I click the switch the app crashes
No problem with the toggle (or button)

I'm using haxe 4.1.15 (due to compatibility issues with Openfl) targeting Neko
 and 

haxelib: [3.3.0]
haxeui-core: [1.2.3]
haxeui-openfl: [1.2.3]
hxcpp: [4.1.15] 4.2.1
lime: 7.7.0 [7.8.0] 7.9.0 <---- same issue using 7.7.0
openfl: [9.0.2]

ERROR : 
Called from haxe/ui/styles/animation/util/Actuator.hx line 137
Called from haxe/ui/styles/animation/util/Actuator.hx line 78
Called from haxe/ui/styles/animation/KeyFrame.hx line 43
Called from haxe/ui/styles/animation/Animation.hx line 289
Called from haxe/ui/styles/animation/Animation.hx line 174
Called from haxe/ui/core/Component.hx line 1896
Called from haxe/ui/core/Component.hx line 1801
Called from haxe/ui/core/Component.hx line 1694
Called from haxe/ui/core/ComponentValidation.hx line 236
Called from haxe/ui/core/ComponentValidation.hx line 171
Called from haxe/ui/validation/ValidationManager.hx line 128
Called from haxe/ui/util/Timer.hx line 10
Called from haxe/ui/backend/TimerImpl.hx line 16
Called from openfl/events/EventDispatcher.hx line 178
Called from a C function
Called from openfl/display/DisplayObject.hx line 516
Called from openfl/display/Stage.hx line 1158
Invalid field access : index
Called from ? line 1
Called from ApplicationMain.hx line 25
Called from ApplicationMain.hx line 130
Called from lime/app/Application.hx line 150
Called from lime/_internal/backend/native/NativeApplication.hx line 146
Called from a C function
Called from lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime/_internal/macros/EventMacro.hx line 91
Called from openfl/display/Stage.hx line 1949
Called from openfl/display/Stage.hx line 1162
Called from openfl/display/Stage.hx line 1422
Called from openfl/display/Stage.hx line 1158
Called from openfl/display/DisplayObject.hx line 516
Called from a C function
Called from openfl/events/EventDispatcher.hx line 178
Called from haxe/ui/backend/TimerImpl.hx line 16
Called from haxe/ui/util/Timer.hx line 10
Called from haxe/ui/validation/ValidationManager.hx line 128
Called from haxe/ui/core/ComponentValidation.hx line 171
Called from haxe/ui/core/ComponentValidation.hx line 236
Called from haxe/ui/core/Component.hx line 1694
Called from haxe/ui/core/Component.hx line 1801
Called from haxe/ui/core/Component.hx line 1896
Called from haxe/ui/styles/animation/Animation.hx line 174
Called from haxe/ui/styles/animation/Animation.hx line 289
Called from haxe/ui/styles/animation/KeyFrame.hx line 43
Called from haxe/ui/styles/animation/util/Actuator.hx line 78
Called from haxe/ui/styles/animation/util/Actuator.hx line 137
Uncaught exception - Invalid field access : index

**Comment by ianharrigan** [comment]
Interesting, someone i think had an issue like this recently... what openfl target are you using? Neko by any chance? Does the same happen with git haxeui-core & haxeui-openfl?

Cheers,
Ian

**Comment by Sartoric** [comment]
Yep neko .. forgot to mention it 😄

**Comment by Sartoric** [comment]
@ianharrigan 
Same using  git version

**Comment by ianharrigan** [comment]
Ok, can you try that again with haxeui-core git

(ive also tweaked the pill style a little bit as it was looking weird)

Cheers,
Ian

**Comment by Sartoric** [comment]
> Ok, can you try that again with haxeui-core git
> 

👍  Working now

> (ive also tweaked the pill style a little bit as it was looking weird)
> 
Yep ... it looked more like a suppository than a pill 😄
