### ISSUE TITLE
Constant as parameter for ComponentMacros.buildComponent() doesn't work

### ISSUE THREAD

**Issue by Sartoric** [haxeui/haxeui-core#385]
I'm trying to use a constant as parameter for buildComponent

`public static inline final XMLPATH:String = 'file.xml';`
`this.widget = ComponentMacros.buildComponent(XMLPATH);`

## Expected Behavior
I would expect (as it's inline ) to work. 

## Current Behavior

But it looks like compiler doesn't like it 

` haxe.macro.Expr should be String For function argument 'filePath'`

## Possible Solution
Maybe it has something to do with macros ? 

`$type(XMLPATH);` confirm it's a String

**Comment by Apprentice-Alchemist** [comment]
The macro expects a constant string, and you give it an expression. And since the expression passed to the macro isn't typed yet, the compiler hasn't replaced `XMLPATH` with `file.xml` yet.

So this is not a bug, but expected behaviour.
