### ISSUE TITLE
strange binding behavior

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-core#388]
See the example code here: https://github.com/sh-dave/haxeui-kha-testsuite/blob/master/src/externalXmlBindings/Main.hx

## Expected Behavior

- it's a simple `[-] 0 [+]` component test
  - `-` decreases the counter value
  - `+` increases the counter value).

The counter should update properly.

## Current Behavior

- If you click on `+` first, it will append a 1 every time you click it instead of incrementing `counter`. (i guess it's typed as a string)
  -  `01` -> `011` -> `0111` ...
- If you click on `-` first, it will correctly decrement and display `-1`, and if you then click `+` it will correctly increment and display the counter

## Possible Solution

Even though i typed the counter variable as `Int` i guess it gets typed as `String` under some circumstance.

## Steps to Reproduce (for bugs)
1. Clone the [haxeui-kha-testsuite](https://github.com/sh-dave/haxeui-kha-testsuite) and open  in vscode with the Kha Extension Pack installed
2. Edit the khafile.js and uncomment the line `// suite.addParameter('--main externalXmlBindings.Main');` to pull in the proper Main function, comment out any other that might be active.

## Context
Just playing around for now

## Your Environment
* Version used: haxeui-core @ 35db371, haxeui-kha @ 9359c59, Kha @ 7688d65
  - all are linked as submodule in the repo
* Environment name and version (e.g. Chrome 39, node.js 5.4): debug-html5 build
* Operating System and version (desktop or mobile): Linux + Windows Desktop
* Link to your project: https://github.com/sh-dave/haxeui-kha-testsuite

**Comment by ianharrigan** [comment]
Hmmm, so yeah, there is no conversion process (i dont think) that is happening with the binding. Ie, even thought its typed as an int, the value of the textbox.text is a string... if im honest, im a little surprised it compiles at all! And also, the fact it _does_ decrement correctly is strange... Il check it out.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Ok, so i think thats fixed now. Lemme know if that works for you now, and if you are happy could you close this?

Cheers,
Ian

PS: thanks for the isolated test case, makes looking at bugs sooooooo much easier! :)

**Comment by sh-dave** [comment]
Incrementing is fixed it seems, but now it will throw an exception in Variant.toInt() when trying to decrement the value from `-1` to `-2` and that worked before. Btw, i would also be fine with it not compiling at all, it's just that the current behavior seems unintuitive  / error prone.

**Comment by ianharrigan** [comment]
Hmm, ill check it out... 

>  i would also be fine with it not compiling at all, it's just that the current behavior seems unintuitive / error prone.
Agreed, and haxeui's Variant should be able to handle this type of stuff, seems like there is a bug in there, which is good to find. Also, removed some reflection here to which is ideal.

**Comment by ianharrigan** [comment]
Ok, this should work correctly now, there was indeed a bug in Variant wrt to negative number :o

**Comment by sh-dave** [comment]
Yes, looking good now.
