### ISSUE TITLE
Scrollview children width has issue?

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#39]
When adding a Child with 100% width to  a scroll view the child will get  a width of 0

## Expected Behavior
I would expect the child to get the content width of the scroll view this would be either
1. the width of the scrollview itself
or 
2 the width of the widest child content of the scroll view

## Test app / minimal test case
[ScrollViewTest.zip](https://github.com/haxeui/haxeui-core/files/523149/ScrollViewTest.zip)

**Comment by ianharrigan** [comment]
This specific case can be fixed by adding the following:

```xml
<style>
    .scrollview .scrollview-contents {
        width: 100%;
    }
</style>
```

However, i dont want to add that to the default styles as you may want horizontally scrolling scrollviews also... im working on a test app that reproduces these issues and will attach it shortly

**Comment by ianharrigan** [comment]
So without using css it causes issues, attached is a test app where the bottom row should match the top row (which has the css fix) in order for this to be closed. 

[ScrollVIewIssue.zip](https://github.com/haxeui/haxeui-core/files/523227/ScrollVIewIssue.zip)

**Comment by ianharrigan** [comment]
one possible solution would be to create two new properties on `ScrollView`, `contentWidth` and `contentHeight`, so then for example you could do:

```xml
<hbox width="100%">
    <scrollview width="50%" contentWidth="100%">
      ...
    </scrollview>
    <scrollview width="50%">
      ...
    </scrollview>
</hbox>
```

But not sure if this is too verbose

**Comment by hoseyjoe** [comment]
I ok with contentWidth

**Comment by ianharrigan** [comment]
Im not a huge fan of `contentWidth` but not sure there is a better different alternative other than css (or this property).

The other option is that you must explicitly specify a container, for example:

```xml
<scrollview width="50%">
    <vbox width="100%">
        ...
    </vbox>
</scrollview>
```

But i dropped this as i thought it was causing confusion with how to use `ScrollView` - maybe its a better method after all... ... ...

**Comment by ianharrigan** [comment]
OK, ive added the the new `contentWidth` and `contentHeight` properties (in xml they can be either % or explicit px units), this is the test app on my system: 

![image](https://cloud.githubusercontent.com/assets/3024242/19705674/1e53bf92-9b0e-11e6-962f-71b5e379ca2f.png)

(bottom row looks fine now)

Updated test app is:

```xml
<vbox id="main" width="100%" height="100%" style="padding:10px;">
    <style>
        #scroll1 .scrollview-contents {
            width: 100%;
        }
        
        #scroll2 .scrollview-contents {
            height: 100%;
        }
    </style>
    <hbox width="100%" height="50%">
        <scrollview id="scroll1" width="50%" height="100%">
            <button text="Button 1" width="100%" />
            <button text="Button 2" width="100%" />
            <button text="Button 3" width="100%" />
            <button text="Button 4" width="100%" />
            <button text="Button 5" width="100%" />
            <button text="Button 6" width="100%" />
            <button text="Button 7" width="100%" />
            <button text="Button 8" width="100%" />
            <button text="Button 9" width="100%" />
            <button text="Button 10" width="100%" />
        </scrollview>
        <scrollview id="scroll2" width="50%" height="100%" layout="horizontal">
            <button text="Button 1" height="100%" />
            <button text="Button 2" height="100%" />
            <button text="Button 3" height="100%" />
            <button text="Button 4" height="100%" />
            <button text="Button 5" height="100%" />
            <button text="Button 6" height="100%" />
            <button text="Button 7" height="100%" />
            <button text="Button 8" height="100%" />
            <button text="Button 9" height="100%" />
            <button text="Button 10" height="100%" />
        </scrollview>
    </hbox>
    
    <hbox width="100%" height="50%">
        <scrollview width="50%" height="100%" contentWidth="100%">
            <button text="Button 1" width="100%" />
            <button text="Button 2" width="100%" />
            <button text="Button 3" width="100%" />
            <button text="Button 4" width="100%" />
            <button text="Button 5" width="100%" />
            <button text="Button 6" width="100%" />
            <button text="Button 7" width="100%" />
            <button text="Button 8" width="100%" />
            <button text="Button 9" width="100%" />
            <button text="Button 10" width="100%" />
        </scrollview>
        <scrollview width="50%" height="100%" layout="horizontal" contentHeight="100%">
            <button text="Button 1" height="100%" />
            <button text="Button 2" height="100%" />
            <button text="Button 3" height="100%" />
            <button text="Button 4" height="100%" />
            <button text="Button 5" height="100%" />
            <button text="Button 6" height="100%" />
            <button text="Button 7" height="100%" />
            <button text="Button 8" height="100%" />
            <button text="Button 9" height="100%" />
            <button text="Button 10" height="100%" />
        </scrollview>
    </hbox>
</vbox>
```

Let me know if it works and this can be closed. 

Cheers,
Ian

**Comment by hoseyjoe** [comment]
I compiled the project I originally attached. the scrollview has a width=100% and a button is added with width=100 .  It does not appear correct.  adding contentWidth=100% in the scrollview makes it appear correctly.  You may want to rethink whether we can asume contentWidth to be 100% if not spcified.

Having said that it works for me

**Comment by ianharrigan** [comment]
The problem with making a "decision" about always making contentWidth=100% default is a few things:

* Should create a 100% scrollview (with a horizontal scrollbar) and a 2000px button inside:
```xml
<scrollview width="100%">
    <button width="2000" />
</scrollview>
```

* Should create a scrollview horizontally aligned components of 100% height:
```xml
<scrollview layout="horizontal" contentHeight="100%">
    <button height="100%" />
    ...
    <button height="100%" />
</scrollview>
```

**Comment by hoseyjoe** [comment]
Your right. I got nothing

**Comment by ianharrigan** [comment]
It can always become a seperate issue if it proves to be a constant issue, or someone comes up with a bright idea.

**Comment by ianharrigan** [comment]
although, i have to admit, in my brain im kinda going back to how it WAS, ie, the first child is the container, and you have direct control over it, eg:

```xml
<scrollview>
    <image width="1000" height="1000" />
</scrollview>
```

or

```xml
<scrollview>
    <vbox width="100%">
        ...
    </vbox>
</scrollview>
```

or

```xml
<scrollview>
    <hbox height="100%">
        ...
    </hbox>
</scrollview>
```

Its more verbose (especially from just code, but that could possibly be mitigated by "auto adding" a `Box` if one doesnt exist)
