### ISSUE TITLE
-D hscriptPos

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#394]
When you use -D hscriptPos,   haxeui doesn't work anymore.

`haxeui-core/haxe/ui/binding/BindingManager.hx:382: characters 18-34 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:386: characters 18-51 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:386: characters 25-41 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:388: characters 18-62 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:388: characters 25-58 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:388: characters 32-48 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:390: characters 18-34 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:392: characters 18-35 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:395: characters 18-32 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:397: characters 18-36 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:401: characters 18-27 : hscript.ExprDef should be hscript.Expr
haxeui-core/haxe/ui/binding/BindingManager.hx:390: lines 390-391 : Incompatible pattern
`

**Comment by ianharrigan** [comment]
Interesting, thanks. : )

**Comment by ianharrigan** [comment]
This should be fixed now... reminds me how important it is to remove the hscript dependency... 

Cheers,
Ian

**Comment by ianharrigan** [comment]
Im going to close this as there is no hscript in haxeui now by default
