### ISSUE TITLE
CRITICAL: TextField broken on latest git

### ISSUE THREAD

**Issue by Gulvan0** [haxeui/haxeui-core#397]
## Current Behavior
Text input is impossible (more specifically, it is impossible to focus the TextField).

## Test app / minimal test case
```
package;

import haxe.ui.Toolkit;
import haxe.ui.components.TextField;
import openfl.display.Sprite;

class Main extends Sprite
{

    public function new()
    {
        super();
        Toolkit.init();
        var t:TextField = new TextField();
        addChild(t);
    }
}
```

## Your Environment
* Lib version: latest git
* Haxe version: 4.2.2
* Target: html5
* Environment name and version (e.g. Chrome 39, node.js 5.4): latest Chrome & Opera
* Operating System and version (desktop or mobile): Desktop web

**Comment by ianharrigan** [comment]
OK, i can reproduce, it seems something is swallowing mouse downs... still investigating.

**Comment by ianharrigan** [comment]
OK, that should be fixed now... Im not really sure its a "fix" really, more of a workaround as nothing has really changed in haxeui around this area i dont think, and it suddenly started eating mouseDowns, which makes me think something in openfl has changed (though i couldnt see anything obvious)... ill check with each release as they come out and see if this is still needed. 

For now, if that works can you close if happy?

Cheers,
Ian

**Comment by Gulvan0** [comment]
Great, thank you for your work!
