### ISSUE TITLE
Style's @:structInit is broken since the constructor was added

### ISSUE THREAD

**Issue by Gulvan0** [haxeui/haxeui-core#398]
## Expected Behavior
Compile successfully

## Current Behavior
Compile-time error: { fontSize : Int } has extra field fontSize

## Test app / minimal test case
```
package;

import haxe.ui.styles.Style;
import haxe.ui.Toolkit;
import openfl.display.Sprite;

class Main extends Sprite
{

    public function new()
    {
        super();
        Toolkit.init();
        var style:Style = {fontSize: 14};
    }
}
```

## Your Environment

* Version used: latest git
* Target: html5

**Comment by ianharrigan** [comment]
What version of haxe are you on?

**Comment by Gulvan0** [comment]
> What version of haxe are you on?

Latest git, as specified in the environment section

**Comment by ianharrigan** [comment]
This should be fixed now, if you are happy can you close when you get a moment?

Cheers,
Ian

**Comment by Gulvan0** [comment]
Awesome, thanks for the efforts!
