### ISSUE TITLE
Components never receive UIEvent.DESTROY

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-core#401]
```
class MyComponent extends Box {
        public function new() {
                super();
                registerEvent(UIEvent.DESTROY, function( e ) {
			trace('cleaning up');
		});
        }
}
```

## Expected Behavior
The event should be received after removing (and in turn destroying) it from it's parent.

## Current Behavior
The event is never received.

## Possible Solution
I think it's related to the following code in `Component.removeComponentAt()`. The event listeners are unregistered before the component is destroyed. Simply swapping the call order them might fix it? And it looks like the same code should be changed in `Component.removeComponent()`.

```
    public override function removeComponentAt(index:Int, dispose:Bool = true, invalidate:Bool = true):Component {
...
            if (dispose == true) {
                child._isDisposed = true;
                child.unregisterEvents();
                child.destroyComponent();
            }
...
```

## Your Environment
* Version used: https://github.com/haxeui/haxeui-core/commit/e076dee64c5d987291e1edec55193664cc515545

**Comment by ianharrigan** [comment]
Yeah, i think thats valid - feels like an oversight. Ive fixed this in haxeui-core git now... if that fixes it, can you close please?

Cheers,
Ian

**Comment by sh-dave** [comment]
Looks like this issue got reintroduced in b3c9517d34dafb530f436288a344b144521a79b6

**Comment by ianharrigan** [comment]
doh!

**Comment by ianharrigan** [comment]
Actually, i dont think that is the case: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/core/Component.hx#L466-L471

The order looks correct / the same there, no?

**Comment by sh-dave** [comment]
Yes that's ok, but for removeComponentAt() it isn't working any more: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/core/Component.hx#L506-L517

**Comment by ianharrigan** [comment]
Can you pull latest and try again please? Should be fixed. 

Cheers,
Ian
