### ISSUE TITLE
Table contents dont wrap ion some targets

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#405]
Broken (text doesnt wrap in columns):  
Raylib:  
![image](https://user-images.githubusercontent.com/2074385/131441190-3f26d3d2-d6ec-4520-bc9c-7fe08a2208e7.png)
Heaps: similar to raylib has issue currently but  
https://github.com/haxeui/haxeui-heaps/issues/29

Working  
html5:
![image](https://user-images.githubusercontent.com/2074385/131441160-de2bfb11-a47b-40fa-abb3-fd758da33e4a.png)

Project: [Simplified.zip](https://github.com/haxeui/haxeui-core/files/7081158/Simplified.zip)

**Comment by hoseyjoe** [comment]
The text wraps when there are spaces so the issue appears to be word-break wrapping in non html targets

**Comment by ianharrigan** [comment]
Hmmmm - yeah, although clipping every label could be _very_ expensive. It would be nicer if it "just worked" :(

**Comment by hoseyjoe** [comment]
Image from newest git
![image](https://user-images.githubusercontent.com/2074385/132046041-cd55dc89-1954-4022-bf4b-cd59e0e4ae41.png)

**Comment by hoseyjoe** [comment]
[Simplified.zip](https://github.com/haxeui/haxeui-core/files/7107671/Simplified.zip)

**Comment by ianharrigan** [comment]
Should be working now
