### ISSUE TITLE
bug: Tooltips not rendering properly

### ISSUE THREAD

**Issue by radiatoryang** [haxeui/haxeui-core#408]
Recent commit "use styles for basic item renderer" https://github.com/haxeui/haxeui-core/commit/c8fa98c51f4e82a9a3174b992066858b4d1282fe seems to have affected tooltip rendering... at least for me on Heaps + HashLink.

Correct tooltip with commit https://github.com/haxeui/haxeui-core/commit/e47a3a10c4ed0fff699d55706d4dd5e227f527c8 (the commit right before)
![image](https://user-images.githubusercontent.com/2285943/132160436-cdcddd79-968d-4724-a69c-9e97608696f3.png)

(mouse cursor isn't pictured on the screenshot, but it's in the center of the screen)

Wrong tooltips with commit https://github.com/haxeui/haxeui-core/commit/c8fa98c51f4e82a9a3174b992066858b4d1282fe
![image](https://user-images.githubusercontent.com/2285943/132160702-da3257e2-74af-4c00-985e-a6eef648e49f.png)

Was also able to reproduce this in a simple Heaps Hashlink test app
![image](https://user-images.githubusercontent.com/2285943/132161487-36e0747a-9a0f-44e4-8c80-c9eb986b1b29.png)

I don't have any styles or modifications to tooltips. Just using standard dark theme tooltips on buttons. Seems like tooltips depended on that percentWidth setting for some reason.

Not sure if the fix is to change how haxeui-heaps is rendering tooltips? Or if carving out a special case for .tooltip in haxeui-core is better? But I've filed the bug on this repo since it seems directly related to a haxeui-core commit.

**Comment by ianharrigan** [comment]
Oh, nice one... thanks - ill check it out.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Nice catch... i was setting the wrong thing to 100%... 

Should be fixed in latest now

Cheers,
Ian

**Comment by radiatoryang** [comment]
tooltips working in my project again! thanks for the speedy fix
