### ISSUE TITLE
Component childs get's removed randomly

### ISSUE THREAD

**Issue by AdrianV** [haxeui/haxeui-core#412]
I am trying out haxeui from git head - html5. In many components I have the situation when something changes, that the content (childs) of the outer component gets removed:

- when I click on a dropdown the second time it is empty
- when I have a TableView (virtual on)and filter the dataSource the content gets removed when the row count is less than the possible visible rows (before the filter, the row-count was higher than the visible rows)
- ...

## Steps to Reproduce (for bugs)
bug.xml
```xml
<vbox>
    <dropdown text="Select Date" type="date" />
</vbox>
```
```haxe
class Bug {

    static function main() {
		Toolkit.init();
		var main = ComponentMacros.buildComponent("assets/ui/bug.xml");
		Screen.instance.addComponent(main);        
    }
}
```
## Media

![Peek 2021-09-15 16-45](https://user-images.githubusercontent.com/1785852/133457642-336faa2c-9129-4da5-bab8-671aee544678.gif)

## Your Environment
* Version used: git head, haxeui-html5
* Environment name and version (e.g. Chrome 39, node.js 5.4): firefox, chrome
* Operating System and version (desktop or mobile): linux, windows

**Comment by hoseyjoe** [comment]
I believe this is related to #409 and requires a similar fix like pull request #411

**Comment by AdrianV** [comment]
yes - it looks like that many components are affected from the changes in removeComponent

**Comment by AdrianV** [comment]
maybe the default should be `false` and not `true` ?

**Comment by AdrianV** [comment]
no - that's not enough :)

**Comment by ianharrigan** [comment]
hmmm... so yeah, i recently changed components being removed from the screen to be able to be disposed, so i guess thats what causing the issue. Im a little surprised changing the default didnt fix it.

**Comment by hoseyjoe** [comment]
Since the does the same thing ,essentially, as pull request changing the default does fix #409

**Comment by ianharrigan** [comment]
Yeah, i can see whats going on... once fix is committed, but there are other things - bear with me :)

**Comment by AdrianV** [comment]
Hi Ian, seems to work now for me. Many thanks.
