### ISSUE TITLE
Components (dropdowns at least) and icons

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#417]
The dropdown icon is left aligned when beginning its life in a hidden component. Click the button to show().
![image](https://user-images.githubusercontent.com/2074385/135354119-d03fb436-1101-4cb8-acdd-4accac4e7a92.png)
[dropdown.zip](https://github.com/haxeui/haxeui-core/files/7255257/dropdown.zip)

**Comment by ianharrigan** [comment]
Hmmm - i thought i had fixed this actually, i presume you are on latest (git) everything?

**Comment by hoseyjoe** [comment]
yep git versioned. sha-1 941ff025aa403e2e7f6086030a67d602c07e8028, fix for issue 401

**Comment by ianharrigan** [comment]
OK, that should be fixed now.

**Comment by hoseyjoe** [comment]
fixed and in raylib
