### ISSUE TITLE
Redefinition of variable name in subclass is not allowed. Previously declared at h2d.Object

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#421]
I have a table with column 

```<column id="name" text="jimminy" width="34%" sortable="true"/>```

When compiling for heaps I get:  
``` 
Redefinition of variable name in subclass is not allowed. Previously declared at h2d.Object
```

Changing column id to ```<column id="name2"``` fixes the issue.

I dont know if you want to call it a issue or not

**Comment by ianharrigan** [comment]
Unfortunately there isnt a huge amount i can do about it. Using that xml above haxeui tries to create a "name" member variable in your class - in haxeui heaps that component eventually extends h2d.Object, which already has a name property. Same would happen in openfl if you use some property that already exists in Sprite.
