### ISSUE TITLE
Enable/disable state??

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#44]
Hi!
## Expected Behavior

I don't know if it is a missing feature, a design decision or I'm missing something.
The `enable` or `disable` state in some components (like Buttons, CheckBox, TextField...) are useful. HaxeUI v1 had this property.
## Current Behavior

Not implemented.
## Context

For example, i want to disable buttons (with the `disabled` state selector in css).

**Comment by ianharrigan** [comment]
This currently doesnt exist at all in haxeui2... :(

Its something that should be added of course, the css state is easy, other parts (like mouse events, focus, etc) not so much.

**Comment by ianharrigan** [comment]
as, rather ugly, work around (visually) you could always define new css psuedo classes and add them with at `myComponent.addClass(":disabled")`, but again, that will have no effect on actual interaction.

**Comment by aW4KeNiNG** [comment]
Ok, perfect.

I will use the work around for now, thanks.

**Comment by hoseyjoe** [comment]
I was going to add a "disabled" property to the Button but maybe the property should be on InteractiveComponent. Which opens a lot of potential for other components. I will use workaround as well.

**Comment by ianharrigan** [comment]
I agree that this should go on InteractiveComponent. The css should be relatively straight forward. As mentioned above, simply a ":disabled" - will be a bit of a pain retrospectively going through all current components and styling them, but oh well - better now than later. 

It worth keeping in mind that this also needs to effectively "shut down" certain events in the event map (namely mouse and keyboard events), my thoughts would be to add a `.freeze` and `unfreeze` functions here: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/util/EventMap.hx that would take care of that. 

I also guess there will need to be another backend function `handleDisabled(disabled:Bool)` (for native backends primarily) which means each backend will need an update or fail compilation. @haxeui/haxeui-collaborators - just a heads up...

**Comment by ianharrigan** [comment]
Actually, scratch that... disabled should use the behaviour system - sorry, wasnt thinking.

**Comment by hoseyjoe** [comment]
why ":disabled" vs "disabled"?

**Comment by ianharrigan** [comment]
i mean a css pseudo class, something like: 

```css
button {
    ...
}

button:hover {
    ...
}

button:down {
    ...
}

button:disabled {
    ...
}
```

```haxe
class InterativeComponent {
    public var enabled(get, set):Bool;
    private function set_enabled(value:Bool):Bool {
        behaviourSet("disabled", value);
        return value;
    }
}

class DefaultDisabledBehaviour {
    public override function set(value:Variant) {
        if (value == true) {
            _component.addClass(":disabled");
        } else {
            _component.removeClass(":disabled");
        }
    }
}
```

**Comment by ianharrigan** [comment]
one thing that needs to be checked (and probably changed) is how the default behaviours are setup, for example: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/components/Button.hx#L30-L36

If you did the same for InteractiveComponent then button would overwrite that behaviour. So we probably need a `registerBehaviour` or something similar so subclasses dont overwrite things.

**Comment by ianharrigan** [comment]
Ah, and another thing.. it should cascade down to all child components in composite components (ie, in `DefaultDisabledBehaviour`)... For example, if you have a listview and disable it, then everything in the listview should be disabled, including scrolls (which is itself 3 buttons)... doing `myScroll.disabled = true` would have no effect on the children (the buttons) in the example impl above.

**Comment by aW4KeNiNG** [comment]
The issue could be closed now with the new commits. It works for me :)

**Comment by ianharrigan** [comment]
+1
