### ISSUE TITLE
vbox not resizing on component removal

### ISSUE THREAD

**Issue by terefang** [haxeui/haxeui-core#441]
the project where this can be seen is at https://github.com/terefang/ftl-calculon

if components are dynamically added ("+" button) the vbox enlarges, 
but on removal ("-" button) the vbox does not resize. (see screenshot)

![image](https://user-images.githubusercontent.com/492154/162741912-00823747-c3d8-4195-8352-e7f25f2115a2.png)

if removeAllComponenets is called the vbox contracts back again (using the "X" button)

## Environment

* haxeui-core + html5 1.4.0; haxe 4.2.3
* firefox 91.8 ESR
* chrome 100
* LinuxMint 19.x

**Comment by ianharrigan** [comment]
Something very weird happening there. I can repro the issue, but also, it seems after a while the vbox goes back to its normal size. Ill check it out a little deeper.

**Comment by ianharrigan** [comment]
OK, so there are a couple of issues:

You are removing the child from the wrong parent:
```haxe
paths.addComponent(new FtlDurationLYItem(this));
```
then later:
```haxe
_parent.removeComponent(this);
```
but `_parent` is set to `this` not `paths` which is where it was added, so it should be:
```haxe
paths.addComponent(new FtlDurationLYItem(paths));
```
An easier way would be just to use the `parentComponent` property:
```haxe
parentComponent.removeComponent(this);
```
Also, in your dropdown handler you had:
```haxe
    @:bind(calc_Selector, UIEvent.PROPERTY_CHANGE)
    private function onSelChange(e:UIEvent)
```
This is the wrong event type, it should be `UIEvent.CHANGE`, `UIEvent.PROPERTY_CHANGE` is used when other properties change, like text, etc. So you get weird results where it recreates the UI for "no reason"

All that said and done, i do think there is a bug in core, where it the child isnt a child of the component and you try and remove it, it _still_ destroys and removes it, which it should. It should warn you and return, so ill fix that shortly.

Let me know if that helps / makes sense.

Cheers,
Ian

**Comment by ianharrigan** [comment]
OK, i added a warning to core now, so in the future:

a) it WILL not destroy the child if its not a child of the component (doh!)
b) it will trace out a warning: `WARNING: trying to remove a child that is not a child of this component`

If you are happy with the above (and the explanation also makes sense), can you close this? Nice find though! thanks!

Cheers,
Ian

**Comment by terefang** [comment]
many thanks for pointing that out

also many thanks for writing haxeui in the first place.

i am only a couple of hours into both haxe and ui and have been very productive so far

**Comment by terefang** [comment]
thank you very much
