### ISSUE TITLE
Table Header height

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#442]
a table header with text that wraps causes a weird space issue.

![image](https://user-images.githubusercontent.com/2074385/163474681-fab55b3d-8563-4845-b671-8873a420bcd9.png)

If you change  
haxe\ui\containers\Header.hx to include  
|| child.height < max  
on line 77 so it is  
if (child.text == null || child.text.length == 0 || child.height < max) {

Now it looks like  
![image](https://user-images.githubusercontent.com/2074385/163475415-4c552388-9965-4af7-b2b3-53b8ba693b9e.png)

When none wrap  
![image](https://user-images.githubusercontent.com/2074385/163476332-ea1d6357-cd53-4a24-8530-6301430dafc6.png)

**Comment by hoseyjoe** [comment]
Also weird 2 pixel scroll?
[tabletest.zip](https://github.com/haxeui/haxeui-core/files/8492240/tabletest.zip)

**Comment by ianharrigan** [comment]
Perfect, thanks Joe - i used your fix, seems to work great. 

![image](https://user-images.githubusercontent.com/3024242/163480979-c267a551-e4a5-4fed-af25-3c9a7dfb9b4e.png)

Cheers,
Ian

PS: ive also fixed the incorrect scroll with autosized tables
