### ISSUE TITLE
Table Weirdness - ItemRenderer extends box

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#450]
We created a button item renderer that extends ItemRenderer. It causes weird layout issues.  The fix was to change the item renderer to first add an hbox then add a button as child of the hbox.

Should we be able to do that? Should anything that extends ItemRenderer have a container?

![tableweirdness](https://user-images.githubusercontent.com/2074385/164564736-acfc9142-c551-4032-beeb-c0ca12d7bc30.gif)

[TableViewRendererWeirdness.zip](https://github.com/haxeui/haxeui-core/files/8535569/TableViewRendererWeirdness.zip)

**Comment by ianharrigan** [comment]
This project doesnt seem to compile by the way, got a few problems with it, when i tried to clear them up, i got a bunch of other issues. Did you upload the wrong project / wrong version? 

Cheers,
Ian

**Comment by hoseyjoe** [comment]
fixed everything I saw
