### ISSUE TITLE
Random startup crash on android

### ISSUE THREAD

**Issue by hypergeome** [haxeui/haxeui-core#452]
I have VBox panel that act as whole app GUI container call ContactAppContainer.
Inside that ContactApContainer onReady method, I new about 10 of other panels/forms which are all subclass of vbox and use xml file as template.

Sometimes, app crashes during those panel super() call. which parent is Vbox.
Sometimes, app crashes after done creating some panels.
The crashes are random, but all are when creating the panels/forms.

## Expected Behavior
App startup not crashing.

## Current Behavior
App randomly crash during startup and GUI initialization.

## Possible Solution
I think haxeui-core use some timers and code in them have issue that cause crash.

## Steps to Reproduce (for bugs)

Not sure if I can simplify the app and give you. Will try.

1.
2.
3.
4.

## Your Environment
actuate: [1.8.9]
air4haxe: [1.0.0]
akifox-asynchttp: [0.4.7]
box2d: [1.2.3]
haxe-crypto: [0.0.7]
haxeui-core: 1.2.3 [1.4.0]
haxeui-openfl: 1.2.3 [1.4.0] git
haxeui: [1.8.21]
hscript: [2.4.0]
hxcpp-debug-server: [dev:c:\Users\Subin\.vscode\extensions\vshaxe.hxcpp-debugger-1.2.4\hxcpp-debug-server]
hxcpp: [4.2.1]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [7.9.0]
msignal: [1.2.5]
openfl-samples: [8.7.0]
openfl: [9.1.0]
thx.core: [0.44.0]
thx.promise: [0.7.0]

HAXE 4.0.5
haxeui-core 1.4.0
haxeui-openfl 1.4.0

compile using android ndk r15

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ianharrigan** [comment]
Do you have a minimal test app? Its going to be hard (and time consuming) for me to try and recreate what you described in words in code. Also, i notice you are using haxeui 1.4.0, any chance you could upgrade to git versions (both haxeui-core and haxeui-openfl) and try again?

Also, if it the problem does persist, is there a stack trace or any additional information?

> I think haxeui-core use some timers and code in them have issue that cause crash.

haxeui-openfl uses ENTER_FRAME in its validation sequence, not timers. 

Additional info and / or a test app (and confirmation that i happens in git) would be useful.

Cheers,
Ian

**Comment by hypergeome** [comment]
Trying to build a simplified version of app that show the issue

**Comment by ianharrigan** [comment]
Great, thanks!

**Comment by ianharrigan** [comment]
So after a little bit of playing with the test app, your problem seems to be thread usage. I seems you have some type of race condition, if i take the app "as is" it crashes about 50% of the time - if i remove the:

`public var coreThread:CoreThread = new CoreThread();`
and
`coreThread.coreLoadNode();`

Then i cant get it crash at all - so my advice would be to review your usage of your threading system, there is certainly something going wrong there it seems. Note if i run the app in debug mode, even the "vanilla" version then it also never seems to crash, further indicating this is a race condition in your thread system. 

Cheers,
Ian

**Comment by hypergeome** [comment]
It is weird. That is just a thread that in your sample app now does nothing. But I will move that new CoreThread part to after done creating all panels then. Thanks.

**Comment by hypergeome** [comment]
So, on my app, I commented out the CoreThread new. Still crash. It must be something else.

**Comment by hypergeome** [comment]
Ok, I will build another sample app for you as much as like mine right now and no CoreThread and for you to easier to see it crashes.

**Comment by hypergeome** [comment]
Got it. My thread loop had issue.

**Comment by ianharrigan** [comment]
Great! Glad you managed to track it down (and quickly!)... threading issues can sometimes be a real pain to rectify... congrats!

Cheers,
Ian

**Comment by hypergeome** [comment]
Thank you.

**Comment by hypergeome** [comment]
BTW,
by the sample I gave you, I found out this, just FYI:

so, if you code it like this

var myThread = Thread.createWithEventLoop(THREAD_FUNC);
...
function THREAD_FUNC():Void{
     myThread.something; //THis may cause null pointer exception
}

Instead, do this
Thread.createWithEventLoop(THREAD_FUNC);
...
function THREAD_FUNC():Void{
    var myThread = Thread.current();
    myThread.something; //THis is fine
}

My guess is that cpp thread may fall into THREAD_FUNC before the call to  Thread.createWithEventLoop returns.
