### ISSUE TITLE
DropDown behaviour with custom renderer

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#455]
I was setting the index of a dropdown during pageload in html app.  It would get my set index to 5 and then reset it to 0.

Turns out it was being reset by the onReady call of the dropdown component
```
public override function onReady() {
	super.onReady();
	if (_dropdown.text == null ) {
		handler.applyDefault();
	}
}
```
Since my drop down renderer is custom I dont have a _dropdown.text(?) so it would apply defaults thus changing index to 0 and causing my issue.

Is there a way for me to know when the dropdown is ready without override-ing the onReady call?

Alternatively I worked around it by changing the dropdown onReady to
```
public override function onReady() {
	super.onReady();
	if (_dropdown.text == null && _dropdown.selectedIndex == null) {
		handler.applyDefault();
	}
}
```

**Comment by hoseyjoe** [comment]
With the attached project you will notice line 36 doesnt change the selected index  
[Haxeui.zip](https://github.com/haxeui/haxeui-core/files/8934618/Haxeui.zip)

**Comment by hoseyjoe** [comment]
Another option, I think, is to check for itemrenderer. as there is no default for a custom renderer. 
```
public override function onReady() {
	super.onReady();
	if (_dropdown.text == null && _dropdown.findComponent(ItemRenderer) == null) {
		handler.applyDefault();
	}
}
```

**Comment by ianharrigan** [comment]
This should be fixed now - can you close if it works for you (your test app seems fine now).

Cheers,
Ian
