### ISSUE TITLE
Allow right click selection on TreeViewNode or ListViewNode

### ISSUE THREAD

**Issue by inc0der** [haxeui/haxeui-core#457]
I'm not sure if there are other alternatives for my proposal, if there are please let me know in the comments and then we can just close this issue.

## Expected Behavior
When right clicking on a TreeViewNode or ListViewNode it would be nice if it selected the node similar to a normal click.

## Current Behavior
Right clicking on a node currently does nothing, or opens the context menu depending on the backend used

## Possible Solution
Add a flag `allowRightClick` on the `TreeView` nad `ListView` node that if enabled when the component is initialized will register an event for right clicks similar to normal and double clicks.

## Test app / minimal test case
In the `TreeView.hx` we could simply add a flag variable to the class

```js
 public var allowRightClick: Bool = false;
```
Then in the `onInitialize` method of the `TreeViewNodeBuilder` adding a check like this would work.

```js
        if (treeview.allowRightClick) {
          _nodeContainer.registerEvent(MouseEvent.RIGHT_CLICK, onContainerClick);
        }
   ```
   
## Context
In many applications a tree or list component allows selection via right click, and in my specific case I do need this behavior for my map editor I'm building.

If this is something you'd like implemented I will make a PR, just let me know.

**Comment by ianharrigan** [comment]
Im back from honeymoon now, so will take a look at this, right click should already be possible (at least for treeview), but ill have to remind myself how it works. Leave it with me, ill check it out and get back to you.

Cheers,
Ian

**Comment by inc0der** [comment]
Appears to be working perfect 👌 Thanks for much for all you do.
