### ISSUE TITLE
<slider> component crashes when used

### ISSUE THREAD

**Issue by MasterEric** [haxeui/haxeui-core#478]
## Expected Behavior
When including the `<slider>` component in a layout, the application should include a slider as demonstrated in the Component Explorer.

## Current Behavior
When including the `<slider>` component in a layout, the application crashes with a Null Object Reference.

## Possible Solution
If the intent is to deprecate Slider and make HorizontalSlider and VerticalSlider the replacement, steps should be taken to update existing documentation and add an appropriate error message to reduce any confusion caused by this change,

## Steps to Reproduce (for bugs)
I was able to reproduce this bug by copying `<slider width="100%" majorTicks="10" minorTicks="5" pos="70" />` from the HaxeUI Component Explorer into one of my layouts.

## Test app / minimal test case
https://github.com/mastereric/haxeuitestbench

## Context
This issue occurred when attempting to copy the layout from the Menus example.

https://www.haxeui.org/explorer/#containers/menus

## Your Environment

* Version used: Issue occurs with release (1.4.0) and latest ([5b2e3d2](https://github.com/haxeui/haxeui-core/commit/5b2e3d2b02eb7c691ecae6d49638ff15222a45ff)) haxeui-core.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Tested with Flixel 4.11.0 and develop.
* Operating System and version (desktop or mobile): desktop

**Comment by ianharrigan** [comment]
Am i right in thinking this is fixed now?

**Comment by MasterEric** [comment]
I assume so, based on our previous conversation and [this commit](https://github.com/haxeui/haxeui-core/commit/84fbbb162bded8f4140f0d2f4e17427927b0cded).

**Comment by ianharrigan** [comment]
OK, cool - ill close this.
