### ISSUE TITLE
Proposal: Image ScaleMode property

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#48]
It would be useful a `scaleMode` property in the `Image` component.

Actually, you have `maintainAspectRatio` in the `ImageLayout` class, but it is private.
The `scaleMode` property can have the next values:

Example values:

```
Resource = 2000x2000
Image component = 200x100
```
- none -> the resource will be 1:1 inside of component. It maintains the aspect ratio. You will see only a partial piece of the resource. The resource will be the original size, 2000x2000.
- fill -> the image fills the component size. It doesn't maintain the aspect ratio. The resource will be scaled to 200x100.
- fit-inside -> It maintains the aspect ratio. The resource will be scaled to be visible completely, 100x100.
- fit-outside -> It maintains the aspect ratio. The resource will be scaled to fill the component completely, 200x200.
- fit-width -> It maintains the aspect ratio. The resource will be scaled to fill the component width completely, in our case 200x200.
- fit-height -> It maintains the aspect ratio. The resource will be scale to fill the component height completely, in our case 100x100.

Also, it could be interesting an `imageHorizontalAlign` property and `imageVerticalAlign` property, or something like that, to modify the resource align.

What do you think?

I can implemented it in a PR. You don't need to worry about that if you want :)

**Comment by ianharrigan** [comment]
Yeah, i like this, it seems more flexible that `maintainAspectRatio`
