### ISSUE TITLE
[BUG] MenuCheckBox.onChange does not fire.

### ISSUE THREAD

**Issue by MasterEric** [haxeui/haxeui-core#484]
I am having an issue where a basic MenuCheckBox with an `onChange(event:UIEvent)` callback does not fire when set.

## Expected Behavior
I am expecting that, upon clicking the MenuCheckBox and checking/unchecking it, the `onChange` function assigned to that component (if any) should fire.

## Current Behavior
An assigned callback does not fire. This issue does not occur with the standard CheckBox component.

## Possible Solution
I am not aware of the root cause of this issue.

## Steps to Reproduce (for bugs)
1. Create a UI with a MenuBar component, containing a Menu
2. Add a MenuCheckBox to that Menu
3. From code, retrieve the MenuCheckBox via its ID and assign a `onChange(event:UIEvent) -> Void` callback to the component. 
4. Run the application and attempt to click the check box.

Expected behavior is that the callback should run.
Actual behavior is that the callback does not run.

## Test app / minimal test case
I currently have a minimal reproduction available at https://github.com/MasterEric/HaxeUITestBench

## Your Environment
* Version used: I tested this on the Git master branch, `dea3e62`.
* Environment name and version (e.g. Chrome 39, node.js 5.4): Flixel `dev` branch
* Operating System and version (desktop or mobile): Tested on Windows 10 and Linux

**Comment by ianharrigan** [comment]
This should be fixed now (i also update MenuOptionBox since that is basically the same).

**Comment by MasterEric** [comment]
Looks like it works to me.
