### ISSUE TITLE
[Feature request] Add SortDirection  for  sortCustom dataSource

### ISSUE THREAD

**Issue by flashultra** [haxeui/haxeui-core#486]
At the moment it's not possible to use SortDirection ( ASCENDING / DESCENDING ) in a sortCustom function (DataSource type).
So if I need to sort a field in ascending and descending order, I will need to create two separate functions.

**Comment by ianharrigan** [comment]
Good catch, yeah, ill add it :)

**Comment by ianharrigan** [comment]
So actually, looking at this, im not sure its possible, the reason is that is ArrayDataSource sortCustom uses array.sort (haxe inbuilt) and that has a function signature of T->T->Int, and i cant change that, so im not sure how i would pass the "direction" parameter down to that function

**Comment by ianharrigan** [comment]
Actually, nvm - i think this should be fixed now in latest haxeui core... if this works for you can you close the issue please?

Cheers.
Ian

**Comment by flashultra** [comment]
Thank you Ian!
