### ISSUE TITLE
Rename haxe.ui.core.Compoent::clipRect to cropRect.

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-core#49]
Currently the haxeui `Component` has a `clipRect` property that defines a clipping rectangle, the type of which is a `haxe.ui.utils.Rectangle`. This however, clashes with HaxeFlixel as `FlxSprite` also defines this property (with a type of `FlxRect`) and the component inheritance would be such that:

```haxe
Component extends ComponentBase extends FlxSprite
```
(for a haxeui-flixel backend).

This obviously causes a conflict, the path of least resistance is to rename the property in haxeui-core to something that doesnt clash. Possibilities are:

* cropRect
* trimRect
* snipRect
* sliceRect
* cutRect

**Comment by ianharrigan** [comment]
Its probably also worth mentioning there is a `Bool` property `clip` which basically says "always clip this to its width / height", that would also change to one of the verbs, ie: 

* crop
* trim
* snip
* slice
* cut

Which i think rules out the last two.

**Comment by troyedwardsjr** [comment]
I think cropRect makes sense, as the word "crop" in this context will be immediately familiar to anyone who uses image editors (particularly from an Adobe background).

**Comment by ianharrigan** [comment]
I think i tend to agree... I prefer clip of course, but crop is a close second...

**Comment by ianharrigan** [comment]
i think `clipComponent` and `clipComponentRect` actually make the most sense.

**Comment by aW4KeNiNG** [comment]
`clipRectangle`?

**Comment by kevinresol** [comment]
`clipShape` / `clipArea`? In case one day you wish to support crop with arbitrary shapes?
