### ISSUE TITLE
Haxui-Heaps depracated calls to lineBreak: bool

### ISSUE THREAD

**Issue by Beq-BD** [haxeui/haxeui-core#497]
`lineBreak: Bool` doesn't seem to be a part of Heaps' api any longer, which causes problems trying to build anything with HaxeUI. 
## Expected Behavior

The project should just build so it can be run. It's a generated "Hello World" project from the tutorial/example.

Basically anything referring to "lineBreak" in HaxeUI+Heaps needs to be removed or corrected.
## Current Behavior

* all lines related to that lineBreak boolean value show up as errors when trying to build the HL bytecode.
* importing the Toolkit package and adding `Toolkit.init();` early also doesn't seem to change anything.

## Possible Solution

* I tried commenting out all those lines referencing lineBreak, which allowed it to build but the app's behaviour seems to suffer, as in the buttons do nothing when clicked, no button-down state when clicking and no messages related to the button show up in the app or terminal to reflect the example code. Also the Vbox doesn't seem to do anything either. Even with that, going a step further and trying to build an executable binary simply gives an error and fails.

* Only solution I can think of with my limited knowledge is updating the HaxeUI-Heaps backend to be compatible with the current Heaps-stable (non-git repo package) API and possibly rechecking the C -> exec-binary compilation issues if necessary.

## Steps to Reproduce (for bugs)

1. install dependencies
2. run `haxelib run haxeui-core create heaps` to create the project.
3. run ` haxe heaps-hl.hxml`
4.

## Media

![initial_error_messages](https://user-images.githubusercontent.com/119837993/205577446-7631027e-74ab-4f93-bb2a-f76b77613df5.png)

![c_comp_error](https://user-images.githubusercontent.com/119837993/205577753-577f7337-c8e4-4459-ad2a-4e845f6aeaba.png)

![run_attempt_after_edit](https://user-images.githubusercontent.com/119837993/205591351-52a44057-32d7-40de-97da-1d12444af16e.png)

## Context

I'm currently trying to learn game dev as well as tool and general app development. And since Haxe+Heaps+hashlink are so versatile in what platforms they can target and languages Haxe can interop with, I figured it'd be the ideal way to learn and practice of both, since Heaps' default UI system is really "extra" (IMsO) with the whole CSS aspect of it since most other UI solutions don't really need that, or rather, I'm simply not a fan of CSS since I never had any reason or will to go into webdev related things. Hence why something like HaxeUI+Heaps is somewhat crucial/preferred since it would technically solves the "write once run everywhere" issue if I ever become more proficient in the language and besides general app development it gives me the ability to mess with 2D and 3D graphics and audio from the get-go without having to pull in and hack solutions together from other backends/libraries or trying to figure out how building that kind of stuff almost from scratch with `Kha`. Other languages like python would force potential clients to install the interpreter or be an over bloated executable while not making it easy to port the same code to the web and constantly suffers from breaking changes due to updates to the language, same mostly goes for JVM languages and their build tools that seem to fail on the regular. Lost track of how many FOSS java projects I've tried that simply refused to build.

## Your Environment

* Version used: 1.5.0
* Environment name and version (e.g. Chrome 39, node.js 5.4): Haxe-4.2.5, Heaps-1.9.1, Hashlink-1.12, 
* Operating System and version (desktop or mobile): Linux- Arch (EndeavourOS)- Kernel: 6.0.11-zen1-1-zen
* Link to your project:
---
Apologies for my lack of knowledge/experience with this stuff. I legit made a github account just to see if posting this issue would help things along.

**Comment by Beq-BD** [comment]
I  realised I made a mistake about where I was posting the issue, I didn't know there were other repos for specific backends. Will close and repost in the proper place. Truly sorry. I'm new to this stuff.

**Comment by ianharrigan** [comment]
NP - i answered your other issue btw :)
