### ISSUE TITLE
Having the ui in the top folder prevent css inclusion

### ISSUE THREAD

**Issue by ibilon** [haxeui/haxeui-core#5]
## Expected Behavior

Should find the css file.

## Current Behavior

I'm getting the warning:
`haxeui-core/haxe/ui/parsers/ui/resolvers/FileResourceResolver.hx:28: WARNING: Could not find file: /main.css`

App still build but obviously style isn't applied.

## Possible Solution

Looks like a `/` is added by mistake.

Also having the ui and css stored in an `asset` folder fix things.

## Test app / minimal test case

[includeTest.tar.gz](https://github.com/haxeui/haxeui-core/files/376359/includeTest.tar.gz)

Can also change in the `main.xml` line 3 from `main.css` to `./main.css` or even `../test/main.css` ("test" being the name of my folder) without success.

## Your Environment

Latest git version, https://github.com/haxeui/haxeui-core/commit/12965ffef8900cd379ae63b2a2b9c30d96bfb48b

**Comment by ianharrigan** [comment]
Should be fixed now, can you retest and close if working?

Cheers.

**Comment by ibilon** [comment]
Fixed thanks.
