### ISSUE TITLE
TableView messes with layout and drops scrollbar 

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#51]
Same 4 box layout. I added a tableview to the topleft with 20 items.  Scrollbar does not appear for tableview.  Also if you resize there is space to the far right of the columns. See image.  Remove the table (xml and hx) and everything works.

![image](https://cloud.githubusercontent.com/assets/2074385/21027873/94490dbe-bd47-11e6-9f0c-c84cd13dace6.png)

Odd: Reduce to below 800 width and the scrollbar appears!  but it is small?
![image](https://cloud.githubusercontent.com/assets/2074385/21028127/9eb978c8-bd48-11e6-8339-a67cc89326da.png)

## Expected Behavior
Scrollbar should appear and squares should still work

## Test app / minimal test case
[ContinioiusTest.zip](https://github.com/haxeui/haxeui-core/files/640609/ContinioiusTest.zip)

## Your Environment
HTML5 and NME windows tested

**Comment by ianharrigan** [comment]
hmmm... cant reporoduce this, but it does happen in your test project, so something else is happening...

![image](https://cloud.githubusercontent.com/assets/3024242/24468894/0182da3a-14ba-11e7-82c5-6df1194834d6.png)

**Comment by hoseyjoe** [comment]
Seems to be worse.  Just recompiled it with newest.  I deleted th html in the browser which revealed a hidden 0 C.  Looks like thefirst row wasnt showing?  Also there is now padding between headers?
![image](https://user-images.githubusercontent.com/2074385/28732011-154eb1d0-738b-11e7-9c49-341b2acd8c03.png)

**Comment by hoseyjoe** [comment]
removed spacing in my example fixes the column...spacing

It is still disappearing sometimes.  It appears to be getting the width of its parent?  Ill try to get more information

**Comment by ianharrigan** [comment]
what backend is this btw? I dont see a scroll at all in haxeui-html. 

PS: ive fixed the spacing issue in the default theme

**Comment by ianharrigan** [comment]
to be honest, there is something pretty strange happening when you put a TableView in a ScrollView:

```xml
            <scrollview id="scroll" width="100%" height="100%" contentWidth="100%" >
				<tableview height="100%" width="100%" id="tableview">
                    <header style="height: auto;width:100%;">
                        <column id="colA" text="colA" style="width:33%" sortable="true" />
                        <column id="colB" text="colB" style="width:33%" sortable="true" />
                        <column id="colC" text="colC" style="width:34%" sortable="true" />
                    </header>
                </tableview>
            </scrollview>    
```

That doesnt display the table view, removing the outer scrollview makes it work fine.

**Comment by ianharrigan** [comment]
Ok, i think this is fixed now. Can you confirm and close if thats the case. Nice one.

Ian
