### ISSUE TITLE
Notification system breaks when closing a notification

### ISSUE THREAD

**Issue by luqyann** [haxeui/haxeui-core#510]
## Expected Behavior
Notifications open and close depending on their behavior at any time.

## Current Behavior
Notification system breaks when closing a notification, if you create several notifications at once.

## Steps to Reproduce (for bugs)
1. http://haxeui.org/explorer/#miscellaneous/notifications
2. Invoke multiple notifications.
3. Close one of them.

## Media
https://user-images.githubusercontent.com/18350226/218172907-37c6feae-f166-481b-9152-f972c84b10c9.mp4

https://user-images.githubusercontent.com/18350226/218175982-87c1e607-fb10-4d2a-b417-f909ef77fd64.mp4

## Your Environment
Win10 Firefox Dev. Ed. 110.0b9

**Comment by ianharrigan** [comment]
Oh, thats interesting, it only seemed to be when you use the custom notification?

**Comment by ianharrigan** [comment]
Actually, no, its not... gotcha

**Comment by ianharrigan** [comment]
Nope, happens locally, thanks!

**Comment by ianharrigan** [comment]
OK, this should be fixed now - ive also updated the component explorer (you might need to hard refresh to get the new version). If that works for you can you close the issue.

Thanks!
Ian

**Comment by luqyann** [comment]
Well, notifications can rarely stick (they can still be closed, but they don't disappear on a timer) if you close one of them quickly.

https://user-images.githubusercontent.com/18350226/221352361-76208016-c363-406a-a7ac-971fc51266af.mp4

**Comment by ianharrigan** [comment]
yup, you a right - still work to do... :/

**Comment by ianharrigan** [comment]
Alright, can you try again (new component explorer - might need to CTRL+F5 to clear your cache).

**Comment by luqyann** [comment]
One more thing, the notification cannot be closed while other notifications are fading out

https://user-images.githubusercontent.com/18350226/221354094-a0a0df94-21a9-428c-900a-0ae1f6c1b807.mp4

**Comment by ianharrigan** [comment]
Yeah, this is by design, there is a queue based system, so if you have 100 notifications "animating out" then new ones are added to the end (so will have to wait)... ill have a think about maybe having a priority based system, but for now i think having loads of notifications isnt really realistic anyway (and also not technically related to this issue)

Cheers,
Ian

**Comment by luqyann** [comment]
Ok thanks
