### ISSUE TITLE
Tooltips break after open sidebar

### ISSUE THREAD

**Issue by luqyann** [haxeui/haxeui-core#511]
## Steps to Reproduce (for bugs)
1. http://haxeui.org/builder/?28e898d2
2. Open sidebar

## Media
https://user-images.githubusercontent.com/18350226/218863118-9e5885e3-6866-4b3d-8746-7b03f06dd136.mp4

## Your Environment
Win10 Firefox Dev. Ed. 110.0b9

**Comment by ianharrigan** [comment]
haha... what? Thats wild... thanks, ill check it out!

**Comment by ianharrigan** [comment]
This should also be fixed - if it works for you, can you close this issue please?

Cheers,
Ian

**Comment by luqyann** [comment]
It's working, thanks.
