### ISSUE TITLE
[BUG] Text is not hidden when closing a dialog (with destroyOnClose = false)

### ISSUE THREAD

**Issue by EliteMasterEric** [haxeui/haxeui-core#515]
## Expected Behavior
Closing a dialog (when `destroyOnClose = false` set for later reuse), text from TextFields should be made invisible to the user like the rest of the dialog.

## Current Behavior
When closing a dialog with `destroyOnClose = false` set, any text from TextFields in that dialog will still be visible even after the window is closed.

## Possible Solution
Not sure what's causing this, maybe the code hiding the dialog is skipping the text, or the text's visibility is being overridden?

## Steps to Reproduce (for bugs)
1. Create a dialog with a text field.
2. Set destroyOnClose = true.
3. Open the dialog, and type in a text field.
4. Close the dialog.

## Test app / minimal test case
```
var dialog:Dialog = cast this.buildComponent("assets/data/dialog.xml");
dialog.destroyOnClose = false;
dialog.closable = true;
dialog.showDialog(true);
```

## Your Environment
* Version used: `haxeui-core git (2f23ce8)`
* Environment name and version (e.g. Chrome 39, node.js 5.4): Haxe Flixel (`haxeui-flixel git d353389`
* Operating System and version (desktop or mobile): Window 10 Desktop

**Comment by ianharrigan** [comment]
This should be fixed now - if it is, can you close.

Cheers,
Ian

**Comment by EliteMasterEric** [comment]
Closed as resolved.
