### ISSUE TITLE
Email Validator only accepts 2-3 letter TLDs.

### ISSUE THREAD

**Issue by Benjie56** [haxeui/haxeui-core#516]
The email validator regex only accepts 2 and 3 character top-level-domains. The current longest TLD is .vermögensberatung (XN--VERMGENSBERATUNG-PWB), which is 24 characters long. The longest possible is 63 characters long.
I personally use a .scot email address, which gets rejected by email fields.

**Comment by ianharrigan** [comment]
fair point - i just grabbed the regex online somewhere.

**Comment by Tezar** [comment]
Could try to fix that.

Two approaches:
1. either relax the pattern to allow for vermögensberatung and friends
2. add (and occasionally update) 10 KiB official [domain list](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)

Any preference @ianharrigan ?

**Comment by ianharrigan** [comment]
my personal preference would be the former, ie, relax the regexp - i just dont like the idea of adding some 10kb file and then having to remember to update it, etc... feels like additional maintenance... ... ... ?
