### ISSUE TITLE
hxwidgets doesn't build with the latest haxe

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [haxeui/haxeui-core#523]
When running `haxe hxwidgets.hxml`, we have a build error

## Expected Behavior

Should build ok.

## Current Behavior
Log snippet

```
/bsata/home/user3/haxelib/haxeui-core/1,5,0/haxe/ui/macros/ComponentMacros.hx:872: characters 107-109 : Reification $v is not allowed outside of `macro` expression
/bsata/home/user3/haxelib/haxeui-core/1,5,0/haxe/ui/constants/SortDirection.hx:3: characters 1-7 : Warning : (WDeprecated) `@:enum abstract` is deprecated in favor of `enum abstract`
/bsata/home/user3/haxelib/haxeui-core/1,5,0/haxe/ui/events/UIEvent.hx:7: characters 1-8 : Build failure
```

## Possible Solution
Unknown
## Steps to Reproduce (for bugs)

1. Under Linux 64-bit, download & install haxe compiler https://build.haxe.org/builds/haxe/linux64/haxe_2023-04-18_development_f9af093.tar.gz
2. Run `haxe hxwidgets.hxml` in project https://github.com/nonlin-lin-chaos-order-etc-etal/haxeui-sample1
3. Build fails

## Test app / minimal test case

Test app https://github.com/nonlin-lin-chaos-order-etc-etal/haxeui-sample1

## Your Environment

* Version used: haxelib/haxeui-core/1,5,0/haxe/ui/
* Operating System and version (desktop or mobile): Debian 11 desktop
* Link to your project: https://github.com/nonlin-lin-chaos-order-etc-etal/haxeui-sample1

**Comment by ianharrigan** [comment]
This is fixed in git version (you'll also need to use git versions of any dependencies), ill be making a new release soon(ish) - maybe the weekend. 

Cheers,
Ian

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
I tried wxWidgets 3.2.2 and 3.1.4 with this version of haxe compiler, had link errors

With stable compiler, wxWidgets 3.1.4 built ok.

So current working sitiation is:

$ wx-config --version
3.1.4
$ haxelib list
haxeui-core: 1.5.0 [git]
haxeui-hxwidgets: 1.5.0 [git]
hxcpp: 4.3.2 [git]
hxWidgets: 1.10.0 [git]

(and haxe is from Debian 11 apt)

**Comment by nonlin-lin-chaos-order-etc-etal** [comment]
@ianharrigan thanks for a heroic work!
