### ISSUE TITLE
[flixel] Incompatible OpenFL-specific code

### ISSUE THREAD

**Issue by MSGhero** [haxeui/haxeui-core#53]
1) https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/components/Label.hx#L20-L22

Doesn't work in Flixel because the `ComponentBase` doesn't extend `flash.display.Sprite` where `mouseChildren` comes from.

2) **Edit**: ah, there's a todo for it down here: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/components/Label.hx#L83-L86

3) https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/components/Label.hx#L100-L101

`textWidth` comes from `flash.text.TextField` rather than from `TextDisplay`

**Comment by ianharrigan** [comment]
Can this be closed?
