### ISSUE TITLE
Compile broken - TextAlign

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#57]
`git/haxe/ui/components/TextField.hx:97: characters 16-40 : haxe.ui.core.TextInput has no field textAlign
git/haxe/ui/components/Label.hx:68: characters 16-42 : haxe.ui.core.TextDisplay has no field textAlign`

**Comment by aW4KeNiNG** [comment]
Hi!

What backend are you using?

**Comment by hoseyjoe** [comment]
It was NME windows.

**Comment by aW4KeNiNG** [comment]
It requires the PR haxeui/haxeui-nme#4 . Ping @ianharrigan 🎱

**Comment by hoseyjoe** [comment]
Closing as duplicate of haxeui/haxeui-nme#4 .

**Comment by ianharrigan** [comment]
Ok, merged now
