### ISSUE TITLE
Build fails for targets with Java code output

### ISSUE THREAD

**Issue by dstrekelj** [haxeui/haxeui-core#6]
## Expected Behavior

Build should pass.
## Current Behavior

Build fails with errors originating at multiple positions in the output source code. These errors are caused by the use and extension of several generic interfaces in component classes.

Sample error message:

```
<path-to-project>\HaxeUIApp\src\haxe\ui\containers\Box.java
error: IClonable cannot be inherited with different arguments: <haxe.ui.containers.Box> and <haxe.ui.core.Component>
error: incompatible types: Box cannot be converted to VBox
error: incompatible types: Box cannot be converted to VBox
```

Complete error log can be found [here](https://gist.github.com/dstrekelj/d6658eefb92f4b861d3252dd17553f14).
## Possible Solution

From Java's perspective, it is illegal for a class to extend different instances of the same generic interface. Java's generics are implemented at compile time through [type erasure](https://docs.oracle.com/javase/tutorial/java/generics/erasure.html). Extending different instances of one generic interface means creation of duplicate bridge methods, and also leads to type casting issues.

A possible solution could lie in bounded type parameters. However, this seems like a Java solution more than a Haxe one.

Issue might be related to HaxeFoundation/haxe#2280, but I'm not sure how much of this is caused by the way Java sources are generated.
## Steps to Reproduce (for bugs)

1. Set up haxeui-kha.
2. Download the haxeui-kha skeleton project from the templates repository.
3. Build for Android.
## Your Environment

- Version used: Latest haxeui-core and haxeui-kha
- Environment name and version (e.g. Chrome 39, node.js 5.4): Android Studio 1.5.1, JDK1.8.0_73
- Operating System and version (desktop or mobile): Windows 10 64bit

**Comment by ianharrigan** [comment]
Just a quick question, presumably this also happens if you just use a `Button` right? Ie, no `VBox` no nothing, just a single button on the screen.
