### ISSUE TITLE
Add codeclimate and checkstyle to repos

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/haxeui-core#61]
Add codeclimate to all relevant haxeui repos. 

- [x] haxeui-core
- [ ] haxeui-openfl
- [ ] haxeui-flambe
- [ ] haxeui-kha
- [ ] haxeui-html5 - mostly working, regexp issue around method names
- [ ] haxeui-pixijs
- [ ] haxeui-nme
- [ ] haxeui-luxe
- [ ] haxeui-hxwidgets
- [x] haxeui-xwt

There is currently an issue with haxe-checkstyle not seeming to work on CC, but working with checkstyle locally is fine until this is resolved (https://github.com/HaxeCheckstyle/haxe-checkstyle/issues/320)

**Comment by ianharrigan** [comment]
@ibilon / @MSGhero - presumably you would prefer a different style for your backends, so ill leave that up to you... :)

**Comment by ianharrigan** [comment]
This is the issue on haxe-checkstyle: https://github.com/HaxeCheckstyle/haxe-checkstyle/issues/320#issuecomment-267760490

**Comment by ibilon** [comment]
Codeclimate/checkstyle added to haxeui-xwt.

haxeui-hxWidgets was already done but I didn't have the badges yet, added now.
