### ISSUE TITLE
Proposal: Improve Binding

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#63]
It would be nice to improve the binding system in a more flexible way.

## Current Behavior

Actually, we have:

```
<hslider id="widthSlider" max="280" value="200"/>
<label id="widthLabel" text="???" styleNames="valueLabel"
       bindTo="widthSlider" bindTransform="${MathUtils.round(value, 2)}"/>
```

## Proposal

```
<hslider id="widthSlider" max="280" value="200"/>
<label id="widthLabel" text="{ MathUtils.round(widthSlider.value, 2) }" styleNames="valueLabel"/>
```

Any expr between { } should be interpreted as bindable. If the user uses a non-bindable property then a compile warning should be visible (just it will work as a simple assignation without bind).
If you think about that, it is cleaner and powerful, and it allows multiple properties with different targets. For example, you can do:

```
<checkbox id="labelVisibleCB" text="Label Visible"/>
<hslider id="minSlider" min="0" max="100" value="50"/>
<hslider id="maxSlider" min="200" max="300" value="250"/>
<hslider id="selectSlider" min="{ minSlider.value }"
                        max="{ maxSlider.value }" 
                        value="200"/>

<label id="sliderValueLabel" text="{ MathUtils.round(selectSlider.value, 2) }" visible="{ labelVisibleCB.value }"/>
<label text="Value > 200" visible="{ selectSlider.value > 200 }"/>
```

The [bindx2](https://github.com/profelis/bindx2) library could be a good start point.

**Comment by ianharrigan** [comment]
I really like this, i think its very flexible and powerful. 

How would be use it on runtime components?

**Comment by ianharrigan** [comment]
I guess a macro for compile time and hscript for runtime? Seems the most sensible option. However, at compile time, im not sure how "{mycomponent.text}" makes anysense

**Comment by ianharrigan** [comment]
something like this would be nice as a test too:

´´´xml
<vbox>
    <textfield id="tf1" text="75" />
    <textfield id="tf2" text="50"  />
    <textfield id="tf3" text="${tf1.text}" />
    <label text="Test1: ${slider1.pos - slider2.pos}" />
    <label text="Test2: ${slider1.pos} - ${slider2.pos}" />
    <hslider id="slider1" pos="${tf3.text}" />
    <hslider id="slider2" pos="${tf2.text}" />
    <button width="${slider1.pos}" height="${slider2.pos}%" />
</vbox>
´´´
