### ISSUE TITLE
idk how to fix

### ISSUE THREAD

**Issue by LeonGamerPS1** [haxeui/haxeui-core#645]
## Expected Behavior

```

```

## Current Behavior

```
C:/haxelib/haxeui-core/git/haxe/ui/containers/Panel.hx:46: characters 30-40 : Field set_height overrides parent class with different or incomplete type
C:/haxelib/haxeui-core/git/haxe/ui/backend/ComponentBase.hx:972: characters 32-42 : ... Base field is defined here
C:/haxelib/haxeui-core/git/haxe/ui/containers/Panel.hx:46: characters 30-40 : ... error: Null<Float> should be Float
C:/haxelib/haxeui-core/git/haxe/ui/containers/Panel.hx:46: characters 30-40 : ... have: (...) -> Null<...>
C:/haxelib/haxeui-core/git/haxe/ui/containers/Panel.hx:46: characters 30-40 : ... want: (...) -> Float
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ianharrigan** [comment]
oh, i think i just broke this with the latest commit two secs

**Comment by ianharrigan** [comment]
Right, should be fixed now - you'll need to pull latest again - my bad - should have tested on a static haxe target before committing... 🤦‍♂️

**Comment by LeonGamerPS1** [comment]
thank
