### ISSUE TITLE
HScript + Variant problem?

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#66]
In my test in the PR #65, I have detected a problem when I change the width/height slider. It didn't work in HScript. I have debugged in html5 backend and assignation is a Array<Float> (and it should be a Float). At start, it is assigned multiple times as Float, after that it is a Array and it stopped to work.

## Expected Behavior
Hscript + Variant should work.

## Current Behavior
When it assigns the Array, the Float value is NaN.

## Possible Solution
It requires investigation.

## Steps to Reproduce (for bugs
1. Go to PR #65 and download the example.
2. Compile for html5 (other backends have the same problem).
3. Move the width/height slider.

**Comment by ianharrigan** [comment]
This reproduces the issue more simply: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<vbox id="main" style="padding:10px;">
    <script>
        function test1() {
            test.width = slider1.pos;
        }
        
        function test2() {
            test.width = slider2.value;
        }
    </script>
    
    <hslider id="slider1" pos="100" min="50" max="150" onchange="test1()" />
    <hslider id="slider2" pos="100" min="50" max="150" onchange="test2()" />
    <button id="test" text="Test" width="100" />
</vbox>
```

**Comment by ianharrigan** [comment]
Looking at traces it seems that its converting it into a string.

**Comment by aW4KeNiNG** [comment]
It works 👍
