### ISSUE TITLE
No grid component

### ISSUE THREAD

**Issue by duoguo** [haxeui/haxeui-core#68]
No grid component

**Comment by aW4KeNiNG** [comment]
You can use the PR #65 for Grid. It is an initial implementation.

**Comment by ianharrigan** [comment]
I think this should be split into two separate issues. One for grids, and one for menubars. @duoguo - is this something you are happy to do? (My thoughts would be rename this to "No grid" and open a new one for "No Menubar")

Cheers,
Ian

**Comment by ianharrigan** [comment]
OK, since im here, im going to make the edits and split them

**Comment by ianharrigan** [comment]
Closing this as no feedback from original poster.
