### ISSUE TITLE
Logging / no silent fails

### ISSUE THREAD

**Issue by sh-dave** [haxeui/haxeui-core#7]
I just tried to position a button on the screen.

```haxe
{...    
    button.left = button.top = 4;
    someAbsoluteContainerThingy.addComponent(button);
...}
```
This didn't work so i stepped through the code and noticed the ```if (_ready == false) return``` in Component.moveComponent. Just swapping the 2 lines in my code (addComponent() before assigning left + top) did the trick.

## Expected Behavior
It would be nice to be notified about the missing layout.

## Current Behavior
The code silently fails / doesn't do as i expected.

## Possible Solution
Notify me if i'm being stupid or do stuff differently than expected. Adding logging/assertions would go a long way in these situations. This should probably be enabled by default for debug/development builds but also removable for release build.

```haxe
public function moveComponent(left:Null<Float>, top:Null<Float>) {
    if (_ready == false) {
        usage_log('moveComponent for "${id}" requires an assigned parent container');
        return;
    }
}
```

**Comment by ianharrigan** [comment]
Let me just have a quick check of implications, but i feel like that `_ready` check shouldnt be there. I might have been over cautious when adding it. Either way, i dont think its reasonable to have to put your UI code in a specific order for it to work correctly.

**Comment by ianharrigan** [comment]
Can you restest with latest from github? As i suspected i dont think the `_ready` check is needed (it was removed from `resizeComponent` also - so probably an over cautious artifact left over)

**Comment by sh-dave** [comment]
Yup, works either way now.

**Comment by ianharrigan** [comment]
Perfect.... Can you close if you are happy its sorted? Cheers!

**Comment by sh-dave** [comment]
Sure will do. And just to add, i think it wouldn't be unreasonable to require a certain code order (maybe for performance issues or making the libraries code way more complicated otherwise). But if that's the case, then some sort of notification would be good.

**Comment by ianharrigan** [comment]
Yeah, i agree that if it needs to be in a specific order then there should be some type of notification, or warning if you dont have that order. But for something as simple as setting components props before adding it to a container i dont think a specific order is reasonable (or sensible) - and in this case it was just a little bit of left over code that didnt really need to be there anyway, so enforcing an order for no reason is even more unreasonable. 

Anyways, all sorted now - thanks for the finding! :)
