### ISSUE TITLE
Slider wrong value while dragging

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#70]
Slider pos has a wrong value when you click and drag the value in the background in the slider.  I'd rather not fix because I don't use rangeStart/rangeEnd for now and maybe I can broken something about that.

## Expected Behavior
The value should be equal to the mouse position.

## Current Behavior
The value maintains the initial offset while the mouse is dragged.

## Possible Solution
The problem is in `_mouseDownOffset` in the `_onRangeEndThumbMouseDown` function.
`_activeThumb.screenLeft` has the value before of animation, so it is wrong when the mouse is moved.

## Steps to Reproduce (for bugs)
1. Click in the background
2. Drag mouse with left button pressed.

## Media
https://vimeo.com/197234589

## Test app / minimal test case
```
<?xml version="1.0" encoding="utf-8"?>
<vbox id="main" width="100%" height="100%">
    <hslider width="100%"/>
</vbox>
```

## Context
It is a big problem in mobile apps.

## Your Environment
It didn't work in OpenFL and NME (and maybe other backends
It works in HTML5.

**Comment by ianharrigan** [comment]
Initial investigations show this is related to actuate - if you remove the actuate lib (which means there will be no animations ofc) the issue goes away - investigating further.

**Comment by ianharrigan** [comment]
Should be working now, can you retest and close?

Thanks.

**Comment by aW4KeNiNG** [comment]
It works. Thanks @ianharrigan  =)
