### ISSUE TITLE
Skip ByteConverter #if flash

### ISSUE THREAD

**Issue by MSGhero** [haxeui/haxeui-core#81]
`bytes.getData()` is already a BA on flash target, no need to convert manually there I think. I can make the PR, but I will forget in a few days without this reminder.

**Comment by azrafe7** [comment]
Hey @MSGhero, as a heads-up, there are also related `ByteArray.fromBytes()` functions in both [openfl](https://github.com/openfl/openfl/blob/35d0f8bb0413b317ff509cb2b651e6a6ea781bea/openfl/utils/ByteArray.hx#L87) and [nme](https://github.com/haxenme/nme/blob/652f0a9eeecdb64e68c3d9505cbfaa75ee3ad009/src/nme/utils/ByteArray.hx#L347) that should bypass the copying.

With the caveat that both need some testing to see if target-specific endianness/ARGB-format has an impact on how haxeui use the result later.
