### ISSUE TITLE
Proposal: ListView with multiple selection

### ISSUE THREAD

**Issue by aW4KeNiNG** [haxeui/haxeui-core#84]
I think that ListView can be changed to manage multiple selection optionally. For example it is a requirement in 2 apps mine. I have implemented it in an internal way, but I can share it.

Also it is useful to implement "long pressure" to select the item. 

Changes:

__ItemRenderer:__

* Add selected:Bool property.
* Add allowSelection:Bool property.

__ListView:__

* Add selectedItems:Array<Dynamic> property.
* Add selectedIndices:Array<Int> property.
* Add selectedIndex:Int property. It should return the first index (or maybe the last index)
* Add allowSelection:Bool property. True by default.
* Add allowMultipleSelection:Bool property. If it is false (by default), only 1 item can be selected.
* Add pressSelectionTime:Int (maybe other name is more descriptive??) property. Time in MS to select one item (default is 0). The target for that is if you want to distinguish between selection or click in the itemrenderer. For example: I want to select multiple items with 500 ms and my UI will show a "Delete" button to delete the items selected. Also I want to click in one item to see info view about that.
* Also we can add an opacity animation when the item is selected/unselected. 

Here a video:

https://www.dropbox.com/s/go0fyd8z45lxrly/listview_multiselection.mp4?dl=0

What do you think?

**Comment by ianharrigan** [comment]
This seems totally sensible to me. I think a nice enhancement would be to use shift to select them too, not sure how that fits into your proposal though. 

I think just have this ability would mean we could later add a way to change the flag if shift is pressed.

**Comment by ianharrigan** [comment]
btw, unrelated, but im just about to embark on a mobile iteration. Ive noticed it seems from that video that you app has "drag to scroll" - do you mind sharing (email or gist or whatever) and is it inertial?

**Comment by aW4KeNiNG** [comment]
Hi. Sorry for the late reply. Bad days for me :(

Currently it is a basic implementation without inertial. I have seen that you have already implemented it :)

About the selection, this weekend I will share the branch with the changes, so we can discuss it.

**Comment by aW4KeNiNG** [comment]
What do you think a "multiselectionMode" property?

It could be: disabled, shift, ¿ctrl?, long-press...

About long-press in my apps. I'm using long press to select the first item. After that it is a simple click. Do you see it right? Maybe we could have long-press and first-long-press or something like that.

**Comment by ianharrigan** [comment]
Cleaning up issues, pretty sure this is done! :)

Hope you are well man!

Ian
