### ISSUE TITLE
Component parser error when binding

### ISSUE THREAD

**Issue by tokiop** [haxeui/haxeui-core#88]
Binding seems to crash compilation of ComponentParser under some conditions, not sure if it's an error on my side.

## Expected Behavior

Compilation :)

## Current Behavior

No compilation :'(

## Possible Solution

Initializing `_nextId` in [ComponentParser.hx](https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/parsers/ui/ComponentParser.hx#L51) allow compilation : 

        private static var _nextId:Int = 0;

## Steps to Reproduce

Using this component in ui.xml :

        <hbox>
            <label text="Slider:" />
            <hslider id="slider" min="1" max="200" value="5" />
            <label bindTo="slider" />
        </hbox>

Compilation fails with : 

	$ openfl test neko
	../haxeui-core/haxe/ui/parsers/ui/ComponentParser.hx:54: characters 8-17 : +
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:224: characters 31-55 : Called from
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:50: characters 12-43 : Called from
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:55: characters 20-69 : Called from
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:55: characters 20-69 : Called from
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:55: characters 20-69 : Called from
	../haxeui-core/haxe/ui/parsers/ui/XMLParser.hx:21: characters 8-56 : Called from
	../haxeui-core/haxe/ui/macros/ComponentMacros.hx:104: characters 30-132 : Called from
	../haxeui-core/haxe/ui/macros/ComponentMacros.hx:40: characters 24-111 : Called from

## Test app / minimal test case

[component-parser-error.zip](https://github.com/haxeui/haxeui-core/files/719402/component-parser-error.zip)

## Your Environment

* git versions of haxeui-core and haxeui-openfl
* haxe 3.2.1 and neko 2.0.0
* Debian Stretch

Thanks for you work and dedication !

**Comment by ianharrigan** [comment]
Right, i see this make sense... `_nextId` is essentially null on neko...

**Comment by ianharrigan** [comment]
Can we recheck this and close if all fine?

Thanks!

**Comment by tokiop** [comment]
Fix confirmed, thanks !
