### ISSUE TITLE
Invalid field access (scaleMode) on Neko

### ISSUE THREAD

**Issue by fulopm** [haxeui/haxeui-core#9]
## Expected Behavior
The program should run.

## Current Behavior
After compiling the app with "haxe build.hxml", and running with "neko client.n", I'm getting this error:

> fulopm@pc:~/haxeprojects/client$ neko client
> ThemeManager.hx:56: WARNING: could not find styles/main.css
> Parser.hx:1107: Invalid value #E6E6E6 for css background
> Parser.hx:1107: Invalid value #F1F1F1 for css background
> Parser.hx:1107: Invalid value #C2C2C2 for css background
> Parser.hx:1107: Invalid value #D4DEE8 for css background
> Parser.hx:1107: Invalid value #DEE8F2 for css background
> Parser.hx:1107: Invalid value #B4BEC8 for css background
> Parser.hx:1107: Invalid value #FFFFFF for css background
> Parser.hx:1107: Invalid value #E6E6E6 for css background
> ThemeManager.hx:56: WARNING: could not find styles/default/main.css
> Called from util.SharedConstants::$statics line 1
> Called from Main::main line 10
> Called from ui.UI::$init line 8
> Called from a C function
> Called from ui.UI::new line 16
> Called from haxe.ui.HaxeUIApp::ready line 16
> Called from haxe.ui.HaxeUIApp::init line 24
> Called from haxe.ui.Toolkit::init line 46
> Called from haxe.ui.Toolkit::get_screen line 69
> Called from haxe.ui.core.Screen::get_instance line 35
> Called from haxe.ui.core.Screen::$init line 26
> Called from a C function
> Called from haxe.ui.core.Screen::new line 46
> Called from a C function
> Called from haxe.ui.backend.ScreenBase::new line 18
> Uncaught exception - Invalid field access : scaleMode

## Steps to Reproduce (for bugs)
1. Use [my code](https://gist.github.com/fulopm/c90dd931d0b24ac725782b282f4fbdbc), and compile it to Neko target. ([build.hxml](https://gist.github.com/fulopm/772e5a6f7d6e0352bf64c3d3d0717749))
2. Run the compiled Neko file, and you'll get invalid field access as described before.

## Test app / minimal test case
Included in the "Steps to Reproduce" 

## Your Environment
HaxeUI is V2 of course.
OS: Lubuntu 16.04 x64
neko: 2.1.0
haxe: 3.2.1
openfl: 4.0.3-Ldfc8L
lime: 3.0.3

**Comment by ianharrigan** [comment]
Is this still an issue? Do you have latest openfl? It may be an issue there, im on git version and all openfl targets work fine. 

I had to change your code slightly, but certainly didnt get a runtime error or anything like that

**Comment by ianharrigan** [comment]
Closing this issue as cant reproduce and havent heard anything from reporter, think it is/was neko/openfl issue
