### ISSUE TITLE
TextArea - wordWrap inconsistant

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#97]
HTMl target has wordwrap enabled by default, other targets are not the case: Openfl (html5,windows), NME (windows)
I added this to core since there is no property to adjust wordwrap.  

## Expected Behavior
A wordWrap property on the textarea so you can enable or disable it.

## Current Behavior
some targets wrap auto some do not

## Possible Solution
You should have a wordWrap property on the textarea so you can enable or disable it.

## Media
without wordwrap
![image](https://cloud.githubusercontent.com/assets/2074385/22445848/5ffaf168-e6fe-11e6-884a-c2e724e15b6a.png)

with wordwrap
![image](https://cloud.githubusercontent.com/assets/2074385/22445864/71360882-e6fe-11e6-99f8-c1e33e83e577.png)

Project
[TextArea Test.zip](https://github.com/haxeui/haxeui-core/files/740720/TextArea.Test.zip)

**Comment by ianharrigan** [comment]
OK, looks good... I have recently added the ability to scroll horizontally on the text areas too... any chance of a PR?

**Comment by hoseyjoe** [comment]
I will make some attempts at a PR.

**Comment by ianharrigan** [comment]
OK, dont worry about it if you dont want to, ill probably be faster as i know the backends... what did you do and where, that should be enough. 

Cheers,
Ian

**Comment by ianharrigan** [comment]
Can we retest this and close as required? 

Thanks!

**Comment by hoseyjoe** [comment]
I think this is done...Except.  A long word in NME breaks at whatever letter comes next.  Openfl creates a horizontal scroll to accomodate.  The HTML5 version matches NME.  So the odd ball is Openfl in this case

NME
![image](https://cloud.githubusercontent.com/assets/2074385/22533665/4c694288-e8a4-11e6-9a85-ae8faf71cbca.png)

Openfl
![image](https://cloud.githubusercontent.com/assets/2074385/22533671/59f847d2-e8a4-11e6-8999-444958b5a5e7.png)
