### ISSUE TITLE
Text Area- No default height

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#98]
Add textarea without height doesn't display anything

## Expected Behavior
Autosizes to minimum height

Maybe have a maximum height property that it would be able to auto size to in the event of growth?

[TextArea Test.zip](https://github.com/haxeui/haxeui-core/files/740725/TextArea.Test.zip)

**Comment by ianharrigan** [comment]
Can we retest this and close as required? 

Thanks!
